FROM golang:1.24-alpine
ENV GOTOOLCHAIN=auto
RUN apk add --no-cache ca-certificates
RUN go install github.com/air-verse/air@latest
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ENTRYPOINT ["air"]
