// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ai.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAIUsageByDay = `-- name: GetAIUsageByDay :many
SELECT
    date_trunc($1, created_at)::timestamptz AS bucket,
    model,
    SUM(prompt_tokens) AS total_prompt_tokens,
    SUM(completion_tokens) AS total_completion_tokens,
    SUM(total_tokens) AS total_tokens,
    COUNT(*) AS request_count
FROM okt_system.ai_usage
WHERE ($2::timestamptz IS NULL OR created_at >= $2)
  AND ($3::timestamptz IS NULL OR created_at < $3)
  AND ($4::uuid IS NULL OR repository_id = $4)
GROUP BY bucket, model
ORDER BY bucket, model
`

type GetAIUsageByDayParams struct {
	Bucket       string             `json:"bucket"`
	From         pgtype.Timestamptz `json:"from"`
	To           pgtype.Timestamptz `json:"to"`
	RepositoryID pgtype.UUID        `json:"repository_id"`
}

type GetAIUsageByDayRow struct {
	Bucket                pgtype.Timestamptz `json:"bucket"`
	Model                 string             `json:"model"`
	TotalPromptTokens     int64              `json:"total_prompt_tokens"`
	TotalCompletionTokens int64              `json:"total_completion_tokens"`
	TotalTokens           int64              `json:"total_tokens"`
	RequestCount          int64              `json:"request_count"`
}

// Time-bucketed consumption for the over-time chart. The bucket
// width (day/week/month) is passed as a string param to date_trunc;
// sqlc cannot parameterize identifiers, so the literal is bound at
// exec time via the Bucket param.
func (q *Queries) GetAIUsageByDay(ctx context.Context, arg GetAIUsageByDayParams) ([]GetAIUsageByDayRow, error) {
	rows, err := q.db.Query(ctx, getAIUsageByDay,
		arg.Bucket,
		arg.From,
		arg.To,
		arg.RepositoryID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAIUsageByDayRow
	for rows.Next() {
		var i GetAIUsageByDayRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Model,
			&i.TotalPromptTokens,
			&i.TotalCompletionTokens,
			&i.TotalTokens,
			&i.RequestCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAIUsageByOperation = `-- name: GetAIUsageByOperation :many
SELECT
    operation,
    model,
    COUNT(*) AS request_count,
    SUM(prompt_tokens) AS total_prompt_tokens,
    SUM(completion_tokens) AS total_completion_tokens,
    SUM(total_tokens) AS total_tokens
FROM okt_system.ai_usage
WHERE ($1::timestamptz IS NULL OR created_at >= $1)
  AND ($2::timestamptz IS NULL OR created_at < $2)
  AND ($3::uuid IS NULL OR repository_id = $3)
GROUP BY operation, model
ORDER BY total_tokens DESC
`

type GetAIUsageByOperationParams struct {
	From         pgtype.Timestamptz `json:"from"`
	To           pgtype.Timestamptz `json:"to"`
	RepositoryID pgtype.UUID        `json:"repository_id"`
}

type GetAIUsageByOperationRow struct {
	Operation             string `json:"operation"`
	Model                 string `json:"model"`
	RequestCount          int64  `json:"request_count"`
	TotalPromptTokens     int64  `json:"total_prompt_tokens"`
	TotalCompletionTokens int64  `json:"total_completion_tokens"`
	TotalTokens           int64  `json:"total_tokens"`
}

func (q *Queries) GetAIUsageByOperation(ctx context.Context, arg GetAIUsageByOperationParams) ([]GetAIUsageByOperationRow, error) {
	rows, err := q.db.Query(ctx, getAIUsageByOperation, arg.From, arg.To, arg.RepositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAIUsageByOperationRow
	for rows.Next() {
		var i GetAIUsageByOperationRow
		if err := rows.Scan(
			&i.Operation,
			&i.Model,
			&i.RequestCount,
			&i.TotalPromptTokens,
			&i.TotalCompletionTokens,
			&i.TotalTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAIUsageByRepository = `-- name: GetAIUsageByRepository :many
SELECT
    repository_id,
    model,
    COUNT(*) AS request_count,
    SUM(prompt_tokens) AS total_prompt_tokens,
    SUM(completion_tokens) AS total_completion_tokens,
    SUM(total_tokens) AS total_tokens
FROM okt_system.ai_usage
WHERE ($1::timestamptz IS NULL OR created_at >= $1)
  AND ($2::timestamptz IS NULL OR created_at < $2)
  AND ($3::uuid IS NULL OR repository_id = $3)
GROUP BY repository_id, model
ORDER BY total_tokens DESC
`

type GetAIUsageByRepositoryParams struct {
	From         pgtype.Timestamptz `json:"from"`
	To           pgtype.Timestamptz `json:"to"`
	RepositoryID pgtype.UUID        `json:"repository_id"`
}

type GetAIUsageByRepositoryRow struct {
	RepositoryID          pgtype.UUID `json:"repository_id"`
	Model                 string      `json:"model"`
	RequestCount          int64       `json:"request_count"`
	TotalPromptTokens     int64       `json:"total_prompt_tokens"`
	TotalCompletionTokens int64       `json:"total_completion_tokens"`
	TotalTokens           int64       `json:"total_tokens"`
}

func (q *Queries) GetAIUsageByRepository(ctx context.Context, arg GetAIUsageByRepositoryParams) ([]GetAIUsageByRepositoryRow, error) {
	rows, err := q.db.Query(ctx, getAIUsageByRepository, arg.From, arg.To, arg.RepositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAIUsageByRepositoryRow
	for rows.Next() {
		var i GetAIUsageByRepositoryRow
		if err := rows.Scan(
			&i.RepositoryID,
			&i.Model,
			&i.RequestCount,
			&i.TotalPromptTokens,
			&i.TotalCompletionTokens,
			&i.TotalTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAIUsageBySource = `-- name: GetAIUsageBySource :many
SELECT
    source_id,
    repository_id,
    model,
    COUNT(*) AS request_count,
    SUM(prompt_tokens) AS total_prompt_tokens,
    SUM(completion_tokens) AS total_completion_tokens,
    SUM(total_tokens) AS total_tokens
FROM okt_system.ai_usage
WHERE ($1::timestamptz IS NULL OR created_at >= $1)
  AND ($2::timestamptz IS NULL OR created_at < $2)
  AND ($3::uuid IS NULL OR repository_id = $3)
GROUP BY source_id, repository_id, model
ORDER BY total_tokens DESC
`

type GetAIUsageBySourceParams struct {
	From         pgtype.Timestamptz `json:"from"`
	To           pgtype.Timestamptz `json:"to"`
	RepositoryID pgtype.UUID        `json:"repository_id"`
}

type GetAIUsageBySourceRow struct {
	SourceID              pgtype.UUID `json:"source_id"`
	RepositoryID          pgtype.UUID `json:"repository_id"`
	Model                 string      `json:"model"`
	RequestCount          int64       `json:"request_count"`
	TotalPromptTokens     int64       `json:"total_prompt_tokens"`
	TotalCompletionTokens int64       `json:"total_completion_tokens"`
	TotalTokens           int64       `json:"total_tokens"`
}

func (q *Queries) GetAIUsageBySource(ctx context.Context, arg GetAIUsageBySourceParams) ([]GetAIUsageBySourceRow, error) {
	rows, err := q.db.Query(ctx, getAIUsageBySource, arg.From, arg.To, arg.RepositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAIUsageBySourceRow
	for rows.Next() {
		var i GetAIUsageBySourceRow
		if err := rows.Scan(
			&i.SourceID,
			&i.RepositoryID,
			&i.Model,
			&i.RequestCount,
			&i.TotalPromptTokens,
			&i.TotalCompletionTokens,
			&i.TotalTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAIUsageSummary = `-- name: GetAIUsageSummary :many
SELECT
    provider,
    model,
    COUNT(*) AS request_count,
    SUM(prompt_tokens) AS total_prompt_tokens,
    SUM(completion_tokens) AS total_completion_tokens,
    SUM(total_tokens) AS total_tokens
FROM okt_system.ai_usage
GROUP BY provider, model
ORDER BY total_tokens DESC
`

type GetAIUsageSummaryRow struct {
	Provider              string `json:"provider"`
	Model                 string `json:"model"`
	RequestCount          int64  `json:"request_count"`
	TotalPromptTokens     int64  `json:"total_prompt_tokens"`
	TotalCompletionTokens int64  `json:"total_completion_tokens"`
	TotalTokens           int64  `json:"total_tokens"`
}

func (q *Queries) GetAIUsageSummary(ctx context.Context) ([]GetAIUsageSummaryRow, error) {
	rows, err := q.db.Query(ctx, getAIUsageSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAIUsageSummaryRow
	for rows.Next() {
		var i GetAIUsageSummaryRow
		if err := rows.Scan(
			&i.Provider,
			&i.Model,
			&i.RequestCount,
			&i.TotalPromptTokens,
			&i.TotalCompletionTokens,
			&i.TotalTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAIUsageSummaryInRange = `-- name: GetAIUsageSummaryInRange :many

SELECT
    provider,
    model,
    operation,
    COUNT(*) AS request_count,
    SUM(prompt_tokens) AS total_prompt_tokens,
    SUM(completion_tokens) AS total_completion_tokens,
    SUM(total_tokens) AS total_tokens
FROM okt_system.ai_usage
WHERE ($1::timestamptz IS NULL OR created_at >= $1)
  AND ($2::timestamptz IS NULL OR created_at < $2)
  AND ($3::uuid IS NULL OR repository_id = $3)
GROUP BY provider, model, operation
ORDER BY total_tokens DESC
`

type GetAIUsageSummaryInRangeParams struct {
	From         pgtype.Timestamptz `json:"from"`
	To           pgtype.Timestamptz `json:"to"`
	RepositoryID pgtype.UUID        `json:"repository_id"`
}

type GetAIUsageSummaryInRangeRow struct {
	Provider              string `json:"provider"`
	Model                 string `json:"model"`
	Operation             string `json:"operation"`
	RequestCount          int64  `json:"request_count"`
	TotalPromptTokens     int64  `json:"total_prompt_tokens"`
	TotalCompletionTokens int64  `json:"total_completion_tokens"`
	TotalTokens           int64  `json:"total_tokens"`
}

// Dashboard queries. The dashboard fetches several rollups in
// parallel; each query takes an optional date range (from / to)
// and an optional repository_id filter so the UI can scope to a
// single repo. sqlc.narg marks the param as nullable so a NULL
// value matches "no filter" without a separate query.
func (q *Queries) GetAIUsageSummaryInRange(ctx context.Context, arg GetAIUsageSummaryInRangeParams) ([]GetAIUsageSummaryInRangeRow, error) {
	rows, err := q.db.Query(ctx, getAIUsageSummaryInRange, arg.From, arg.To, arg.RepositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAIUsageSummaryInRangeRow
	for rows.Next() {
		var i GetAIUsageSummaryInRangeRow
		if err := rows.Scan(
			&i.Provider,
			&i.Model,
			&i.Operation,
			&i.RequestCount,
			&i.TotalPromptTokens,
			&i.TotalCompletionTokens,
			&i.TotalTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIUsageByModel = `-- name: ListAIUsageByModel :many
SELECT id, task_id, model, provider, prompt_tokens, completion_tokens, total_tokens, created_at, repository_id, source_id, operation FROM okt_system.ai_usage
WHERE model = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAIUsageByModelParams struct {
	Model string `json:"model"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListAIUsageByModel(ctx context.Context, arg ListAIUsageByModelParams) ([]OktSystemAiUsage, error) {
	rows, err := q.db.Query(ctx, listAIUsageByModel, arg.Model, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktSystemAiUsage
	for rows.Next() {
		var i OktSystemAiUsage
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Model,
			&i.Provider,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.CreatedAt,
			&i.RepositoryID,
			&i.SourceID,
			&i.Operation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIUsageByProvider = `-- name: ListAIUsageByProvider :many
SELECT id, task_id, model, provider, prompt_tokens, completion_tokens, total_tokens, created_at, repository_id, source_id, operation FROM okt_system.ai_usage
WHERE provider = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAIUsageByProviderParams struct {
	Provider string `json:"provider"`
	Limit    int32  `json:"limit"`
}

func (q *Queries) ListAIUsageByProvider(ctx context.Context, arg ListAIUsageByProviderParams) ([]OktSystemAiUsage, error) {
	rows, err := q.db.Query(ctx, listAIUsageByProvider, arg.Provider, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktSystemAiUsage
	for rows.Next() {
		var i OktSystemAiUsage
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Model,
			&i.Provider,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.CreatedAt,
			&i.RepositoryID,
			&i.SourceID,
			&i.Operation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIUsageByTask = `-- name: ListAIUsageByTask :many
SELECT id, task_id, model, provider, prompt_tokens, completion_tokens, total_tokens, created_at, repository_id, source_id, operation FROM okt_system.ai_usage
WHERE task_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAIUsageByTask(ctx context.Context, taskID *string) ([]OktSystemAiUsage, error) {
	rows, err := q.db.Query(ctx, listAIUsageByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktSystemAiUsage
	for rows.Next() {
		var i OktSystemAiUsage
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Model,
			&i.Provider,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.CreatedAt,
			&i.RepositoryID,
			&i.SourceID,
			&i.Operation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAIUsage = `-- name: RecordAIUsage :exec
INSERT INTO okt_system.ai_usage (
    task_id, model, provider,
    prompt_tokens, completion_tokens, total_tokens,
    repository_id, source_id, operation
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type RecordAIUsageParams struct {
	TaskID           *string     `json:"task_id"`
	Model            string      `json:"model"`
	Provider         string      `json:"provider"`
	PromptTokens     int32       `json:"prompt_tokens"`
	CompletionTokens int32       `json:"completion_tokens"`
	TotalTokens      int32       `json:"total_tokens"`
	RepositoryID     pgtype.UUID `json:"repository_id"`
	SourceID         pgtype.UUID `json:"source_id"`
	Operation        string      `json:"operation"`
}

func (q *Queries) RecordAIUsage(ctx context.Context, arg RecordAIUsageParams) error {
	_, err := q.db.Exec(ctx, recordAIUsage,
		arg.TaskID,
		arg.Model,
		arg.Provider,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.RepositoryID,
		arg.SourceID,
		arg.Operation,
	)
	return err
}
