// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: api_keys.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAPIKeysByUser = `-- name: CountAPIKeysByUser :one
SELECT count(*) FROM okt_system.api_keys WHERE user_id = $1
`

func (q *Queries) CountAPIKeysByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAPIKeysByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO okt_system.api_keys (
    user_id, name, token_hash, prefix, repository_id, permissions, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, token_hash, prefix, repository_id, permissions, expires_at, last_used_at, revoked_at, created_at
`

type CreateAPIKeyParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	Name         string             `json:"name"`
	TokenHash    string             `json:"token_hash"`
	Prefix       string             `json:"prefix"`
	RepositoryID pgtype.UUID        `json:"repository_id"`
	Permissions  []string           `json:"permissions"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (OktSystemApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
		arg.RepositoryID,
		arg.Permissions,
		arg.ExpiresAt,
	)
	var i OktSystemApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.RepositoryID,
		&i.Permissions,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredAPIKeys = `-- name: DeleteExpiredAPIKeys :exec
DELETE FROM okt_system.api_keys
WHERE expires_at IS NOT NULL AND expires_at < now() AND revoked_at IS NULL
`

func (q *Queries) DeleteExpiredAPIKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAPIKeys)
	return err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, user_id, name, token_hash, prefix, repository_id, permissions, expires_at, last_used_at, revoked_at, created_at FROM okt_system.api_keys WHERE id = $1
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (OktSystemApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i OktSystemApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.RepositoryID,
		&i.Permissions,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByTokenHash = `-- name: GetAPIKeyByTokenHash :one
SELECT id, user_id, name, token_hash, prefix, repository_id, permissions, expires_at, last_used_at, revoked_at, created_at FROM okt_system.api_keys
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetAPIKeyByTokenHash(ctx context.Context, tokenHash string) (OktSystemApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByTokenHash, tokenHash)
	var i OktSystemApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.RepositoryID,
		&i.Permissions,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, user_id, name, prefix, repository_id, permissions, expires_at,
       last_used_at, revoked_at, created_at
FROM okt_system.api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListAPIKeysByUserRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Name         string             `json:"name"`
	Prefix       string             `json:"prefix"`
	RepositoryID pgtype.UUID        `json:"repository_id"`
	Permissions  []string           `json:"permissions"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID pgtype.UUID) ([]ListAPIKeysByUserRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysByUserRow
	for rows.Next() {
		var i ListAPIKeysByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.RepositoryID,
			&i.Permissions,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE okt_system.api_keys SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.UserID)
	return err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE okt_system.api_keys SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}
