// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditEvents = `-- name: CountAuditEvents :one
SELECT count(*) FROM okt_system.permission_audit a
WHERE ($1::uuid IS NULL OR a.repository_id = $1)
  AND ($2::text IS NULL OR a.action = $2)
  AND ($3::uuid IS NULL OR a.actor_user_id = $3)
  AND ($4::text IS NULL OR a.object = $4)
  AND ($5::timestamptz IS NULL OR a.occurred_at >= $5)
  AND ($6::timestamptz IS NULL OR a.occurred_at <= $6)
`

type CountAuditEventsParams struct {
	RepositoryID pgtype.UUID        `json:"repository_id"`
	Action       *string            `json:"action"`
	ActorUserID  pgtype.UUID        `json:"actor_user_id"`
	Object       *string            `json:"object"`
	From         pgtype.Timestamptz `json:"from"`
	To           pgtype.Timestamptz `json:"to"`
}

func (q *Queries) CountAuditEvents(ctx context.Context, arg CountAuditEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEvents,
		arg.RepositoryID,
		arg.Action,
		arg.ActorUserID,
		arg.Object,
		arg.From,
		arg.To,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAuditEventsOlderThan = `-- name: DeleteAuditEventsOlderThan :execrows
DELETE FROM okt_system.permission_audit WHERE occurred_at < $1
`

func (q *Queries) DeleteAuditEventsOlderThan(ctx context.Context, occurredAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuditEventsOlderThan, occurredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAuditActions = `-- name: ListAuditActions :many
SELECT DISTINCT action FROM okt_system.permission_audit ORDER BY action
`

func (q *Queries) ListAuditActions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAuditActions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var action string
		if err := rows.Scan(&action); err != nil {
			return nil, err
		}
		items = append(items, action)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT
    a.id,
    a.occurred_at,
    a.actor_user_id,
    a.actor_username,
    a.action,
    a.object,
    a.repository_id,
    a.target,
    a.detail,
    a.source_url,
    u.email AS actor_email
FROM okt_system.permission_audit a
LEFT JOIN users u ON u.id = a.actor_user_id
WHERE ($1::uuid IS NULL OR a.repository_id = $1)
  AND ($2::text IS NULL OR a.action = $2)
  AND ($3::uuid IS NULL OR a.actor_user_id = $3)
  AND ($4::text IS NULL OR a.object = $4)
  AND ($5::timestamptz IS NULL OR a.occurred_at >= $5)
  AND ($6::timestamptz IS NULL OR a.occurred_at <= $6)
ORDER BY a.occurred_at DESC
LIMIT $8 OFFSET $7
`

type ListAuditEventsParams struct {
	RepositoryID pgtype.UUID        `json:"repository_id"`
	Action       *string            `json:"action"`
	ActorUserID  pgtype.UUID        `json:"actor_user_id"`
	Object       *string            `json:"object"`
	From         pgtype.Timestamptz `json:"from"`
	To           pgtype.Timestamptz `json:"to"`
	PageOffset   int32              `json:"page_offset"`
	LimitRows    int32              `json:"limit_rows"`
}

type ListAuditEventsRow struct {
	ID            int64              `json:"id"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	ActorUserID   pgtype.UUID        `json:"actor_user_id"`
	ActorUsername string             `json:"actor_username"`
	Action        string             `json:"action"`
	Object        string             `json:"object"`
	RepositoryID  pgtype.UUID        `json:"repository_id"`
	Target        *string            `json:"target"`
	Detail        []byte             `json:"detail"`
	SourceUrl     *string            `json:"source_url"`
	ActorEmail    *string            `json:"actor_email"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ListAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.RepositoryID,
		arg.Action,
		arg.ActorUserID,
		arg.Object,
		arg.From,
		arg.To,
		arg.PageOffset,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditEventsRow
	for rows.Next() {
		var i ListAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorUserID,
			&i.ActorUsername,
			&i.Action,
			&i.Object,
			&i.RepositoryID,
			&i.Target,
			&i.Detail,
			&i.SourceUrl,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAuditEvent = `-- name: RecordAuditEvent :exec
INSERT INTO okt_system.permission_audit
    (actor_user_id, actor_username, action, object, repository_id, target, detail, source_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type RecordAuditEventParams struct {
	ActorUserID   pgtype.UUID `json:"actor_user_id"`
	ActorUsername string      `json:"actor_username"`
	Action        string      `json:"action"`
	Object        string      `json:"object"`
	RepositoryID  pgtype.UUID `json:"repository_id"`
	Target        *string     `json:"target"`
	Detail        []byte      `json:"detail"`
	SourceUrl     *string     `json:"source_url"`
}

func (q *Queries) RecordAuditEvent(ctx context.Context, arg RecordAuditEventParams) error {
	_, err := q.db.Exec(ctx, recordAuditEvent,
		arg.ActorUserID,
		arg.ActorUsername,
		arg.Action,
		arg.Object,
		arg.RepositoryID,
		arg.Target,
		arg.Detail,
		arg.SourceUrl,
	)
	return err
}
