// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: concepts.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addConceptAlias = `-- name: AddConceptAlias :one
INSERT INTO okt_repository.concept_aliases (concept_id, alias_text)
VALUES ($1, $2)
ON CONFLICT (concept_id, lower(alias_text)) DO NOTHING
RETURNING id, concept_id, alias_text, created_at
`

type AddConceptAliasParams struct {
	ConceptID pgtype.UUID `json:"concept_id"`
	AliasText string      `json:"alias_text"`
}

// Idempotent: re-adding the same alias (e.g. a seed alias from a
// second fact that extracts the same concept) doesn't fail. The
// caller uses :one so a conflict is surfaced as pgx.ErrNoRows,
// which the worker treats as "already present, skip". The conflict
// target matches the uq_concept_aliases_concept_text unique index
// on (concept_id, lower(alias_text)).
func (q *Queries) AddConceptAlias(ctx context.Context, arg AddConceptAliasParams) (OktRepositoryConceptAlias, error) {
	row := q.db.QueryRow(ctx, addConceptAlias, arg.ConceptID, arg.AliasText)
	var i OktRepositoryConceptAlias
	err := row.Scan(
		&i.ID,
		&i.ConceptID,
		&i.AliasText,
		&i.CreatedAt,
	)
	return i, err
}

const addFactCandidate = `-- name: AddFactCandidate :one
INSERT INTO okt_repository.fact_candidates (fact_id, candidate_id)
VALUES ($1, $2)
ON CONFLICT (fact_id, candidate_id) DO NOTHING
RETURNING fact_id, candidate_id, first_seen_at
`

type AddFactCandidateParams struct {
	FactID      pgtype.UUID `json:"fact_id"`
	CandidateID pgtype.UUID `json:"candidate_id"`
}

// Link a fact to an unresolved candidate. Idempotent via the PK.
func (q *Queries) AddFactCandidate(ctx context.Context, arg AddFactCandidateParams) (OktRepositoryFactCandidate, error) {
	row := q.db.QueryRow(ctx, addFactCandidate, arg.FactID, arg.CandidateID)
	var i OktRepositoryFactCandidate
	err := row.Scan(&i.FactID, &i.CandidateID, &i.FirstSeenAt)
	return i, err
}

const addFactConcept = `-- name: AddFactConcept :one
INSERT INTO okt_repository.fact_concepts (fact_id, concept_id, promptset_hash)
VALUES ($1, $2, $3)
ON CONFLICT (fact_id, concept_id) DO NOTHING
RETURNING fact_id, concept_id, first_seen_at, promptset_hash
`

type AddFactConceptParams struct {
	FactID        pgtype.UUID `json:"fact_id"`
	ConceptID     pgtype.UUID `json:"concept_id"`
	PromptsetHash *string     `json:"promptset_hash"`
}

// Idempotent junction link. ON CONFLICT DO NOTHING so a re-extract
// pass that re-links the same (fact, concept) pair is a no-op.
// promptset_hash tags the link with the philosophy that produced
// the fact+concept pair so the junction stays queryable by
// philosophy (a fact and a concept derived under different
// promptsets must not be joined by a query that filters by hash).
func (q *Queries) AddFactConcept(ctx context.Context, arg AddFactConceptParams) (OktRepositoryFactConcept, error) {
	row := q.db.QueryRow(ctx, addFactConcept, arg.FactID, arg.ConceptID, arg.PromptsetHash)
	var i OktRepositoryFactConcept
	err := row.Scan(
		&i.FactID,
		&i.ConceptID,
		&i.FirstSeenAt,
		&i.PromptsetHash,
	)
	return i, err
}

const countAliasesSinceRefinement = `-- name: CountAliasesSinceRefinement :one
SELECT COUNT(*) FROM okt_repository.concept_aliases
WHERE concept_id = $1
  AND $2::timestamptz IS NOT NULL
  AND created_at > $2
`

type CountAliasesSinceRefinementParams struct {
	ConceptID pgtype.UUID        `json:"concept_id"`
	RefinedAt pgtype.Timestamptz `json:"refined_at"`
}

// Count aliases added since the last refinement. Used by the
// pruning gate: re-prune only when >= X new aliases have
// accumulated since aliases_refined_at.
func (q *Queries) CountAliasesSinceRefinement(ctx context.Context, arg CountAliasesSinceRefinementParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAliasesSinceRefinement, arg.ConceptID, arg.RefinedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countConceptRelationsByConceptName = `-- name: CountConceptRelationsByConceptName :one
SELECT COUNT(*) FROM (
    SELECT cr.name_b AS other_name
    FROM okt_repository.concept_relations cr
    WHERE cr.repository_id = $1 AND cr.name_a = lower($2)
    UNION
    SELECT cr.name_a AS other_name
    FROM okt_repository.concept_relations cr
    WHERE cr.repository_id = $1 AND cr.name_b = lower($2)
) r
`

type CountConceptRelationsByConceptNameParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Lower        string      `json:"lower"`
}

// Companion count for ListConceptRelationsByConceptName: the number of
// distinct related names for the given concept group, regardless of
// which column of the matview the pair sits in. Pure index count on
// the matview (no join to concepts), so it's cheap even for a concept
// with thousands of relations.
func (q *Queries) CountConceptRelationsByConceptName(ctx context.Context, arg CountConceptRelationsByConceptNameParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConceptRelationsByConceptName, arg.RepositoryID, arg.Lower)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countConceptsByContext = `-- name: CountConceptsByContext :one
SELECT COUNT(*) FROM okt_repository.concepts
WHERE repository_id = $1 AND lower(context) = lower($2)
`

type CountConceptsByContextParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Context      string      `json:"context"`
}

// The settings DELETE endpoint uses this to refuse deleting a
// context that still has concepts (the admin must migrate first).
func (q *Queries) CountConceptsByContext(ctx context.Context, arg CountConceptsByContextParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConceptsByContext, arg.RepositoryID, arg.Context)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countConceptsByRepo = `-- name: CountConceptsByRepo :one
SELECT COUNT(*) FROM okt_repository.concepts WHERE repository_id = $1
`

func (q *Queries) CountConceptsByRepo(ctx context.Context, repositoryID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countConceptsByRepo, repositoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFactsByConcept = `-- name: CountFactsByConcept :one
SELECT COUNT(*) FROM okt_repository.fact_concepts fc
JOIN okt_repository.facts f ON f.id = fc.fact_id
WHERE fc.concept_id = $1
  AND ($2::text = '' OR f.search_tsv @@ websearch_to_tsquery('english', $2))
`

type CountFactsByConceptParams struct {
	ConceptID pgtype.UUID `json:"concept_id"`
	Column2   string      `json:"column_2"`
}

// Companion count for ListFactsByConcept. Same concept_id and
// search predicates, minus the ORDER BY / LIMIT / OFFSET, so the
// API envelope can report `total` without a window function.
func (q *Queries) CountFactsByConcept(ctx context.Context, arg CountFactsByConceptParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFactsByConcept, arg.ConceptID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupedConceptsByRepo = `-- name: CountGroupedConceptsByRepo :one
SELECT COUNT(DISTINCT lower(c.canonical_name))
FROM okt_repository.concepts c
WHERE c.repository_id = $1
  AND ($2::text = '' OR lower(c.canonical_name) LIKE '%' || lower($2::text) || '%')
`

type CountGroupedConceptsByRepoParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Q            string      `json:"q"`
}

// Number of distinct canonical-name groups in a repo (one entry
// per lower(canonical_name)). Optional @q filters by canonical_name
// substring (case-insensitive), mirroring ListGroupedConceptsByRepo.
func (q *Queries) CountGroupedConceptsByRepo(ctx context.Context, arg CountGroupedConceptsByRepoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupedConceptsByRepo, arg.RepositoryID, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupedInvestigationConcepts = `-- name: CountGroupedInvestigationConcepts :one
SELECT COUNT(DISTINCT lower(c.canonical_name))
FROM okt_repository.concepts c
JOIN okt_repository.fact_concepts fcon ON fcon.concept_id = c.id
JOIN okt_repository.fact_sources fs ON fs.fact_id = fcon.fact_id
JOIN okt_repository.investigation_sources is_join ON is_join.source_id = fs.source_id
WHERE is_join.investigation_id = $1
`

// Number of distinct canonical-name groups reachable from an
// investigation's sources. Mirrors CountGroupedConceptsByRepo but
// scoped via the investigation_sources join.
func (q *Queries) CountGroupedInvestigationConcepts(ctx context.Context, investigationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupedInvestigationConcepts, investigationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInvestigationConcepts = `-- name: CountInvestigationConcepts :one
SELECT COUNT(DISTINCT c.id)
FROM okt_repository.concepts c
JOIN okt_repository.fact_concepts fcon ON fcon.concept_id = c.id
JOIN okt_repository.fact_sources fs ON fs.fact_id = fcon.fact_id
JOIN okt_repository.investigation_sources is_join ON is_join.source_id = fs.source_id
WHERE is_join.investigation_id = $1
`

// Companion count for ListInvestigationConcepts. Counts DISTINCT
// concepts reachable from the investigation's sources.
func (q *Queries) CountInvestigationConcepts(ctx context.Context, investigationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInvestigationConcepts, investigationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCandidate = `-- name: CreateCandidate :one
INSERT INTO okt_repository.concept_candidates (repository_id, concept_text, context, seed_aliases)
VALUES ($1, $2, $3, $4)
ON CONFLICT (repository_id, lower(concept_text), lower(context)) DO NOTHING
RETURNING id, repository_id, concept_text, context, seed_aliases, resolved_concept_id, resolved_at, created_at
`

type CreateCandidateParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	ConceptText  string      `json:"concept_text"`
	Context      string      `json:"context"`
	SeedAliases  []string    `json:"seed_aliases"`
}

// Insert a concept candidate (routing cache entry + work queue
// for refine_concepts). ON CONFLICT DO NOTHING so the same
// (concept_text, context) from multiple facts coalesces into one
// candidate row; the caller re-fetches by the unique key when it
// needs the id of an existing unresolved candidate.
func (q *Queries) CreateCandidate(ctx context.Context, arg CreateCandidateParams) (OktRepositoryConceptCandidate, error) {
	row := q.db.QueryRow(ctx, createCandidate,
		arg.RepositoryID,
		arg.ConceptText,
		arg.Context,
		arg.SeedAliases,
	)
	var i OktRepositoryConceptCandidate
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.ConceptText,
		&i.Context,
		&i.SeedAliases,
		&i.ResolvedConceptID,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createConcept = `-- name: CreateConcept :one

INSERT INTO okt_repository.concepts (repository_id, canonical_name, context, description, promptset_hash)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (repository_id, lower(canonical_name), lower(context)) DO NOTHING
RETURNING id, repository_id, canonical_name, context, description, embedded_at, embedded_model, created_at, summarizing_at, aliases_refined_at, promptset_hash
`

type CreateConceptParams struct {
	RepositoryID  pgtype.UUID `json:"repository_id"`
	CanonicalName string      `json:"canonical_name"`
	Context       string      `json:"context"`
	Description   *string     `json:"description"`
	PromptsetHash *string     `json:"promptset_hash"`
}

// concepts.sql — concept extraction Phase 1 queries.
//
// A concept is a repo-scoped, canonical-named entity assigned a
// context (an L3 ontology class label). Concepts are produced by
// the extract_concepts worker over a repo's stable facts. The
// fact_concepts junction is the end goal: querying a concept returns
// every fact linked to it.
// ON CONFLICT DO NOTHING so a racing extract_concepts pass that
// inserts the same (repository_id, canonical_name, context) twice
// doesn't fail; the caller re-queries by the unique key when it
// needs the id of the survivor. The conflict target matches the
// uq_concepts_repo_name_context unique index on
// (repository_id, lower(canonical_name), lower(context)).
// promptset_hash tags the concept with the philosophy that produced
// it so downstream queries (synthesis, registry pull) can filter to
// a single promptset and decompositions from different promptsets do
// not mix.
func (q *Queries) CreateConcept(ctx context.Context, arg CreateConceptParams) (OktRepositoryConcept, error) {
	row := q.db.QueryRow(ctx, createConcept,
		arg.RepositoryID,
		arg.CanonicalName,
		arg.Context,
		arg.Description,
		arg.PromptsetHash,
	)
	var i OktRepositoryConcept
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.CanonicalName,
		&i.Context,
		&i.Description,
		&i.EmbeddedAt,
		&i.EmbeddedModel,
		&i.CreatedAt,
		&i.SummarizingAt,
		&i.AliasesRefinedAt,
		&i.PromptsetHash,
	)
	return i, err
}

const deleteCandidate = `-- name: DeleteCandidate :exec
DELETE FROM okt_repository.concept_candidates
WHERE id = $1
`

// Delete a concept_candidate row (and its fact_candidates links via
// cascade). Used by refine_concepts after per-fact routing when all
// of a candidate's facts have been routed to real concepts and none
// were deferred (a deferred fact stays on the candidate, so the
// candidate is kept unresolved for the next pass). Distinct from
// ResolveCandidate, which marks the candidate as a resolved cache
// entry (resolved_concept_id) for single-target merges.
func (q *Queries) DeleteCandidate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCandidate, id)
	return err
}

const deleteConceptAliasByText = `-- name: DeleteConceptAliasByText :exec
DELETE FROM okt_repository.concept_aliases
WHERE concept_id = $1
  AND lower(alias_text) = lower($2)
`

type DeleteConceptAliasByTextParams struct {
	ConceptID pgtype.UUID `json:"concept_id"`
	AliasText string      `json:"alias_text"`
}

// Prune a specific alias from a concept (case-insensitive). Used
// by refine_concepts to apply aliases_to_prune from the LLM.
func (q *Queries) DeleteConceptAliasByText(ctx context.Context, arg DeleteConceptAliasByTextParams) error {
	_, err := q.db.Exec(ctx, deleteConceptAliasByText, arg.ConceptID, arg.AliasText)
	return err
}

const deleteConceptByID = `-- name: DeleteConceptByID :exec
DELETE FROM okt_repository.concepts WHERE id = $1
`

func (q *Queries) DeleteConceptByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConceptByID, id)
	return err
}

const deleteFactCandidate = `-- name: DeleteFactCandidate :exec
DELETE FROM okt_repository.fact_candidates
WHERE fact_id = $1 AND candidate_id = $2
`

type DeleteFactCandidateParams struct {
	FactID      pgtype.UUID `json:"fact_id"`
	CandidateID pgtype.UUID `json:"candidate_id"`
}

// Delete a single fact_candidates row (one fact off a candidate).
// Used by refine_concepts' per-fact routing branch: when an alias
// matches multiple concepts, each fact is routed individually to
// its cosine-winning concept and removed from the candidate, while
// deferred facts (no usable vector) stay on the candidate.
func (q *Queries) DeleteFactCandidate(ctx context.Context, arg DeleteFactCandidateParams) error {
	_, err := q.db.Exec(ctx, deleteFactCandidate, arg.FactID, arg.CandidateID)
	return err
}

const deleteFactCandidatesByCandidate = `-- name: DeleteFactCandidatesByCandidate :exec
DELETE FROM okt_repository.fact_candidates
WHERE candidate_id = $1
`

// Clear fact_candidates rows after resolution (the candidate row
// stays as a cache entry; only its fact links are moved to
// fact_concepts).
func (q *Queries) DeleteFactCandidatesByCandidate(ctx context.Context, candidateID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFactCandidatesByCandidate, candidateID)
	return err
}

const findConceptByAlias = `-- name: FindConceptByAlias :one
SELECT c.id, c.repository_id, c.canonical_name, c.context, c.description, c.embedded_at, c.embedded_model, c.created_at, c.summarizing_at, c.aliases_refined_at, c.promptset_hash
FROM okt_repository.concepts c
WHERE c.repository_id = $1
  AND lower(c.context) = lower($2)
  AND (
      lower(c.canonical_name) = lower($3)
      OR EXISTS (
          SELECT 1 FROM okt_repository.concept_aliases a
          WHERE a.concept_id = c.id AND lower(a.alias_text) = lower($3)
      )
  )
LIMIT 1
`

type FindConceptByAliasParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Context      string      `json:"context"`
	Name         string      `json:"name"`
}

// Text-search match scoped by (repository_id, context): matches
// either a concept's canonical_name OR any of its aliases (both
// case-insensitive). The context is matched case-insensitively too
// so a context drift ("Politician" vs "politician") still resolves
// to the same concept. LIMIT 1 so the first match wins; the caller
// links the fact to it.
//
// NOTE: callers that need to disambiguate an alias shared by
// multiple concepts (e.g. "N" on both Nitrogen and Neutron) should
// use FindConceptsByAlias (:many) and apply an embedding-distance
// tie-break per fact. This :one query returns an arbitrary first
// row on a shared alias and is only safe when the caller does not
// care about ambiguity (canonical-name-only routing, or a context
// where aliases are known to be unique).
func (q *Queries) FindConceptByAlias(ctx context.Context, arg FindConceptByAliasParams) (OktRepositoryConcept, error) {
	row := q.db.QueryRow(ctx, findConceptByAlias, arg.RepositoryID, arg.Context, arg.Name)
	var i OktRepositoryConcept
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.CanonicalName,
		&i.Context,
		&i.Description,
		&i.EmbeddedAt,
		&i.EmbeddedModel,
		&i.CreatedAt,
		&i.SummarizingAt,
		&i.AliasesRefinedAt,
		&i.PromptsetHash,
	)
	return i, err
}

const findConceptByCanonical = `-- name: FindConceptByCanonical :one
SELECT id, repository_id, canonical_name, context, description, embedded_at, embedded_model, created_at, summarizing_at, aliases_refined_at, promptset_hash FROM okt_repository.concepts
WHERE repository_id = $1
  AND lower(context) = lower($2)
  AND lower(canonical_name) = lower($3)
LIMIT 1
`

type FindConceptByCanonicalParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Context      string      `json:"context"`
	Name         string      `json:"name"`
}

// Same-context canonical name match (case-insensitive). Used by
// refine_concepts to route a candidate to an existing concept by
// its canonical name. Mirrors FindConceptByAlias but matches only
// canonical_name, not aliases.
func (q *Queries) FindConceptByCanonical(ctx context.Context, arg FindConceptByCanonicalParams) (OktRepositoryConcept, error) {
	row := q.db.QueryRow(ctx, findConceptByCanonical, arg.RepositoryID, arg.Context, arg.Name)
	var i OktRepositoryConcept
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.CanonicalName,
		&i.Context,
		&i.Description,
		&i.EmbeddedAt,
		&i.EmbeddedModel,
		&i.CreatedAt,
		&i.SummarizingAt,
		&i.AliasesRefinedAt,
		&i.PromptsetHash,
	)
	return i, err
}

const findConceptsByAlias = `-- name: FindConceptsByAlias :many
SELECT c.id, c.repository_id, c.canonical_name, c.context, c.description, c.embedded_at, c.embedded_model, c.created_at, c.summarizing_at, c.aliases_refined_at, c.promptset_hash
FROM okt_repository.concepts c
WHERE c.repository_id = $1
  AND lower(c.context) = lower($2)
  AND (
      lower(c.canonical_name) = lower($3)
      OR EXISTS (
          SELECT 1 FROM okt_repository.concept_aliases a
          WHERE a.concept_id = c.id AND lower(a.alias_text) = lower($3)
      )
  )
ORDER BY c.created_at, c.id
`

type FindConceptsByAliasParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Context      string      `json:"context"`
	Name         string      `json:"name"`
}

// Same predicate as FindConceptByAlias but returns ALL matches
// (no LIMIT 1), ordered deterministically by created_at, id so the
// fallback when no embedding tie-break is possible is stable. The
// refine_concepts worker uses this to detect alias ambiguity: when
// more than one concept shares an alias, it routes each of the
// candidate's facts individually to the concept whose Qdrant vector
// is cosine-closest to that fact's vector (see
// internal/concepts.ResolveAliasMatchForFact). 0 or 1 match -> no
// ambiguity, behave as the legacy single-target merge.
func (q *Queries) FindConceptsByAlias(ctx context.Context, arg FindConceptsByAliasParams) ([]OktRepositoryConcept, error) {
	rows, err := q.db.Query(ctx, findConceptsByAlias, arg.RepositoryID, arg.Context, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktRepositoryConcept
	for rows.Next() {
		var i OktRepositoryConcept
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.CanonicalName,
			&i.Context,
			&i.Description,
			&i.EmbeddedAt,
			&i.EmbeddedModel,
			&i.CreatedAt,
			&i.SummarizingAt,
			&i.AliasesRefinedAt,
			&i.PromptsetHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findResolvedCandidate = `-- name: FindResolvedCandidate :one
SELECT id, repository_id, concept_text, context, seed_aliases, resolved_concept_id, resolved_at, created_at FROM okt_repository.concept_candidates
WHERE repository_id = $1
  AND lower(concept_text) = lower($2)
  AND lower(context) = lower($3)
  AND resolved_concept_id IS NOT NULL
LIMIT 1
`

type FindResolvedCandidateParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	ConceptText  string      `json:"concept_text"`
	Context      string      `json:"context"`
}

// Cache lookup: a previously-resolved candidate for this
// (concept_text, context). Returns the resolved_concept_id so
// extract_concepts can link the fact directly without refinement.
func (q *Queries) FindResolvedCandidate(ctx context.Context, arg FindResolvedCandidateParams) (OktRepositoryConceptCandidate, error) {
	row := q.db.QueryRow(ctx, findResolvedCandidate, arg.RepositoryID, arg.ConceptText, arg.Context)
	var i OktRepositoryConceptCandidate
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.ConceptText,
		&i.Context,
		&i.SeedAliases,
		&i.ResolvedConceptID,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findUnresolvedCandidate = `-- name: FindUnresolvedCandidate :one
SELECT id, repository_id, concept_text, context, seed_aliases, resolved_concept_id, resolved_at, created_at FROM okt_repository.concept_candidates
WHERE repository_id = $1
  AND lower(concept_text) = lower($2)
  AND lower(context) = lower($3)
  AND resolved_concept_id IS NULL
LIMIT 1
`

type FindUnresolvedCandidateParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	ConceptText  string      `json:"concept_text"`
	Context      string      `json:"context"`
}

func (q *Queries) FindUnresolvedCandidate(ctx context.Context, arg FindUnresolvedCandidateParams) (OktRepositoryConceptCandidate, error) {
	row := q.db.QueryRow(ctx, findUnresolvedCandidate, arg.RepositoryID, arg.ConceptText, arg.Context)
	var i OktRepositoryConceptCandidate
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.ConceptText,
		&i.Context,
		&i.SeedAliases,
		&i.ResolvedConceptID,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getConceptByID = `-- name: GetConceptByID :one
SELECT id, repository_id, canonical_name, context, description, embedded_at, embedded_model, created_at, summarizing_at, aliases_refined_at, promptset_hash FROM okt_repository.concepts WHERE id = $1
`

func (q *Queries) GetConceptByID(ctx context.Context, id pgtype.UUID) (OktRepositoryConcept, error) {
	row := q.db.QueryRow(ctx, getConceptByID, id)
	var i OktRepositoryConcept
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.CanonicalName,
		&i.Context,
		&i.Description,
		&i.EmbeddedAt,
		&i.EmbeddedModel,
		&i.CreatedAt,
		&i.SummarizingAt,
		&i.AliasesRefinedAt,
		&i.PromptsetHash,
	)
	return i, err
}

const getConceptByNameContext = `-- name: GetConceptByNameContext :one
SELECT id, repository_id, canonical_name, context, description, embedded_at, embedded_model, created_at, summarizing_at, aliases_refined_at, promptset_hash FROM okt_repository.concepts
WHERE repository_id = $1
  AND lower(canonical_name) = lower($2)
  AND lower(context) = lower($3)
LIMIT 1
`

type GetConceptByNameContextParams struct {
	RepositoryID  pgtype.UUID `json:"repository_id"`
	CanonicalName string      `json:"canonical_name"`
	Context       string      `json:"context"`
}

// Lookup a concept by (repository_id, canonical_name, context),
// case-insensitively on both name and context. Used by the
// migrate_context worker to decide whether a target (name,
// new_context) already exists (merge path) or whether a plain
// UPDATE is safe (reassign path). Matches the
// uq_concepts_repo_name_context unique index target.
func (q *Queries) GetConceptByNameContext(ctx context.Context, arg GetConceptByNameContextParams) (OktRepositoryConcept, error) {
	row := q.db.QueryRow(ctx, getConceptByNameContext, arg.RepositoryID, arg.CanonicalName, arg.Context)
	var i OktRepositoryConcept
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.CanonicalName,
		&i.Context,
		&i.Description,
		&i.EmbeddedAt,
		&i.EmbeddedModel,
		&i.CreatedAt,
		&i.SummarizingAt,
		&i.AliasesRefinedAt,
		&i.PromptsetHash,
	)
	return i, err
}

const getConceptCandidateByID = `-- name: GetConceptCandidateByID :one
SELECT id, repository_id, concept_text, context, seed_aliases, resolved_concept_id, resolved_at, created_at FROM okt_repository.concept_candidates WHERE id = $1
`

func (q *Queries) GetConceptCandidateByID(ctx context.Context, id pgtype.UUID) (OktRepositoryConceptCandidate, error) {
	row := q.db.QueryRow(ctx, getConceptCandidateByID, id)
	var i OktRepositoryConceptCandidate
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.ConceptText,
		&i.Context,
		&i.SeedAliases,
		&i.ResolvedConceptID,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFactConceptSkip = `-- name: GetFactConceptSkip :one
SELECT fact_id, last_error, skipped_at FROM okt_repository.fact_concept_skips WHERE fact_id = $1
`

func (q *Queries) GetFactConceptSkip(ctx context.Context, factID pgtype.UUID) (OktRepositoryFactConceptSkip, error) {
	row := q.db.QueryRow(ctx, getFactConceptSkip, factID)
	var i OktRepositoryFactConceptSkip
	err := row.Scan(&i.FactID, &i.LastError, &i.SkippedAt)
	return i, err
}

const listConceptAliasesByConcept = `-- name: ListConceptAliasesByConcept :many
SELECT id, concept_id, alias_text, created_at FROM okt_repository.concept_aliases WHERE concept_id = $1 ORDER BY alias_text
`

func (q *Queries) ListConceptAliasesByConcept(ctx context.Context, conceptID pgtype.UUID) ([]OktRepositoryConceptAlias, error) {
	rows, err := q.db.Query(ctx, listConceptAliasesByConcept, conceptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktRepositoryConceptAlias
	for rows.Next() {
		var i OktRepositoryConceptAlias
		if err := rows.Scan(
			&i.ID,
			&i.ConceptID,
			&i.AliasText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConceptAliasesByConceptIDs = `-- name: ListConceptAliasesByConceptIDs :many
SELECT ca.id,
       ca.concept_id,
       ca.alias_text,
       ca.created_at
FROM okt_repository.concept_aliases ca
WHERE ca.concept_id = ANY($1::uuid[])
ORDER BY ca.concept_id, ca.alias_text
`

// Aliases for a set of concept_ids in one query, returned
// un-grouped (the caller groups by concept_id in Go). Used by the
// detail endpoint to fetch every context's aliases in a single
// round-trip instead of N per-context ListConceptAliasesByConcept
// calls. Ordered by concept_id, alias_text so the Go grouping is
// deterministic. ANY() on an empty array matches nothing, which is
// correct (a group with no contexts returns no aliases).
func (q *Queries) ListConceptAliasesByConceptIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]OktRepositoryConceptAlias, error) {
	rows, err := q.db.Query(ctx, listConceptAliasesByConceptIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktRepositoryConceptAlias
	for rows.Next() {
		var i OktRepositoryConceptAlias
		if err := rows.Scan(
			&i.ID,
			&i.ConceptID,
			&i.AliasText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConceptRelationDetailsByConceptName = `-- name: ListConceptRelationDetailsByConceptName :many
SELECT ca.context,
       COUNT(DISTINCT fc1.fact_id) AS shared_fact_count,
       ARRAY_AGG(DISTINCT fc1.fact_id) AS fact_ids
FROM okt_repository.fact_concepts fc1
JOIN okt_repository.concepts ca ON ca.id = fc1.concept_id
JOIN okt_repository.fact_concepts fc2 ON fc2.fact_id = fc1.fact_id
JOIN okt_repository.concepts cb ON cb.id = fc2.concept_id
WHERE ca.repository_id = $1
  AND cb.repository_id = $1
  AND lower(ca.canonical_name) = lower($2)
  AND lower(cb.canonical_name) = lower($3)
GROUP BY ca.context
ORDER BY shared_fact_count DESC, ca.context ASC
`

type ListConceptRelationDetailsByConceptNameParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Lower        string      `json:"lower"`
	Lower_2      string      `json:"lower_2"`
}

type ListConceptRelationDetailsByConceptNameRow struct {
	Context         string      `json:"context"`
	SharedFactCount int64       `json:"shared_fact_count"`
	FactIds         interface{} `json:"fact_ids"`
}

// Relation details for a specific pair of concept names (A, B): one
// row per CONTEXT of A, with shared_fact_count aggregated across all
// of B's contexts. This is the per-context breakdown the user wanted
// for drilling into how two concepts relate (e.g. Trump-as-Politician
// shares N facts with X, aggregated across every context of X).
//
// Unlike the list/count queries (which read the matview), this is a
// LIVE query against fact_concepts. Rationale: the details endpoint
// is on-demand for a specific pair (low volume) and benefits from
// freshness (a just-extracted shared fact shows up immediately without
// waiting for the matview refresh). The cost is bounded by A's fact
// count × concepts-per-fact and the pair filter keeps the working set
// small. fact_ids is the array of shared fact_ids (one row per shared
// fact) so the UI can offer a "view shared facts" drill-down; it's
// gathered via array_agg and capped by A's context fact count, which
// is naturally bounded.
func (q *Queries) ListConceptRelationDetailsByConceptName(ctx context.Context, arg ListConceptRelationDetailsByConceptNameParams) ([]ListConceptRelationDetailsByConceptNameRow, error) {
	rows, err := q.db.Query(ctx, listConceptRelationDetailsByConceptName, arg.RepositoryID, arg.Lower, arg.Lower_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConceptRelationDetailsByConceptNameRow
	for rows.Next() {
		var i ListConceptRelationDetailsByConceptNameRow
		if err := rows.Scan(&i.Context, &i.SharedFactCount, &i.FactIds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConceptRelationsByConceptName = `-- name: ListConceptRelationsByConceptName :many
SELECT other_name,
       MAX(c.canonical_name) AS canonical_name,
       MIN(c.id::text) AS concept_id,
       shared_fact_count
FROM (
    SELECT cr.name_b AS other_name, cr.shared_fact_count AS shared_fact_count
    FROM okt_repository.concept_relations cr
    WHERE cr.repository_id = $1 AND cr.name_a = lower($2)
    UNION ALL
    SELECT cr.name_a AS other_name, cr.shared_fact_count AS shared_fact_count
    FROM okt_repository.concept_relations cr
    WHERE cr.repository_id = $1 AND cr.name_b = lower($2)
) r
JOIN okt_repository.concepts c
  ON c.repository_id = $1 AND lower(c.canonical_name) = r.other_name
GROUP BY other_name, shared_fact_count
ORDER BY shared_fact_count DESC, other_name ASC
LIMIT $3 OFFSET $4
`

type ListConceptRelationsByConceptNameParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Lower        string      `json:"lower"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

type ListConceptRelationsByConceptNameRow struct {
	OtherName       string      `json:"other_name"`
	CanonicalName   interface{} `json:"canonical_name"`
	ConceptID       interface{} `json:"concept_id"`
	SharedFactCount int64       `json:"shared_fact_count"`
}

// Paginated list of concepts related to the concept group identified
// by its lower(canonical_name), ordered by relation strength
// (shared_fact_count DESC) then by the related name ASC for stable
// pagination. A "relation" is the set of facts linked to both concept
// groups; shared_fact_count is the distinct count of those shared
// facts (deduped per fact, not per source — a fact confirmed by N
// sources counts once).
//
// Served from the okt_repository.concept_relations materialized view,
// which stores ordered pairs (lower(name_a) < lower(name_b)) with
// self-pairs excluded. A query for a concept's name therefore matches
// either column and projects the OTHER name as `other_name`. The view
// is refreshed concurrently by the refresh_concept_relations task
// (enqueued at the end of each extract_concepts batch and on a
// periodic schedule), so reads are a single index range scan immune
// to parallel load.
//
// canonical_name is joined from concepts (the related name groups one
// or more per-context rows; MAX(canonical_name) picks a stable
// representative — casing may vary across sibling rows, e.g. "Trump"
// vs "trump", so we pick the lexicographic max deterministically
// rather than relying on every sibling sharing the exact casing).
// MIN(c.id) picks a representative concept_id for the related group
// so the UI can build a detail-page link without a second lookup.
// A repo with no relations for the name returns no rows.
func (q *Queries) ListConceptRelationsByConceptName(ctx context.Context, arg ListConceptRelationsByConceptNameParams) ([]ListConceptRelationsByConceptNameRow, error) {
	rows, err := q.db.Query(ctx, listConceptRelationsByConceptName,
		arg.RepositoryID,
		arg.Lower,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConceptRelationsByConceptNameRow
	for rows.Next() {
		var i ListConceptRelationsByConceptNameRow
		if err := rows.Scan(
			&i.OtherName,
			&i.CanonicalName,
			&i.ConceptID,
			&i.SharedFactCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConceptsByContext = `-- name: ListConceptsByContext :many
SELECT id, repository_id, canonical_name, context, description, embedded_at, embedded_model, created_at, summarizing_at, aliases_refined_at, promptset_hash FROM okt_repository.concepts
WHERE repository_id = $1 AND lower(context) = lower($2)
ORDER BY id
`

type ListConceptsByContextParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Context      string      `json:"context"`
}

// Every concept row in a repo assigned to a given context (case-
// insensitive). The migrate_context worker iterates these to merge
// or reassign each into the target context. Ordered by id for a
// stable merge order (deterministic survivor selection).
func (q *Queries) ListConceptsByContext(ctx context.Context, arg ListConceptsByContextParams) ([]OktRepositoryConcept, error) {
	rows, err := q.db.Query(ctx, listConceptsByContext, arg.RepositoryID, arg.Context)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktRepositoryConcept
	for rows.Next() {
		var i OktRepositoryConcept
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.CanonicalName,
			&i.Context,
			&i.Description,
			&i.EmbeddedAt,
			&i.EmbeddedModel,
			&i.CreatedAt,
			&i.SummarizingAt,
			&i.AliasesRefinedAt,
			&i.PromptsetHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConceptsByFact = `-- name: ListConceptsByFact :many
SELECT c.id, c.repository_id, c.canonical_name, c.context, c.description, c.embedded_at, c.embedded_model, c.created_at, c.summarizing_at, c.aliases_refined_at, c.promptset_hash
FROM okt_repository.fact_concepts fc
JOIN okt_repository.concepts c ON c.id = fc.concept_id
WHERE fc.fact_id = $1
ORDER BY c.canonical_name
`

// The inverse view: which concepts a fact links to. Used by the
// fact detail page to show the concept tags attached to a fact.
func (q *Queries) ListConceptsByFact(ctx context.Context, factID pgtype.UUID) ([]OktRepositoryConcept, error) {
	rows, err := q.db.Query(ctx, listConceptsByFact, factID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktRepositoryConcept
	for rows.Next() {
		var i OktRepositoryConcept
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.CanonicalName,
			&i.Context,
			&i.Description,
			&i.EmbeddedAt,
			&i.EmbeddedModel,
			&i.CreatedAt,
			&i.SummarizingAt,
			&i.AliasesRefinedAt,
			&i.PromptsetHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConceptsByRepo = `-- name: ListConceptsByRepo :many
SELECT c.id, c.repository_id, c.canonical_name, c.context, c.description, c.embedded_at, c.embedded_model, c.created_at, c.summarizing_at, c.aliases_refined_at, c.promptset_hash,
       (SELECT COUNT(*) FROM okt_repository.fact_concepts fc WHERE fc.concept_id = c.id) AS fact_count
FROM okt_repository.concepts c
WHERE c.repository_id = $1
ORDER BY fact_count DESC, c.canonical_name ASC
LIMIT $2 OFFSET $3
`

type ListConceptsByRepoParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

type ListConceptsByRepoRow struct {
	ID               pgtype.UUID        `json:"id"`
	RepositoryID     pgtype.UUID        `json:"repository_id"`
	CanonicalName    string             `json:"canonical_name"`
	Context          string             `json:"context"`
	Description      *string            `json:"description"`
	EmbeddedAt       pgtype.Timestamptz `json:"embedded_at"`
	EmbeddedModel    *string            `json:"embedded_model"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	SummarizingAt    pgtype.Timestamptz `json:"summarizing_at"`
	AliasesRefinedAt pgtype.Timestamptz `json:"aliases_refined_at"`
	PromptsetHash    *string            `json:"promptset_hash"`
	FactCount        int64              `json:"fact_count"`
}

// Paginated concept list with a computed fact_count so the UI can
// sort by "most linked" and the user sees the most relevant
// concepts first. The subquery is correlated but cheap: the
// fact_concepts PK index makes the count an index-only scan.
//
// NOTE: returns one row per (canonical_name, context) pair. The
// HTTP list endpoint groups these into one entry per canonical
// name via ListGroupedConceptsByRepo instead. This query is kept
// for backward compatibility and direct store use; the handler no
// longer calls it.
func (q *Queries) ListConceptsByRepo(ctx context.Context, arg ListConceptsByRepoParams) ([]ListConceptsByRepoRow, error) {
	rows, err := q.db.Query(ctx, listConceptsByRepo, arg.RepositoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConceptsByRepoRow
	for rows.Next() {
		var i ListConceptsByRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.CanonicalName,
			&i.Context,
			&i.Description,
			&i.EmbeddedAt,
			&i.EmbeddedModel,
			&i.CreatedAt,
			&i.SummarizingAt,
			&i.AliasesRefinedAt,
			&i.PromptsetHash,
			&i.FactCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConceptsByRepoName = `-- name: ListConceptsByRepoName :many
SELECT c.id,
       c.repository_id,
       c.canonical_name,
       c.context,
       c.description,
       c.embedded_at,
       c.embedded_model,
       c.created_at,
       (SELECT COUNT(*) FROM okt_repository.fact_concepts fc WHERE fc.concept_id = c.id) AS fact_count
FROM okt_repository.concepts c
WHERE c.repository_id = $1 AND lower(c.canonical_name) = lower($2)
ORDER BY fact_count DESC, c.context ASC
`

type ListConceptsByRepoNameParams struct {
	RepositoryID  pgtype.UUID `json:"repository_id"`
	CanonicalName string      `json:"canonical_name"`
}

type ListConceptsByRepoNameRow struct {
	ID            pgtype.UUID        `json:"id"`
	RepositoryID  pgtype.UUID        `json:"repository_id"`
	CanonicalName string             `json:"canonical_name"`
	Context       string             `json:"context"`
	Description   *string            `json:"description"`
	EmbeddedAt    pgtype.Timestamptz `json:"embedded_at"`
	EmbeddedModel *string            `json:"embedded_model"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	FactCount     int64              `json:"fact_count"`
}

// Group lookup by lower(canonical_name): the primary detail-endpoint
// path. The handler resolves a concept UUID to its canonical_name
// (via GetConceptByID), then calls this to fetch the whole group
// (every per-context row sharing the lower(canonical_name)) in one
// indexed equality lookup. Ordered by fact_count DESC so the first
// row is the highest-fact_count context (the group representative).
func (q *Queries) ListConceptsByRepoName(ctx context.Context, arg ListConceptsByRepoNameParams) ([]ListConceptsByRepoNameRow, error) {
	rows, err := q.db.Query(ctx, listConceptsByRepoName, arg.RepositoryID, arg.CanonicalName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConceptsByRepoNameRow
	for rows.Next() {
		var i ListConceptsByRepoNameRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.CanonicalName,
			&i.Context,
			&i.Description,
			&i.EmbeddedAt,
			&i.EmbeddedModel,
			&i.CreatedAt,
			&i.FactCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactConceptSkipsByRepo = `-- name: ListFactConceptSkipsByRepo :many
SELECT DISTINCT sk.fact_id, sk.last_error, sk.skipped_at
FROM okt_repository.fact_concept_skips sk
JOIN okt_repository.facts f ON f.id = sk.fact_id
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
JOIN okt_repository.sources s ON fs.source_id = s.id
WHERE s.repository_id = $1
ORDER BY sk.skipped_at DESC
`

// For the admin UI / diagnostics: which facts have been skipped
// for a given repo. facts does not carry repository_id, so we
// scope via fact_sources/sources (same shape as
// ListStableFactsForConceptExtraction). DISTINCT in case a fact
// has multiple source rows.
func (q *Queries) ListFactConceptSkipsByRepo(ctx context.Context, repositoryID pgtype.UUID) ([]OktRepositoryFactConceptSkip, error) {
	rows, err := q.db.Query(ctx, listFactConceptSkipsByRepo, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktRepositoryFactConceptSkip
	for rows.Next() {
		var i OktRepositoryFactConceptSkip
		if err := rows.Scan(&i.FactID, &i.LastError, &i.SkippedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactIDsByCandidate = `-- name: ListFactIDsByCandidate :many
SELECT fact_id
FROM okt_repository.fact_candidates
WHERE candidate_id = $1
ORDER BY first_seen_at
`

// The fact_ids linked to an unresolved concept_candidate via
// fact_candidates. Used by refine_concepts' per-fact routing branch
// to route each fact individually to its cosine-winning concept when
// an alias matches multiple concepts.
func (q *Queries) ListFactIDsByCandidate(ctx context.Context, candidateID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listFactIDsByCandidate, candidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var fact_id pgtype.UUID
		if err := rows.Scan(&fact_id); err != nil {
			return nil, err
		}
		items = append(items, fact_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactsByConcept = `-- name: ListFactsByConcept :many
SELECT f.id, f.text, f.status, f.embedded_at, f.embedded_model, f.created_at, f.search_tsv, f.image_url, f.fact_kind, f.promptset_hash, fc.first_seen_at
FROM okt_repository.fact_concepts fc
JOIN okt_repository.facts f ON f.id = fc.fact_id
WHERE fc.concept_id = $1
  AND ($2::text = '' OR f.search_tsv @@ websearch_to_tsquery('english', $2))
ORDER BY fc.first_seen_at
LIMIT $3 OFFSET $4
`

type ListFactsByConceptParams struct {
	ConceptID pgtype.UUID `json:"concept_id"`
	Column2   string      `json:"column_2"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListFactsByConceptRow struct {
	ID            pgtype.UUID        `json:"id"`
	Text          string             `json:"text"`
	Status        string             `json:"status"`
	EmbeddedAt    pgtype.Timestamptz `json:"embedded_at"`
	EmbeddedModel *string            `json:"embedded_model"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	SearchTsv     interface{}        `json:"search_tsv"`
	ImageUrl      *string            `json:"image_url"`
	FactKind      string             `json:"fact_kind"`
	PromptsetHash *string            `json:"promptset_hash"`
	FirstSeenAt   pgtype.Timestamptz `json:"first_seen_at"`
}

// The "query DNA → 200 facts" view. Paginated; the caller passes
// the concept_id (resolved by the caller from the route param).
// Ordered by first_seen_at so the oldest link is first (stable
// across pages). The optional search ($2) runs through
// websearch_to_tsquery against facts.search_tsv (covers facts.text);
// empty string = no filter. LIMIT $3 / OFFSET $4 apply on top.
func (q *Queries) ListFactsByConcept(ctx context.Context, arg ListFactsByConceptParams) ([]ListFactsByConceptRow, error) {
	rows, err := q.db.Query(ctx, listFactsByConcept,
		arg.ConceptID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFactsByConceptRow
	for rows.Next() {
		var i ListFactsByConceptRow
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Status,
			&i.EmbeddedAt,
			&i.EmbeddedModel,
			&i.CreatedAt,
			&i.SearchTsv,
			&i.ImageUrl,
			&i.FactKind,
			&i.PromptsetHash,
			&i.FirstSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupedConceptsByRepo = `-- name: ListGroupedConceptsByRepo :many
SELECT c.id,
       c.repository_id,
       c.canonical_name,
       c.context,
       c.description,
       c.embedded_at,
       c.embedded_model,
       c.created_at,
       (SELECT COUNT(*) FROM okt_repository.fact_concepts fc WHERE fc.concept_id = c.id) AS fact_count
FROM okt_repository.concepts c
WHERE c.repository_id = $1
  AND ($2::text = '' OR lower(c.canonical_name) LIKE '%' || lower($2::text) || '%')
ORDER BY fact_count DESC, c.canonical_name ASC
`

type ListGroupedConceptsByRepoParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Q            string      `json:"q"`
}

type ListGroupedConceptsByRepoRow struct {
	ID            pgtype.UUID        `json:"id"`
	RepositoryID  pgtype.UUID        `json:"repository_id"`
	CanonicalName string             `json:"canonical_name"`
	Context       string             `json:"context"`
	Description   *string            `json:"description"`
	EmbeddedAt    pgtype.Timestamptz `json:"embedded_at"`
	EmbeddedModel *string            `json:"embedded_model"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	FactCount     int64              `json:"fact_count"`
}

// All per-context concept rows for a repo, with a computed
// fact_count, intended to be grouped in Go by lower(canonical_name)
// so the API can present "one concept, many contexts". Returns the
// full set (no SQL-level pagination); the caller paginates the
// resulting groups in Go. Optional @q filters by canonical_name
// substring (case-insensitive). Ordered by fact_count DESC,
// canonical_name ASC so the in-Go group representative pick (first
// row seen for a name) is the highest-fact_count context — stable
// across re-runs. Grouping is by lower(canonical_name) in Go; the
// slug column was removed in migration 0030.
func (q *Queries) ListGroupedConceptsByRepo(ctx context.Context, arg ListGroupedConceptsByRepoParams) ([]ListGroupedConceptsByRepoRow, error) {
	rows, err := q.db.Query(ctx, listGroupedConceptsByRepo, arg.RepositoryID, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupedConceptsByRepoRow
	for rows.Next() {
		var i ListGroupedConceptsByRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.CanonicalName,
			&i.Context,
			&i.Description,
			&i.EmbeddedAt,
			&i.EmbeddedModel,
			&i.CreatedAt,
			&i.FactCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupedInvestigationConcepts = `-- name: ListGroupedInvestigationConcepts :many
SELECT DISTINCT c.id,
       c.repository_id,
       c.canonical_name,
       c.context,
       c.description,
       c.embedded_at,
       c.embedded_model,
       c.created_at,
       (SELECT COUNT(*) FROM okt_repository.fact_concepts fc WHERE fc.concept_id = c.id) AS fact_count
FROM okt_repository.concepts c
JOIN okt_repository.fact_concepts fcon ON fcon.concept_id = c.id
JOIN okt_repository.fact_sources fs ON fs.fact_id = fcon.fact_id
JOIN okt_repository.investigation_sources is_join ON is_join.source_id = fs.source_id
WHERE is_join.investigation_id = $1
ORDER BY fact_count DESC, c.canonical_name ASC
`

type ListGroupedInvestigationConceptsRow struct {
	ID            pgtype.UUID        `json:"id"`
	RepositoryID  pgtype.UUID        `json:"repository_id"`
	CanonicalName string             `json:"canonical_name"`
	Context       string             `json:"context"`
	Description   *string            `json:"description"`
	EmbeddedAt    pgtype.Timestamptz `json:"embedded_at"`
	EmbeddedModel *string            `json:"embedded_model"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	FactCount     int64              `json:"fact_count"`
}

// All per-context concept rows reachable from an investigation's
// sources, with computed fact_count, intended to be grouped in Go
// by lower(canonical_name). Returns the full set (no SQL-level
// pagination); the caller paginates the resulting groups in Go.
// Mirrors ListGroupedConceptsByRepo but scoped via
// fact_concepts → fact_sources → investigation_sources. fact_count
// is repo-wide (cross-confirmation still shows); the membership
// filter is only on which concepts appear. Ordered by fact_count
// DESC, canonical_name ASC so the in-Go group representative pick
// is the highest-fact_count context.
func (q *Queries) ListGroupedInvestigationConcepts(ctx context.Context, investigationID pgtype.UUID) ([]ListGroupedInvestigationConceptsRow, error) {
	rows, err := q.db.Query(ctx, listGroupedInvestigationConcepts, investigationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupedInvestigationConceptsRow
	for rows.Next() {
		var i ListGroupedInvestigationConceptsRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.CanonicalName,
			&i.Context,
			&i.Description,
			&i.EmbeddedAt,
			&i.EmbeddedModel,
			&i.CreatedAt,
			&i.FactCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestigationConcepts = `-- name: ListInvestigationConcepts :many
SELECT DISTINCT c.id, c.repository_id, c.canonical_name, c.context, c.description, c.embedded_at, c.embedded_model, c.created_at, c.summarizing_at, c.aliases_refined_at, c.promptset_hash,
        (SELECT COUNT(*) FROM okt_repository.fact_concepts fc WHERE fc.concept_id = c.id) AS fact_count
FROM okt_repository.concepts c
JOIN okt_repository.fact_concepts fcon ON fcon.concept_id = c.id
JOIN okt_repository.fact_sources fs ON fs.fact_id = fcon.fact_id
JOIN okt_repository.investigation_sources is_join ON is_join.source_id = fs.source_id
WHERE is_join.investigation_id = $1
ORDER BY fact_count DESC, c.canonical_name ASC
LIMIT $2 OFFSET $3
`

type ListInvestigationConceptsParams struct {
	InvestigationID pgtype.UUID `json:"investigation_id"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
}

type ListInvestigationConceptsRow struct {
	ID               pgtype.UUID        `json:"id"`
	RepositoryID     pgtype.UUID        `json:"repository_id"`
	CanonicalName    string             `json:"canonical_name"`
	Context          string             `json:"context"`
	Description      *string            `json:"description"`
	EmbeddedAt       pgtype.Timestamptz `json:"embedded_at"`
	EmbeddedModel    *string            `json:"embedded_model"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	SummarizingAt    pgtype.Timestamptz `json:"summarizing_at"`
	AliasesRefinedAt pgtype.Timestamptz `json:"aliases_refined_at"`
	PromptsetHash    *string            `json:"promptset_hash"`
	FactCount        int64              `json:"fact_count"`
}

// Investigation-scoped concept list. Concepts are reached via
// fact_concepts → fact_sources → investigation_sources, so only
// concepts derived from facts that came from the investigation's
// own sources are returned (a brand-new investigation with no
// sources returns nothing). fact_count is computed over ALL facts
// linked to the concept (repo-wide), mirroring ListConceptsByRepo
// so cross-confirmation still shows; the membership filter is only
// on which concepts appear, not on the count. Paginated, ordered by
// fact_count DESC then canonical_name ASC, mirroring the repo list.
//
// NOTE: returns one row per (canonical_name, context) pair. The
// HTTP investigation-concepts endpoint groups these by
// lower(canonical_name) via ListGroupedInvestigationConcepts
// instead. This query is kept for backward compatibility and direct
// store use; the handler no longer calls it.
func (q *Queries) ListInvestigationConcepts(ctx context.Context, arg ListInvestigationConceptsParams) ([]ListInvestigationConceptsRow, error) {
	rows, err := q.db.Query(ctx, listInvestigationConcepts, arg.InvestigationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvestigationConceptsRow
	for rows.Next() {
		var i ListInvestigationConceptsRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.CanonicalName,
			&i.Context,
			&i.Description,
			&i.EmbeddedAt,
			&i.EmbeddedModel,
			&i.CreatedAt,
			&i.SummarizingAt,
			&i.AliasesRefinedAt,
			&i.PromptsetHash,
			&i.FactCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewConceptsForEmbedding = `-- name: ListNewConceptsForEmbedding :many
SELECT id, canonical_name, context FROM okt_repository.concepts
WHERE repository_id = $1 AND embedded_at IS NULL
ORDER BY created_at
`

type ListNewConceptsForEmbeddingRow struct {
	ID            pgtype.UUID `json:"id"`
	CanonicalName string      `json:"canonical_name"`
	Context       string      `json:"context"`
}

// Concepts with embedded_at IS NULL, scoped to a repository. The
// embed_concepts worker bulk-embeds these (canonical_name + " " +
// context) into the okt_concepts Qdrant collection.
func (q *Queries) ListNewConceptsForEmbedding(ctx context.Context, repositoryID pgtype.UUID) ([]ListNewConceptsForEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, listNewConceptsForEmbedding, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewConceptsForEmbeddingRow
	for rows.Next() {
		var i ListNewConceptsForEmbeddingRow
		if err := rows.Scan(&i.ID, &i.CanonicalName, &i.Context); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewConceptsForEmbeddingBySource = `-- name: ListNewConceptsForEmbeddingBySource :many
SELECT DISTINCT c.id, c.canonical_name, c.context, c.created_at
FROM okt_repository.concepts c
JOIN okt_repository.fact_concepts fc ON fc.concept_id = c.id
JOIN okt_repository.fact_sources fs ON fs.fact_id = fc.fact_id
WHERE c.repository_id = $1
  AND fs.source_id = $2
  AND c.embedded_at IS NULL
ORDER BY c.created_at
`

type ListNewConceptsForEmbeddingBySourceParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	SourceID     pgtype.UUID `json:"source_id"`
}

type ListNewConceptsForEmbeddingBySourceRow struct {
	ID            pgtype.UUID        `json:"id"`
	CanonicalName string             `json:"canonical_name"`
	Context       string             `json:"context"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// Source-scoped variant of ListNewConceptsForEmbedding. Concepts
// have no direct source link; they reach sources via
// fact_concepts → fact_sources. This selects unembedded concepts
// that are linked to at least one fact linked to THIS source.
// DISTINCT is required because a concept may be linked to multiple
// facts, and a fact to multiple sources, so the join expands. A
// concept already embedded by another source's earlier pass has
// embedded_at set and is excluded by the IS NULL filter, so the
// two passes are idempotent.
//
// created_at is selected (not just used in ORDER BY) because
// Postgres requires ORDER BY expressions to appear in the select
// list of a DISTINCT query (SQLSTATE 42P10 otherwise). The repo-wide
// ListNewConceptsForEmbedding query does the same.
func (q *Queries) ListNewConceptsForEmbeddingBySource(ctx context.Context, arg ListNewConceptsForEmbeddingBySourceParams) ([]ListNewConceptsForEmbeddingBySourceRow, error) {
	rows, err := q.db.Query(ctx, listNewConceptsForEmbeddingBySource, arg.RepositoryID, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewConceptsForEmbeddingBySourceRow
	for rows.Next() {
		var i ListNewConceptsForEmbeddingBySourceRow
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalName,
			&i.Context,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStableFactsForConceptExtraction = `-- name: ListStableFactsForConceptExtraction :many
SELECT DISTINCT f.id, f.text, f.created_at
FROM okt_repository.facts f
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
JOIN okt_repository.sources s ON fs.source_id = s.id
WHERE s.repository_id = $1
  AND f.status = 'stable'
  AND NOT EXISTS (SELECT 1 FROM okt_repository.fact_concepts fc WHERE fc.fact_id = f.id)
  AND NOT EXISTS (SELECT 1 FROM okt_repository.fact_concept_skips sk WHERE sk.fact_id = f.id)
  AND NOT EXISTS (SELECT 1 FROM okt_repository.fact_candidates fca WHERE fca.fact_id = f.id)
ORDER BY f.created_at
LIMIT $2
`

type ListStableFactsForConceptExtractionParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	BatchSize    int32       `json:"batch_size"`
}

type ListStableFactsForConceptExtractionRow struct {
	ID        pgtype.UUID        `json:"id"`
	Text      string             `json:"text"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Stable facts not yet linked to any concept and not permanently
// skipped. Batched by LIMIT so the worker can process a repo in
// chunks without loading every fact into memory at once. Ordered
// by created_at so the batch order is stable across runs (a
// re-enqueue that races a previous pass picks up where the first
// pass left off).
//
// DISTINCT is critical: a fact may have many fact_sources rows
// (one per source it was extracted from), and the JOIN shape
// (facts JOIN fact_sources JOIN sources) returns the same fact
// once per source. That duplication caused the worker to call
// the LLM N times for one fact and then hit the fact_concepts
// unique index on the second insert, surfacing pgx.ErrNoRows as
// a fatal error. DISTINCT collapses the duplicates; the JOIN
// remains because facts does not carry repository_id (see
// 0013_facts.up.sql), so the repo filter must go via sources.
func (q *Queries) ListStableFactsForConceptExtraction(ctx context.Context, arg ListStableFactsForConceptExtractionParams) ([]ListStableFactsForConceptExtractionRow, error) {
	rows, err := q.db.Query(ctx, listStableFactsForConceptExtraction, arg.RepositoryID, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStableFactsForConceptExtractionRow
	for rows.Next() {
		var i ListStableFactsForConceptExtractionRow
		if err := rows.Scan(&i.ID, &i.Text, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStableFactsForConceptExtractionBySource = `-- name: ListStableFactsForConceptExtractionBySource :many
SELECT DISTINCT f.id, f.text, f.created_at
FROM okt_repository.facts f
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
JOIN okt_repository.sources s ON fs.source_id = s.id
WHERE s.repository_id = $1
  AND fs.source_id = $2
  AND f.status = 'stable'
  AND NOT EXISTS (SELECT 1 FROM okt_repository.fact_concepts fc WHERE fc.fact_id = f.id)
  AND NOT EXISTS (SELECT 1 FROM okt_repository.fact_concept_skips sk WHERE sk.fact_id = f.id)
  AND NOT EXISTS (SELECT 1 FROM okt_repository.fact_candidates fca WHERE fca.fact_id = f.id)
ORDER BY f.created_at
LIMIT $3
`

type ListStableFactsForConceptExtractionBySourceParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	SourceID     pgtype.UUID `json:"source_id"`
	BatchSize    int32       `json:"batch_size"`
}

type ListStableFactsForConceptExtractionBySourceRow struct {
	ID        pgtype.UUID        `json:"id"`
	Text      string             `json:"text"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Source-scoped variant of ListStableFactsForConceptExtraction.
// Same filters (stable, not yet linked to a concept, not skipped)
// but additionally constrained to facts linked to THIS source via
// fact_sources. Used by the source-scoped extract_concepts pass so
// each source's job only scans its own facts rather than re-scanning
// the whole repo every time any source completes processing. The
// fact_sources join is already present for the repo filter (facts
// has no repository_id), so the source filter rides the same join;
// DISTINCT collapses any per-source duplication (a fact may have
// multiple fact_sources rows for the same source across chunks).
func (q *Queries) ListStableFactsForConceptExtractionBySource(ctx context.Context, arg ListStableFactsForConceptExtractionBySourceParams) ([]ListStableFactsForConceptExtractionBySourceRow, error) {
	rows, err := q.db.Query(ctx, listStableFactsForConceptExtractionBySource, arg.RepositoryID, arg.SourceID, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStableFactsForConceptExtractionBySourceRow
	for rows.Next() {
		var i ListStableFactsForConceptExtractionBySourceRow
		if err := rows.Scan(&i.ID, &i.Text, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnresolvedCandidatesByRepo = `-- name: ListUnresolvedCandidatesByRepo :many
SELECT id, repository_id, concept_text, context, seed_aliases, resolved_concept_id, resolved_at, created_at FROM okt_repository.concept_candidates
WHERE repository_id = $1
  AND resolved_concept_id IS NULL
ORDER BY created_at
`

// All unresolved candidates in a repo. Used by refine_concepts for
// the repo-wide fallback path (manual re-enqueue / periodic catch-up).
func (q *Queries) ListUnresolvedCandidatesByRepo(ctx context.Context, repositoryID pgtype.UUID) ([]OktRepositoryConceptCandidate, error) {
	rows, err := q.db.Query(ctx, listUnresolvedCandidatesByRepo, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktRepositoryConceptCandidate
	for rows.Next() {
		var i OktRepositoryConceptCandidate
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.ConceptText,
			&i.Context,
			&i.SeedAliases,
			&i.ResolvedConceptID,
			&i.ResolvedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnresolvedCandidatesBySource = `-- name: ListUnresolvedCandidatesBySource :many
SELECT DISTINCT cc.id, cc.repository_id, cc.concept_text, cc.context, cc.seed_aliases, cc.resolved_concept_id, cc.resolved_at, cc.created_at
FROM okt_repository.concept_candidates cc
JOIN okt_repository.fact_candidates fc ON fc.candidate_id = cc.id
JOIN okt_repository.fact_sources fs ON fs.fact_id = fc.fact_id
WHERE fs.source_id = $1
  AND cc.resolved_concept_id IS NULL
ORDER BY cc.created_at
`

// Unresolved candidates whose facts are linked to this source.
// Used by refine_concepts to list its source-scoped work set.
func (q *Queries) ListUnresolvedCandidatesBySource(ctx context.Context, sourceID pgtype.UUID) ([]OktRepositoryConceptCandidate, error) {
	rows, err := q.db.Query(ctx, listUnresolvedCandidatesBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktRepositoryConceptCandidate
	for rows.Next() {
		var i OktRepositoryConceptCandidate
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.ConceptText,
			&i.Context,
			&i.SeedAliases,
			&i.ResolvedConceptID,
			&i.ResolvedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConceptEmbedded = `-- name: MarkConceptEmbedded :one
UPDATE okt_repository.concepts
SET embedded_at = now(),
    embedded_model = $2
WHERE id = $1
RETURNING id, repository_id, canonical_name, context, description, embedded_at, embedded_model, created_at, summarizing_at, aliases_refined_at, promptset_hash
`

type MarkConceptEmbeddedParams struct {
	ID            pgtype.UUID `json:"id"`
	EmbeddedModel *string     `json:"embedded_model"`
}

func (q *Queries) MarkConceptEmbedded(ctx context.Context, arg MarkConceptEmbeddedParams) (OktRepositoryConcept, error) {
	row := q.db.QueryRow(ctx, markConceptEmbedded, arg.ID, arg.EmbeddedModel)
	var i OktRepositoryConcept
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.CanonicalName,
		&i.Context,
		&i.Description,
		&i.EmbeddedAt,
		&i.EmbeddedModel,
		&i.CreatedAt,
		&i.SummarizingAt,
		&i.AliasesRefinedAt,
		&i.PromptsetHash,
	)
	return i, err
}

const reassignFactCandidatesToConcept = `-- name: ReassignFactCandidatesToConcept :exec
INSERT INTO okt_repository.fact_concepts (fact_id, concept_id, first_seen_at)
SELECT fc.fact_id, $1, fc.first_seen_at
FROM okt_repository.fact_candidates fc
WHERE fc.candidate_id = $2
ON CONFLICT (fact_id, concept_id) DO NOTHING
`

type ReassignFactCandidatesToConceptParams struct {
	NewConceptID   pgtype.UUID `json:"new_concept_id"`
	OldCandidateID pgtype.UUID `json:"old_candidate_id"`
}

// Move fact_candidates rows to fact_concepts for the target concept.
// ON CONFLICT DO NOTHING so facts already linked to the target
// (via a prior candidate resolution or direct fact_concepts link)
// are not duplicated.
func (q *Queries) ReassignFactCandidatesToConcept(ctx context.Context, arg ReassignFactCandidatesToConceptParams) error {
	_, err := q.db.Exec(ctx, reassignFactCandidatesToConcept, arg.NewConceptID, arg.OldCandidateID)
	return err
}

const reassignFactConceptsToConcept = `-- name: ReassignFactConceptsToConcept :exec
INSERT INTO okt_repository.fact_concepts (fact_id, concept_id, first_seen_at, promptset_hash)
SELECT fc.fact_id, $1, fc.first_seen_at, fc.promptset_hash
FROM okt_repository.fact_concepts fc
WHERE fc.concept_id = $2
ON CONFLICT (fact_id, concept_id) DO NOTHING
`

type ReassignFactConceptsToConceptParams struct {
	NewConceptID pgtype.UUID `json:"new_concept_id"`
	OldConceptID pgtype.UUID `json:"old_concept_id"`
}

// Re-link every fact_concepts row pointing at old_concept_id to
// new_concept_id, ignoring (fact_id, new_concept_id) pairs that
// already exist (ON CONFLICT DO NOTHING). Used by the migrate_context
// merge path before deleting the old concept row. Preserves the
// promptset_hash of each link so a merge does not silently drop the
// philosophy tag.
func (q *Queries) ReassignFactConceptsToConcept(ctx context.Context, arg ReassignFactConceptsToConceptParams) error {
	_, err := q.db.Exec(ctx, reassignFactConceptsToConcept, arg.NewConceptID, arg.OldConceptID)
	return err
}

const recordFactConceptSkip = `-- name: RecordFactConceptSkip :one
INSERT INTO okt_repository.fact_concept_skips (fact_id, last_error)
VALUES ($1, $2)
ON CONFLICT (fact_id) DO UPDATE
SET last_error = EXCLUDED.last_error,
    skipped_at = now()
RETURNING fact_id, last_error, skipped_at
`

type RecordFactConceptSkipParams struct {
	FactID    pgtype.UUID `json:"fact_id"`
	LastError string      `json:"last_error"`
}

// Permanently marks a fact as skipped for concept extraction
// (e.g. the LLM returned a transient error and we don't want to
// retry it on every subsequent pass, since there is no periodic
// re-driver). An operator must delete the row to retry. ON
// CONFLICT DO UPDATE so re-skipping the same fact refreshes the
// last_error and skipped_at.
func (q *Queries) RecordFactConceptSkip(ctx context.Context, arg RecordFactConceptSkipParams) (OktRepositoryFactConceptSkip, error) {
	row := q.db.QueryRow(ctx, recordFactConceptSkip, arg.FactID, arg.LastError)
	var i OktRepositoryFactConceptSkip
	err := row.Scan(&i.FactID, &i.LastError, &i.SkippedAt)
	return i, err
}

const relinkFactConcepts = `-- name: RelinkFactConcepts :exec
INSERT INTO okt_repository.fact_concepts (fact_id, concept_id, first_seen_at, promptset_hash)
SELECT $1, fc.concept_id, fc.first_seen_at, fc.promptset_hash
FROM okt_repository.fact_concepts fc
WHERE fc.fact_id = $2
ON CONFLICT (fact_id, concept_id) DO NOTHING
`

type RelinkFactConceptsParams struct {
	WinnerID pgtype.UUID `json:"winner_id"`
	LoserID  pgtype.UUID `json:"loser_id"`
}

// Copy a loser fact's concept links onto the winner before the
// loser is deleted (ON DELETE CASCADE would otherwise drop them).
// ON CONFLICT DO NOTHING preserves the winner's existing links.
// Called by the dedup worker's mergeSources, alongside
// RelinkFactReferences, so a dedup merge preserves all concept
// mappings from both the winner and the loser. Preserves the
// promptset_hash of each link so a dedup merge does not silently
// drop the philosophy tag.
func (q *Queries) RelinkFactConcepts(ctx context.Context, arg RelinkFactConceptsParams) error {
	_, err := q.db.Exec(ctx, relinkFactConcepts, arg.WinnerID, arg.LoserID)
	return err
}

const resetConceptEmbedding = `-- name: ResetConceptEmbedding :exec
UPDATE okt_repository.concepts
SET embedded_at = NULL
WHERE id = $1
`

// Force re-embed a concept after its fact set or context changed
// (the merge path of migrate_context re-links facts onto a target
// concept, so the target's vector is stale until re-embedded). Sets
// embedded_at = NULL so the embed_concepts worker picks it up.
func (q *Queries) ResetConceptEmbedding(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetConceptEmbedding, id)
	return err
}

const resetConceptEmbeddingForReembed = `-- name: ResetConceptEmbeddingForReembed :exec
UPDATE okt_repository.concepts
SET embedded_at = NULL,
    embedded_model = NULL
WHERE id = ANY($1::uuid[])
`

// Batch version of ResetConceptEmbedding for the CacheReconciler's
// re-embed path. Clears embedded_at + embedded_model on a set of
// concepts so the embed_concepts worker (which filters
// embedded_at IS NULL) re-embeds them with the local model. The
// Qdrant points for these concepts are deleted separately by the
// caller (now possible because Qdrant uses local concept UUIDs,
// not remote registry UUIDs).
func (q *Queries) ResetConceptEmbeddingForReembed(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetConceptEmbeddingForReembed, dollar_1)
	return err
}

const resolveCandidate = `-- name: ResolveCandidate :exec
UPDATE okt_repository.concept_candidates
SET resolved_concept_id = $1,
    resolved_at = now()
WHERE id = $2
`

type ResolveCandidateParams struct {
	ResolvedConceptID pgtype.UUID `json:"resolved_concept_id"`
	ID                pgtype.UUID `json:"id"`
}

// Mark a candidate as resolved: record which concept it maps to
// and when. The candidate row stays as a cache entry for future
// extractions of the same (concept_text, context).
func (q *Queries) ResolveCandidate(ctx context.Context, arg ResolveCandidateParams) error {
	_, err := q.db.Exec(ctx, resolveCandidate, arg.ResolvedConceptID, arg.ID)
	return err
}

const setConceptRefinedAt = `-- name: SetConceptRefinedAt :exec
UPDATE okt_repository.concepts
SET aliases_refined_at = now()
WHERE id = $1
`

// Mark a concept as refined at the current time so refine_concepts
// skips it on future passes. Used when promoting a candidate to a
// new concept and when importing pre-refined concepts from the
// registry.
func (q *Queries) SetConceptRefinedAt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setConceptRefinedAt, id)
	return err
}

const updateConceptCanonical = `-- name: UpdateConceptCanonical :exec
UPDATE okt_repository.concepts
SET canonical_name = $1
WHERE id = $2
`

type UpdateConceptCanonicalParams struct {
	CanonicalName string      `json:"canonical_name"`
	ID            pgtype.UUID `json:"id"`
}

// Rename a concept's canonical_name. Used by refine_concepts when
// the AI proposes a different canonical than the extracted text
// (step 3c). The advisory lock held by the worker prevents a
// parallel refinement from racing on the same canonical.
func (q *Queries) UpdateConceptCanonical(ctx context.Context, arg UpdateConceptCanonicalParams) error {
	_, err := q.db.Exec(ctx, updateConceptCanonical, arg.CanonicalName, arg.ID)
	return err
}

const updateConceptContext = `-- name: UpdateConceptContext :exec
UPDATE okt_repository.concepts
SET context = $1
WHERE id = $2
`

type UpdateConceptContextParams struct {
	Context string      `json:"context"`
	ID      pgtype.UUID `json:"id"`
}

// Reassign a single concept's context (the migrate_context path
// where no target (name, new_context) exists, so a plain UPDATE is
// safe). The unique index on (repo, lower(name), lower(context))
// guarantees no conflict at this point because the caller already
// checked GetConceptByNameContext returned no rows.
func (q *Queries) UpdateConceptContext(ctx context.Context, arg UpdateConceptContextParams) error {
	_, err := q.db.Exec(ctx, updateConceptContext, arg.Context, arg.ID)
	return err
}
