// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: facts.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFactReference = `-- name: AddFactReference :exec
INSERT INTO okt_repository.fact_references (fact_id, source_id, sentence_index, chunk_index, promptset_hash)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (fact_id, source_id, sentence_index) DO NOTHING
`

type AddFactReferenceParams struct {
	FactID        pgtype.UUID `json:"fact_id"`
	SourceID      pgtype.UUID `json:"source_id"`
	SentenceIndex int32       `json:"sentence_index"`
	ChunkIndex    int32       `json:"chunk_index"`
	PromptsetHash *string     `json:"promptset_hash"`
}

// One row per (fact, source, sentence_index). Idempotent on the PK
// so re-processing a source doesn't double-count a citation.
// promptset_hash tags the citation with the philosophy that produced
// the fact, mirroring facts.promptset_hash so the junction stays
// queryable by philosophy.
func (q *Queries) AddFactReference(ctx context.Context, arg AddFactReferenceParams) error {
	_, err := q.db.Exec(ctx, addFactReference,
		arg.FactID,
		arg.SourceID,
		arg.SentenceIndex,
		arg.ChunkIndex,
		arg.PromptsetHash,
	)
	return err
}

const addFactSource = `-- name: AddFactSource :exec
INSERT INTO okt_repository.fact_sources (fact_id, source_id, chunk_index)
VALUES ($1, $2, $3)
ON CONFLICT (fact_id, source_id) DO NOTHING
`

type AddFactSourceParams struct {
	FactID     pgtype.UUID `json:"fact_id"`
	SourceID   pgtype.UUID `json:"source_id"`
	ChunkIndex int32       `json:"chunk_index"`
}

// Idempotent: a fact linked to the same source twice (e.g. re-processing)
// doesn't double-count. ON CONFLICT preserves the original first_seen_at.
// Uses :exec (no RETURNING) so the conflict path returns no error —
// callers that need the row back can re-query by (fact_id, source_id).
func (q *Queries) AddFactSource(ctx context.Context, arg AddFactSourceParams) error {
	_, err := q.db.Exec(ctx, addFactSource, arg.FactID, arg.SourceID, arg.ChunkIndex)
	return err
}

const countFactsByRepo = `-- name: CountFactsByRepo :one
SELECT COUNT(DISTINCT f.id)
FROM okt_repository.facts f
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
JOIN okt_repository.sources s ON fs.source_id = s.id
WHERE s.repository_id = $1
  AND ($2::text = '' OR f.status = $2)
  AND ($3::text = '' OR f.search_tsv @@ websearch_to_tsquery('english', $3))
`

type CountFactsByRepoParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Column2      string      `json:"column_2"`
	Column3      string      `json:"column_3"`
}

// Companion count for ListFactsByRepoWithSourceCount. Counts
// DISTINCT facts (a fact with N sources has N rows in
// fact_sources) matching the same WHERE clause as the list query,
// minus the ORDER BY. Used by the API envelope to report `total`
// without a window-function COUNT(*) OVER ().
func (q *Queries) CountFactsByRepo(ctx context.Context, arg CountFactsByRepoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFactsByRepo, arg.RepositoryID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFactsByRepoForConcept = `-- name: CountFactsByRepoForConcept :one
SELECT COUNT(DISTINCT f.id)
FROM okt_repository.facts f
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
JOIN okt_repository.sources s ON fs.source_id = s.id
WHERE s.repository_id = $1
  AND ($2::text = '' OR f.status = $2)
  AND ($3::text = '' OR f.search_tsv @@ websearch_to_tsquery('english', $3))
  AND EXISTS (
      SELECT 1 FROM okt_repository.fact_concepts fc
      WHERE fc.fact_id = f.id AND fc.concept_id = ANY($4::uuid[])
  )
`

type CountFactsByRepoForConceptParams struct {
	RepositoryID pgtype.UUID   `json:"repository_id"`
	Column2      string        `json:"column_2"`
	Column3      string        `json:"column_3"`
	Column4      []pgtype.UUID `json:"column_4"`
}

// Companion count for ListFactsByRepoWithSourceCountForConcept. Same
// concept-id array filter, minus the ORDER BY / LIMIT / OFFSET.
func (q *Queries) CountFactsByRepoForConcept(ctx context.Context, arg CountFactsByRepoForConceptParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFactsByRepoForConcept,
		arg.RepositoryID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFactsBySource = `-- name: CountFactsBySource :one
SELECT COUNT(DISTINCT f.id)
FROM okt_repository.facts f
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
WHERE fs.source_id = $1
  AND ($2::text = '' OR f.status = $2)
  AND ($3::text = '' OR f.search_tsv @@ websearch_to_tsquery('english', $3))
`

type CountFactsBySourceParams struct {
	SourceID pgtype.UUID `json:"source_id"`
	Column2  string      `json:"column_2"`
	Column3  string      `json:"column_3"`
}

// Companion count for ListFactsBySource. Counts DISTINCT facts
// linked to the source and matching the status/search filters so
// the API envelope can report `total` without a window function.
func (q *Queries) CountFactsBySource(ctx context.Context, arg CountFactsBySourceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFactsBySource, arg.SourceID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSharedFactsByConceptGroups = `-- name: CountSharedFactsByConceptGroups :one
SELECT COUNT(DISTINCT f.id)
FROM okt_repository.facts f
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
JOIN okt_repository.sources s ON fs.source_id = s.id
JOIN (
    SELECT fc.fact_id, COUNT(DISTINCT g2.gv) AS covered_groups
    FROM okt_repository.fact_concepts fc,
         LATERAL unnest($4::uuid[]) WITH ORDINALITY AS c1(cid, c1_idx),
         LATERAL unnest($5::int4[]) WITH ORDINALITY AS g2(gv, g2_idx)
    WHERE c1.c1_idx = g2.g2_idx
      AND c1.cid = fc.concept_id
    GROUP BY fc.fact_id
) cov ON cov.fact_id = f.id
WHERE s.repository_id = $1
  AND ($2::text = '' OR f.status = $2)
  AND ($3::text = '' OR f.search_tsv @@ websearch_to_tsquery('english', $3))
  AND cov.covered_groups = (SELECT COUNT(DISTINCT g) FROM unnest($5::int4[]) AS t(g))
`

type CountSharedFactsByConceptGroupsParams struct {
	RepositoryID pgtype.UUID   `json:"repository_id"`
	Column2      string        `json:"column_2"`
	Column3      string        `json:"column_3"`
	Column4      []pgtype.UUID `json:"column_4"`
	Column5      []int32       `json:"column_5"`
}

// Companion count for ListSharedFactsByConceptGroups. Same
// concept-id + group-index intersection filter, minus ORDER BY /
// LIMIT / OFFSET.
func (q *Queries) CountSharedFactsByConceptGroups(ctx context.Context, arg CountSharedFactsByConceptGroupsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSharedFactsByConceptGroups,
		arg.RepositoryID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFact = `-- name: CreateFact :one
INSERT INTO okt_repository.facts (id, text, fact_kind, image_url, promptset_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, text, status, embedded_at, embedded_model, created_at, search_tsv, image_url, fact_kind, promptset_hash
`

type CreateFactParams struct {
	ID            pgtype.UUID `json:"id"`
	Text          string      `json:"text"`
	FactKind      string      `json:"fact_kind"`
	ImageUrl      *string     `json:"image_url"`
	PromptsetHash *string     `json:"promptset_hash"`
}

// fact_kind defaults to 'text' (the column default) when the caller
// does not specify it; image facts pass 'image' plus a non-null
// image_url so the frontend can render the picture next to the fact
// text. image_url is nullable so text facts leave it NULL.
// promptset_hash tags the fact with the philosophy that produced it
// so downstream queries (synthesis, registry pull) can filter to a
// single promptset and decompositions from different promptsets do
// not mix. The caller passes the repo's effective promptset hash;
// NULL is allowed (legacy rows) and interpreted as the built-in.
func (q *Queries) CreateFact(ctx context.Context, arg CreateFactParams) (OktRepositoryFact, error) {
	row := q.db.QueryRow(ctx, createFact,
		arg.ID,
		arg.Text,
		arg.FactKind,
		arg.ImageUrl,
		arg.PromptsetHash,
	)
	var i OktRepositoryFact
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Status,
		&i.EmbeddedAt,
		&i.EmbeddedModel,
		&i.CreatedAt,
		&i.SearchTsv,
		&i.ImageUrl,
		&i.FactKind,
		&i.PromptsetHash,
	)
	return i, err
}

const deleteDuplicateFactReferences = `-- name: DeleteDuplicateFactReferences :exec
DELETE FROM okt_repository.fact_references fr_loser
USING okt_repository.fact_references fr_winner
WHERE fr_loser.fact_id = $1
  AND fr_winner.fact_id = $2
  AND fr_loser.source_id = fr_winner.source_id
  AND fr_loser.sentence_index = fr_winner.sentence_index
`

type DeleteDuplicateFactReferencesParams struct {
	FactID   pgtype.UUID `json:"fact_id"`
	FactID_2 pgtype.UUID `json:"fact_id_2"`
}

// Before relinking a loser fact's citations onto the survivor,
// delete the loser's rows that would collide with the survivor's
// existing citations (same source_id + sentence_index). The PK
// (fact_id, source_id, sentence_index) would otherwise reject the
// UPDATE. Plain integer comparison — no array ops.
func (q *Queries) DeleteDuplicateFactReferences(ctx context.Context, arg DeleteDuplicateFactReferencesParams) error {
	_, err := q.db.Exec(ctx, deleteDuplicateFactReferences, arg.FactID, arg.FactID_2)
	return err
}

const deleteFactByID = `-- name: DeleteFactByID :exec
DELETE FROM okt_repository.facts WHERE id = $1
`

func (q *Queries) DeleteFactByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFactByID, id)
	return err
}

const deleteStaleFactsInDB = `-- name: DeleteStaleFactsInDB :many
DELETE FROM okt_repository.facts
WHERE id IN (
    SELECT f.id FROM okt_repository.facts f
    WHERE f.status = ANY($1::text[])
      AND f.created_at < $2
    LIMIT $3
)
RETURNING id
`

type DeleteStaleFactsInDBParams struct {
	Column1   []string           `json:"column_1"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
}

// Bounded delete of facts with status in the given set older than
// the cutoff. Returns the deleted IDs so the caller can delete the
// matching Qdrant points. Bounded (LIMIT $3) to avoid multi-minute
// WAL spikes at millions of facts; the catchup job loops until 0
// rows are returned.
func (q *Queries) DeleteStaleFactsInDB(ctx context.Context, arg DeleteStaleFactsInDBParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, deleteStaleFactsInDB, arg.Column1, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFactByID = `-- name: GetFactByID :one
SELECT id, text, status, embedded_at, embedded_model, created_at, search_tsv, image_url, fact_kind, promptset_hash FROM okt_repository.facts WHERE id = $1
`

func (q *Queries) GetFactByID(ctx context.Context, id pgtype.UUID) (OktRepositoryFact, error) {
	row := q.db.QueryRow(ctx, getFactByID, id)
	var i OktRepositoryFact
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Status,
		&i.EmbeddedAt,
		&i.EmbeddedModel,
		&i.CreatedAt,
		&i.SearchTsv,
		&i.ImageUrl,
		&i.FactKind,
		&i.PromptsetHash,
	)
	return i, err
}

const getFactByTextAndSource = `-- name: GetFactByTextAndSource :one
SELECT f.id, f.text, f.status, f.embedded_at, f.embedded_model, f.created_at, f.search_tsv, f.image_url, f.fact_kind, f.promptset_hash FROM okt_repository.facts f
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
WHERE f.text = $1 AND fs.source_id = $2
LIMIT 1
`

type GetFactByTextAndSourceParams struct {
	Text     string      `json:"text"`
	SourceID pgtype.UUID `json:"source_id"`
}

// Exact-text match for the cache import's delta-aware no-op check.
// If a fact with the exact same text already exists linked to this
// source, the import skips CreateFact entirely (no new row, no
// Qdrant point, no downstream job). After the first import + dedup,
// a merged survivor is re-linked to the source via mergeSources,
// so this query finds the survivor and the re-import is a no-op.
// No index on facts.text today; this is a sequential scan, which
// is acceptable because the cache import runs once per source and
// the alternative (re-create + re-dedup) is more expensive.
func (q *Queries) GetFactByTextAndSource(ctx context.Context, arg GetFactByTextAndSourceParams) (OktRepositoryFact, error) {
	row := q.db.QueryRow(ctx, getFactByTextAndSource, arg.Text, arg.SourceID)
	var i OktRepositoryFact
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Status,
		&i.EmbeddedAt,
		&i.EmbeddedModel,
		&i.CreatedAt,
		&i.SearchTsv,
		&i.ImageUrl,
		&i.FactKind,
		&i.PromptsetHash,
	)
	return i, err
}

const getFactsByIDs = `-- name: GetFactsByIDs :many
SELECT id, text, status, embedded_at, embedded_model, created_at, search_tsv, image_url, fact_kind, promptset_hash FROM okt_repository.facts WHERE id = ANY($1::uuid[])
`

// Batch lookup used by the annotate_report worker to fetch the text
// of every candidate fact Qdrant returned for a sentence batch, so
// the posture classifier can render (sentence, fact) pairs without
// N+1 GetFactByID round-trips. The caller passes the deduped fact
// ids across the whole batch; order is unspecified.
func (q *Queries) GetFactsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]OktRepositoryFact, error) {
	rows, err := q.db.Query(ctx, getFactsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktRepositoryFact
	for rows.Next() {
		var i OktRepositoryFact
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Status,
			&i.EmbeddedAt,
			&i.EmbeddedModel,
			&i.CreatedAt,
			&i.SearchTsv,
			&i.ImageUrl,
			&i.FactKind,
			&i.PromptsetHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFactsByIDsForSearch = `-- name: GetFactsByIDsForSearch :many
SELECT f.id, f.text, f.status, f.embedded_at, f.embedded_model, f.created_at,
       f.fact_kind, f.image_url,
       COALESCE(fs_count.source_count, 0) AS source_count,
       MIN(fs.source_id::text)::uuid AS source_id
FROM okt_repository.facts f
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
JOIN okt_repository.sources s ON fs.source_id = s.id
LEFT JOIN (
    SELECT fact_id, COUNT(*) AS source_count
    FROM okt_repository.fact_sources
    GROUP BY fact_id
) fs_count ON fs_count.fact_id = f.id
WHERE f.id = ANY($1::uuid[])
  AND s.repository_id = $2
GROUP BY f.id, fs_count.source_count
`

type GetFactsByIDsForSearchParams struct {
	Ids          []pgtype.UUID `json:"ids"`
	RepositoryID pgtype.UUID   `json:"repository_id"`
}

type GetFactsByIDsForSearchRow struct {
	ID            pgtype.UUID        `json:"id"`
	Text          string             `json:"text"`
	Status        string             `json:"status"`
	EmbeddedAt    pgtype.Timestamptz `json:"embedded_at"`
	EmbeddedModel *string            `json:"embedded_model"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	FactKind      string             `json:"fact_kind"`
	ImageUrl      *string            `json:"image_url"`
	SourceCount   int64              `json:"source_count"`
	SourceID      pgtype.UUID        `json:"source_id"`
}

// Fetches the full ListFactsByRepoWithSourceCount-shaped row for an
// arbitrary set of fact ids in a single round-trip. Used by the
// hybrid search path: the lexical channel over-fetches its own
// rows, the semantic channel (Qdrant) returns only ids, and this
// query fills in the rows for any semantic-only ids the lexical
// batch didn't already return. No ordering is applied here — the
// caller re-orders the combined row set in Go to match the fused
// ranking (sqlc can't express array_position(...) cleanly and the
// result set is small: at most the over-fetch cap per channel).
// Repository scoping is enforced so a cross-repo id in the input
// set is silently dropped (defense in depth alongside Qdrant's
// repository payload filter).
func (q *Queries) GetFactsByIDsForSearch(ctx context.Context, arg GetFactsByIDsForSearchParams) ([]GetFactsByIDsForSearchRow, error) {
	rows, err := q.db.Query(ctx, getFactsByIDsForSearch, arg.Ids, arg.RepositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFactsByIDsForSearchRow
	for rows.Next() {
		var i GetFactsByIDsForSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Status,
			&i.EmbeddedAt,
			&i.EmbeddedModel,
			&i.CreatedAt,
			&i.FactKind,
			&i.ImageUrl,
			&i.SourceCount,
			&i.SourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactReferencesByFact = `-- name: ListFactReferencesByFact :many
SELECT fact_id, source_id, sentence_index, chunk_index, first_seen_at, promptset_hash FROM okt_repository.fact_references WHERE fact_id = $1
`

// Raw fact_references rows for a fact (no source join). Used by the
// dedup worker to relink a loser's citations onto a survivor.
func (q *Queries) ListFactReferencesByFact(ctx context.Context, factID pgtype.UUID) ([]OktRepositoryFactReference, error) {
	rows, err := q.db.Query(ctx, listFactReferencesByFact, factID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktRepositoryFactReference
	for rows.Next() {
		var i OktRepositoryFactReference
		if err := rows.Scan(
			&i.FactID,
			&i.SourceID,
			&i.SentenceIndex,
			&i.ChunkIndex,
			&i.FirstSeenAt,
			&i.PromptsetHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactReferencesBySource = `-- name: ListFactReferencesBySource :many
SELECT fr.fact_id, fr.source_id, fr.sentence_index, fr.chunk_index, fr.first_seen_at,
       f.text, f.status, f.fact_kind, f.image_url, f.created_at
FROM okt_repository.fact_references fr
JOIN okt_repository.facts f ON f.id = fr.fact_id
WHERE fr.source_id = $1
ORDER BY fr.sentence_index
`

type ListFactReferencesBySourceRow struct {
	FactID        pgtype.UUID        `json:"fact_id"`
	SourceID      pgtype.UUID        `json:"source_id"`
	SentenceIndex int32              `json:"sentence_index"`
	ChunkIndex    int32              `json:"chunk_index"`
	FirstSeenAt   pgtype.Timestamptz `json:"first_seen_at"`
	Text          string             `json:"text"`
	Status        string             `json:"status"`
	FactKind      string             `json:"fact_kind"`
	ImageUrl      *string            `json:"image_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// UI-facing: every citation in a source, joined with the fact row so
// the frontend can group facts by sentence_index and render the
// highlight + modal. Ordered by sentence_index so the frontend can
// stream the list into a Map in one pass.
func (q *Queries) ListFactReferencesBySource(ctx context.Context, sourceID pgtype.UUID) ([]ListFactReferencesBySourceRow, error) {
	rows, err := q.db.Query(ctx, listFactReferencesBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFactReferencesBySourceRow
	for rows.Next() {
		var i ListFactReferencesBySourceRow
		if err := rows.Scan(
			&i.FactID,
			&i.SourceID,
			&i.SentenceIndex,
			&i.ChunkIndex,
			&i.FirstSeenAt,
			&i.Text,
			&i.Status,
			&i.FactKind,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactSources = `-- name: ListFactSources :many
SELECT fs.fact_id, fs.source_id, fs.chunk_index, fs.first_seen_at,
       s.url, s.parsed_title, s.parsed_sitename, s.parsed_author,
       s.published_at
FROM okt_repository.fact_sources fs
JOIN okt_repository.sources s ON fs.source_id = s.id
WHERE fs.fact_id = $1
ORDER BY fs.first_seen_at
`

type ListFactSourcesRow struct {
	FactID         pgtype.UUID        `json:"fact_id"`
	SourceID       pgtype.UUID        `json:"source_id"`
	ChunkIndex     int32              `json:"chunk_index"`
	FirstSeenAt    pgtype.Timestamptz `json:"first_seen_at"`
	Url            string             `json:"url"`
	ParsedTitle    *string            `json:"parsed_title"`
	ParsedSitename *string            `json:"parsed_sitename"`
	ParsedAuthor   *string            `json:"parsed_author"`
	PublishedAt    pgtype.Date        `json:"published_at"`
}

// Full source rows linked to a fact, joined with the source's url,
// parsed_title, parsed_sitename (publication name), parsed_author,
// and published_at so the fact detail endpoint surfaces enough
// source metadata for downstream consumers (the UI, the MCP getFact
// tool, and LLM synthesis prompts) to attribute facts to their
// publications and answer publication- and time-bound questions
// (e.g. MultiHop-RAG comparison and temporal queries). Ordered by
// first_seen_at so the UI shows the oldest confirmation first.
func (q *Queries) ListFactSources(ctx context.Context, factID pgtype.UUID) ([]ListFactSourcesRow, error) {
	rows, err := q.db.Query(ctx, listFactSources, factID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFactSourcesRow
	for rows.Next() {
		var i ListFactSourcesRow
		if err := rows.Scan(
			&i.FactID,
			&i.SourceID,
			&i.ChunkIndex,
			&i.FirstSeenAt,
			&i.Url,
			&i.ParsedTitle,
			&i.ParsedSitename,
			&i.ParsedAuthor,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactSourcesByFact = `-- name: ListFactSourcesByFact :many
SELECT fact_id, source_id, chunk_index, first_seen_at FROM okt_repository.fact_sources WHERE fact_id = $1
`

// The raw fact_sources rows for a fact (no source join). The
// dedup worker uses this to walk a fact's current source set
// when merging a loser onto a survivor.
func (q *Queries) ListFactSourcesByFact(ctx context.Context, factID pgtype.UUID) ([]OktRepositoryFactSource, error) {
	rows, err := q.db.Query(ctx, listFactSourcesByFact, factID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktRepositoryFactSource
	for rows.Next() {
		var i OktRepositoryFactSource
		if err := rows.Scan(
			&i.FactID,
			&i.SourceID,
			&i.ChunkIndex,
			&i.FirstSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactsByRepoWithSourceCount = `-- name: ListFactsByRepoWithSourceCount :many
SELECT f.id, f.text, f.status, f.embedded_at, f.embedded_model, f.created_at,
       f.fact_kind, f.image_url,
       COALESCE(fs_count.source_count, 0) AS source_count,
       MIN(fs.source_id::text)::uuid AS source_id
FROM okt_repository.facts f
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
JOIN okt_repository.sources s ON fs.source_id = s.id
LEFT JOIN (
    SELECT fs2.fact_id, COUNT(*) AS source_count
    FROM okt_repository.fact_sources fs2
    JOIN okt_repository.sources s2 ON s2.id = fs2.source_id
    WHERE s2.repository_id = $1
    GROUP BY fs2.fact_id
) fs_count ON fs_count.fact_id = f.id
WHERE s.repository_id = $1
  AND ($2::text = '' OR f.status = $2)
  AND ($3::text = '' OR f.search_tsv @@ websearch_to_tsquery('english', $3))
GROUP BY f.id, fs_count.source_count
ORDER BY
    CASE WHEN $4 = 'source_count' THEN fs_count.source_count END DESC NULLS LAST,
    f.created_at DESC
LIMIT $5 OFFSET $6
`

type ListFactsByRepoWithSourceCountParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Column2      string      `json:"column_2"`
	Column3      string      `json:"column_3"`
	Column4      interface{} `json:"column_4"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

type ListFactsByRepoWithSourceCountRow struct {
	ID            pgtype.UUID        `json:"id"`
	Text          string             `json:"text"`
	Status        string             `json:"status"`
	EmbeddedAt    pgtype.Timestamptz `json:"embedded_at"`
	EmbeddedModel *string            `json:"embedded_model"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	FactKind      string             `json:"fact_kind"`
	ImageUrl      *string            `json:"image_url"`
	SourceCount   int64              `json:"source_count"`
	SourceID      pgtype.UUID        `json:"source_id"`
}

// Repo-level list with a computed source_count (aggregate JOIN).
// Paginated and searchable. The optional status filter ($2) accepts
// ” (all), 'stable', 'new', or 'to_delete'. The optional search
// ($3) runs through websearch_to_tsquery against facts.search_tsv.
// The optional sort ($4) accepts 'created_at' (default — newest
// first) or 'source_count' (most confirmed first); the sort is
// pushed into SQL so pagination stays globally consistent across
// pages (an in-memory sort would only re-order the current page).
// LIMIT $5 / OFFSET $6 apply on top of the ORDER BY.
//
// `source_id` is MIN(fs.source_id) so the row carries the source
// that produced the fact (the frontend's repo-level Facts list
// page does not have a source in the URL; image facts carry a
// service-routable image_url that points at this source, so the
// frontend needs the id to resolve it through getSourceImage).
// Image facts have a single junction row (chunk_index=-1) so MIN
// is the only source; text facts deduped across N sources
// arbitrarily pick one — the source_id is unused for text facts.
// Postgres has no MIN(uuid) aggregate, so cast to text and back.
func (q *Queries) ListFactsByRepoWithSourceCount(ctx context.Context, arg ListFactsByRepoWithSourceCountParams) ([]ListFactsByRepoWithSourceCountRow, error) {
	rows, err := q.db.Query(ctx, listFactsByRepoWithSourceCount,
		arg.RepositoryID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFactsByRepoWithSourceCountRow
	for rows.Next() {
		var i ListFactsByRepoWithSourceCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Status,
			&i.EmbeddedAt,
			&i.EmbeddedModel,
			&i.CreatedAt,
			&i.FactKind,
			&i.ImageUrl,
			&i.SourceCount,
			&i.SourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactsByRepoWithSourceCountForConcept = `-- name: ListFactsByRepoWithSourceCountForConcept :many
SELECT f.id, f.text, f.status, f.embedded_at, f.embedded_model, f.created_at,
       f.fact_kind, f.image_url,
       COALESCE(fs_count.source_count, 0) AS source_count,
       MIN(fs.source_id::text)::uuid AS source_id
FROM okt_repository.facts f
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
JOIN okt_repository.sources s ON fs.source_id = s.id
LEFT JOIN (
    SELECT fact_id, COUNT(*) AS source_count
    FROM okt_repository.fact_sources
    GROUP BY fact_id
) fs_count ON fs_count.fact_id = f.id
WHERE s.repository_id = $1
  AND ($2::text = '' OR f.status = $2)
  AND ($3::text = '' OR f.search_tsv @@ websearch_to_tsquery('english', $3))
  AND EXISTS (
      SELECT 1 FROM okt_repository.fact_concepts fc
      WHERE fc.fact_id = f.id AND fc.concept_id = ANY($4::uuid[])
  )
GROUP BY f.id, fs_count.source_count
ORDER BY
    CASE WHEN $5 = 'source_count' THEN fs_count.source_count END DESC NULLS LAST,
    f.created_at DESC
LIMIT $6 OFFSET $7
`

type ListFactsByRepoWithSourceCountForConceptParams struct {
	RepositoryID pgtype.UUID   `json:"repository_id"`
	Column2      string        `json:"column_2"`
	Column3      string        `json:"column_3"`
	Column4      []pgtype.UUID `json:"column_4"`
	Column5      interface{}   `json:"column_5"`
	Limit        int32         `json:"limit"`
	Offset       int32         `json:"offset"`
}

type ListFactsByRepoWithSourceCountForConceptRow struct {
	ID            pgtype.UUID        `json:"id"`
	Text          string             `json:"text"`
	Status        string             `json:"status"`
	EmbeddedAt    pgtype.Timestamptz `json:"embedded_at"`
	EmbeddedModel *string            `json:"embedded_model"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	FactKind      string             `json:"fact_kind"`
	ImageUrl      *string            `json:"image_url"`
	SourceCount   int64              `json:"source_count"`
	SourceID      pgtype.UUID        `json:"source_id"`
}

// concept-filtered variant of ListFactsByRepoWithSourceCount. The
// caller resolves the `concept` argument (a UUID, or a canonical
// name optionally narrowed by a `context`) into an array of
// concept_ids (the whole group, or just the matching contexts),
// then passes that array here. A fact matches when it links to ANY
// of those concept_ids via fact_concepts. Same select list, status
// filter, search, sort, and pagination as the unfiltered query so
// the MCP searchFacts tool can branch into this query without
// changing its output shape.
func (q *Queries) ListFactsByRepoWithSourceCountForConcept(ctx context.Context, arg ListFactsByRepoWithSourceCountForConceptParams) ([]ListFactsByRepoWithSourceCountForConceptRow, error) {
	rows, err := q.db.Query(ctx, listFactsByRepoWithSourceCountForConcept,
		arg.RepositoryID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFactsByRepoWithSourceCountForConceptRow
	for rows.Next() {
		var i ListFactsByRepoWithSourceCountForConceptRow
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Status,
			&i.EmbeddedAt,
			&i.EmbeddedModel,
			&i.CreatedAt,
			&i.FactKind,
			&i.ImageUrl,
			&i.SourceCount,
			&i.SourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactsBySource = `-- name: ListFactsBySource :many
SELECT f.id, f.text, f.status, f.embedded_at, f.embedded_model, f.created_at,
       f.fact_kind, f.image_url,
       COALESCE(fs_count.source_count, 0) AS source_count
FROM okt_repository.facts f
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
LEFT JOIN (
    SELECT fact_id, COUNT(*) AS source_count
    FROM okt_repository.fact_sources
    GROUP BY fact_id
) fs_count ON fs_count.fact_id = f.id
WHERE fs.source_id = $1
  AND ($2::text = '' OR f.status = $2)
  AND ($3::text = '' OR f.search_tsv @@ websearch_to_tsquery('english', $3))
ORDER BY fs.chunk_index, fs.first_seen_at
LIMIT $4 OFFSET $5
`

type ListFactsBySourceParams struct {
	SourceID pgtype.UUID `json:"source_id"`
	Column2  string      `json:"column_2"`
	Column3  string      `json:"column_3"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type ListFactsBySourceRow struct {
	ID            pgtype.UUID        `json:"id"`
	Text          string             `json:"text"`
	Status        string             `json:"status"`
	EmbeddedAt    pgtype.Timestamptz `json:"embedded_at"`
	EmbeddedModel *string            `json:"embedded_model"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	FactKind      string             `json:"fact_kind"`
	ImageUrl      *string            `json:"image_url"`
	SourceCount   int64              `json:"source_count"`
}

// Facts linked to a specific source, via the junction. Paginated
// and searchable. The optional status filter ($2) accepts ” (all).
// The optional search ($3) runs through websearch_to_tsquery against
// facts.search_tsv. Ordered by chunk_index then first_seen_at so the
// UI shows facts in extraction order within the source; LIMIT $4 /
// OFFSET $5 apply on top. Includes the computed source_count so a
// fact confirmed by other sources shows that cross-confirmation here
// too.
func (q *Queries) ListFactsBySource(ctx context.Context, arg ListFactsBySourceParams) ([]ListFactsBySourceRow, error) {
	rows, err := q.db.Query(ctx, listFactsBySource,
		arg.SourceID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFactsBySourceRow
	for rows.Next() {
		var i ListFactsBySourceRow
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Status,
			&i.EmbeddedAt,
			&i.EmbeddedModel,
			&i.CreatedAt,
			&i.FactKind,
			&i.ImageUrl,
			&i.SourceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactsForDedup = `-- name: ListFactsForDedup :many
SELECT f.id, f.text, f.status, f.embedded_at, f.embedded_model, f.created_at, f.search_tsv, f.image_url, f.fact_kind, f.promptset_hash FROM okt_repository.facts f
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
JOIN okt_repository.sources s ON fs.source_id = s.id
WHERE s.repository_id = $1
  AND f.status IN ('new', 'stable')
ORDER BY f.created_at
`

// All 'new' + 'stable' facts in the repository. The worker needs
// the fact row (id, text, status, created_at) to decide dedup
// ordering and to run nearest-neighbor searches.
func (q *Queries) ListFactsForDedup(ctx context.Context, repositoryID pgtype.UUID) ([]OktRepositoryFact, error) {
	rows, err := q.db.Query(ctx, listFactsForDedup, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktRepositoryFact
	for rows.Next() {
		var i OktRepositoryFact
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Status,
			&i.EmbeddedAt,
			&i.EmbeddedModel,
			&i.CreatedAt,
			&i.SearchTsv,
			&i.ImageUrl,
			&i.FactKind,
			&i.PromptsetHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactsToDelete = `-- name: ListFactsToDelete :many
SELECT f.id FROM okt_repository.facts f
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
JOIN okt_repository.sources s ON fs.source_id = s.id
WHERE s.repository_id = $1
  AND f.status = 'to_delete'
`

// status='to_delete' facts in the repository. The worker deletes
// them from Postgres and Qdrant. Returns the fact id only (the
// Qdrant point id is the fact UUID).
func (q *Queries) ListFactsToDelete(ctx context.Context, repositoryID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listFactsToDelete, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactsToDeleteBySource = `-- name: ListFactsToDeleteBySource :many
SELECT DISTINCT f.id FROM okt_repository.facts f
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
JOIN okt_repository.sources s ON fs.source_id = s.id
WHERE s.repository_id = $1
  AND fs.source_id = $2
  AND f.status = 'to_delete'
`

type ListFactsToDeleteBySourceParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	SourceID     pgtype.UUID `json:"source_id"`
}

// Source-scoped variant of ListFactsToDelete. After a cross-source
// dedup merge, the loser's fact_sources rows still point at its
// original sources (mergeSources adds the loser's sources to the
// winner, it does not remove them from the loser), so this query
// finds the to_delete facts whose original source was this one.
// DISTINCT because the fact_sources join may expand a fact with
// multiple sources; we only need the id once.
func (q *Queries) ListFactsToDeleteBySource(ctx context.Context, arg ListFactsToDeleteBySourceParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listFactsToDeleteBySource, arg.RepositoryID, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewFactsForSourceEmbedding = `-- name: ListNewFactsForSourceEmbedding :many
SELECT DISTINCT ON (f.id) f.id, f.text, f.status, f.embedded_at, f.embedded_model, f.created_at, f.search_tsv, f.image_url, f.fact_kind, f.promptset_hash
FROM okt_repository.facts f
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
JOIN okt_repository.sources s ON fs.source_id = s.id
WHERE s.repository_id = $1
  AND fs.source_id = $2
  AND f.status = 'new'
  AND f.embedded_at IS NULL
ORDER BY f.id
`

type ListNewFactsForSourceEmbeddingParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	SourceID     pgtype.UUID `json:"source_id"`
}

// All 'new' + embedded_at IS NULL facts for ONE source, scoped via
// the fact_sources + sources JOIN. No limit: a source's facts always
// complete in one embed pass so the dedup chain fires per source.
// One row per fact; a fact linked to this source multiple times is
// returned once (the JOIN can't expand it since fact_sources PK is
// (fact_id, source_id)). Uses SELECT f.* (not an explicit column
// list) so sqlc emits the row as store.OktRepositoryFact, which the
// embed worker passes to embedFacts without a type conversion.
func (q *Queries) ListNewFactsForSourceEmbedding(ctx context.Context, arg ListNewFactsForSourceEmbeddingParams) ([]OktRepositoryFact, error) {
	rows, err := q.db.Query(ctx, listNewFactsForSourceEmbedding, arg.RepositoryID, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktRepositoryFact
	for rows.Next() {
		var i OktRepositoryFact
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Status,
			&i.EmbeddedAt,
			&i.EmbeddedModel,
			&i.CreatedAt,
			&i.SearchTsv,
			&i.ImageUrl,
			&i.FactKind,
			&i.PromptsetHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedFactsByConceptGroups = `-- name: ListSharedFactsByConceptGroups :many
SELECT f.id, f.text, f.status, f.embedded_at, f.embedded_model, f.created_at,
       f.fact_kind, f.image_url,
       COALESCE(fs_count.source_count, 0) AS source_count,
       MIN(fs.source_id::text)::uuid AS source_id
FROM okt_repository.facts f
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
JOIN okt_repository.sources s ON fs.source_id = s.id
LEFT JOIN (
    SELECT fs2.fact_id, COUNT(*) AS source_count
    FROM okt_repository.fact_sources fs2
    JOIN okt_repository.sources s2 ON s2.id = fs2.source_id
    WHERE s2.repository_id = $1
    GROUP BY fs2.fact_id
) fs_count ON fs_count.fact_id = f.id
JOIN (
    -- Per-fact coverage: the distinct set of input group indices the
    -- fact is linked to (via fact_concepts). A fact qualifies for the
    -- intersection when its coverage count equals the total distinct
    -- group count in the input. The unnest WITH ORDINALITY pairs the
    -- parallel concept_id[] and group_idx[] arrays positionally.
    SELECT fc.fact_id, COUNT(DISTINCT g2.gv) AS covered_groups
    FROM okt_repository.fact_concepts fc,
         LATERAL unnest($4::uuid[]) WITH ORDINALITY AS c1(cid, c1_idx),
         LATERAL unnest($5::int4[]) WITH ORDINALITY AS g2(gv, g2_idx)
    WHERE c1.c1_idx = g2.g2_idx
      AND c1.cid = fc.concept_id
    GROUP BY fc.fact_id
) cov ON cov.fact_id = f.id
WHERE s.repository_id = $1
  AND ($2::text = '' OR f.status = $2)
  AND ($3::text = '' OR f.search_tsv @@ websearch_to_tsquery('english', $3))
  AND cov.covered_groups = (SELECT COUNT(DISTINCT g) FROM unnest($5::int4[]) AS t(g))
GROUP BY f.id, fs_count.source_count
ORDER BY
    CASE WHEN $6 = 'source_count' THEN COALESCE(fs_count.source_count, 0) END DESC NULLS LAST,
    f.created_at DESC
LIMIT $7 OFFSET $8
`

type ListSharedFactsByConceptGroupsParams struct {
	RepositoryID pgtype.UUID   `json:"repository_id"`
	Column2      string        `json:"column_2"`
	Column3      string        `json:"column_3"`
	Column4      []pgtype.UUID `json:"column_4"`
	Column5      []int32       `json:"column_5"`
	Column6      interface{}   `json:"column_6"`
	Limit        int32         `json:"limit"`
	Offset       int32         `json:"offset"`
}

type ListSharedFactsByConceptGroupsRow struct {
	ID            pgtype.UUID        `json:"id"`
	Text          string             `json:"text"`
	Status        string             `json:"status"`
	EmbeddedAt    pgtype.Timestamptz `json:"embedded_at"`
	EmbeddedModel *string            `json:"embedded_model"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	FactKind      string             `json:"fact_kind"`
	ImageUrl      *string            `json:"image_url"`
	SourceCount   int64              `json:"source_count"`
	SourceID      pgtype.UUID        `json:"source_id"`
}

// N-ary intersection: facts linked to ALL n input concept groups.
// The caller resolves each input concept (UUID or canonical name)
// into its group's concept_ids, flattens them into one uuid[] with a
// parallel int4[] tagging each concept_id's group index (0..n-1).
// A fact qualifies when the DISTINCT set of group indices linked to
// it (via fact_concepts) equals the DISTINCT set of group indices in
// the input — i.e. the fact is linked to at least one concept_id from
// EVERY group. COUNT(DISTINCT i.group_idx) dedupes a fact linked to
// multiple contexts of the same group. Same select list, status
// filter, search, and pagination shape as
// ListFactsByRepoWithSourceCountForConcept so the MCP searchFacts
// tool and the REST /facts endpoint can branch into this query
// without changing their output shape.
func (q *Queries) ListSharedFactsByConceptGroups(ctx context.Context, arg ListSharedFactsByConceptGroupsParams) ([]ListSharedFactsByConceptGroupsRow, error) {
	rows, err := q.db.Query(ctx, listSharedFactsByConceptGroups,
		arg.RepositoryID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSharedFactsByConceptGroupsRow
	for rows.Next() {
		var i ListSharedFactsByConceptGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Status,
			&i.EmbeddedAt,
			&i.EmbeddedModel,
			&i.CreatedAt,
			&i.FactKind,
			&i.ImageUrl,
			&i.SourceCount,
			&i.SourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFactEmbedded = `-- name: MarkFactEmbedded :one
UPDATE okt_repository.facts
SET embedded_at = now(),
    embedded_model = $2
WHERE id = $1
RETURNING id, text, status, embedded_at, embedded_model, created_at, search_tsv, image_url, fact_kind, promptset_hash
`

type MarkFactEmbeddedParams struct {
	ID            pgtype.UUID `json:"id"`
	EmbeddedModel *string     `json:"embedded_model"`
}

func (q *Queries) MarkFactEmbedded(ctx context.Context, arg MarkFactEmbeddedParams) (OktRepositoryFact, error) {
	row := q.db.QueryRow(ctx, markFactEmbedded, arg.ID, arg.EmbeddedModel)
	var i OktRepositoryFact
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Status,
		&i.EmbeddedAt,
		&i.EmbeddedModel,
		&i.CreatedAt,
		&i.SearchTsv,
		&i.ImageUrl,
		&i.FactKind,
		&i.PromptsetHash,
	)
	return i, err
}

const markFactStatus = `-- name: MarkFactStatus :one
UPDATE okt_repository.facts
SET status = $2
WHERE id = $1
RETURNING id, text, status, embedded_at, embedded_model, created_at, search_tsv, image_url, fact_kind, promptset_hash
`

type MarkFactStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) MarkFactStatus(ctx context.Context, arg MarkFactStatusParams) (OktRepositoryFact, error) {
	row := q.db.QueryRow(ctx, markFactStatus, arg.ID, arg.Status)
	var i OktRepositoryFact
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Status,
		&i.EmbeddedAt,
		&i.EmbeddedModel,
		&i.CreatedAt,
		&i.SearchTsv,
		&i.ImageUrl,
		&i.FactKind,
		&i.PromptsetHash,
	)
	return i, err
}

const markFactsStableByRepo = `-- name: MarkFactsStableByRepo :exec
UPDATE okt_repository.facts f
SET status = 'stable'
WHERE f.status = 'new'
  AND EXISTS (
      SELECT 1 FROM okt_repository.fact_sources fs
      JOIN okt_repository.sources s ON fs.source_id = s.id
      WHERE fs.fact_id = f.id AND s.repository_id = $1
  )
`

// Promote surviving 'new' facts in a repository to 'stable'.
// Repository filter goes through fact_sources + sources so the
// query works the same on a shared (filtered) and an isolated
// (physically separate) database.
func (q *Queries) MarkFactsStableByRepo(ctx context.Context, repositoryID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markFactsStableByRepo, repositoryID)
	return err
}

const markSourceProcessed = `-- name: MarkSourceProcessed :one
UPDATE okt_repository.sources
SET status = 'processed',
    processed_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, repository_id, url, kind, status, created_at, updated_at, content, fetched_at, error, doi, parsed_title, parsed_text, parsed_html, parsed_author, parsed_sitename, parsed_language, parsed_at, parse_status, published_at, processed_at, search_tsv, storage_key, content_type, local_path, stored_at, fetch_attempts, oa_status, parsed_markdown, sentence_offsets, chunk_failures, chunk_errors, last_chunk_failure_at, concept_skip_count
`

func (q *Queries) MarkSourceProcessed(ctx context.Context, id pgtype.UUID) (OktRepositorySource, error) {
	row := q.db.QueryRow(ctx, markSourceProcessed, id)
	var i OktRepositorySource
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Url,
		&i.Kind,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Content,
		&i.FetchedAt,
		&i.Error,
		&i.Doi,
		&i.ParsedTitle,
		&i.ParsedText,
		&i.ParsedHtml,
		&i.ParsedAuthor,
		&i.ParsedSitename,
		&i.ParsedLanguage,
		&i.ParsedAt,
		&i.ParseStatus,
		&i.PublishedAt,
		&i.ProcessedAt,
		&i.SearchTsv,
		&i.StorageKey,
		&i.ContentType,
		&i.LocalPath,
		&i.StoredAt,
		&i.FetchAttempts,
		&i.OaStatus,
		&i.ParsedMarkdown,
		&i.SentenceOffsets,
		&i.ChunkFailures,
		&i.ChunkErrors,
		&i.LastChunkFailureAt,
		&i.ConceptSkipCount,
	)
	return i, err
}

const relinkFactReferences = `-- name: RelinkFactReferences :exec
UPDATE okt_repository.fact_references
SET fact_id = $2
WHERE fact_id = $1
`

type RelinkFactReferencesParams struct {
	FactID   pgtype.UUID `json:"fact_id"`
	FactID_2 pgtype.UUID `json:"fact_id_2"`
}

// Move all of a loser fact's citation rows onto the survivor. Run
// after DeleteDuplicateFactReferences so no PK collision remains.
// Non-overlapping citations from both facts are preserved, which is
// the dedup-preserves-all-references guarantee.
func (q *Queries) RelinkFactReferences(ctx context.Context, arg RelinkFactReferencesParams) error {
	_, err := q.db.Exec(ctx, relinkFactReferences, arg.FactID, arg.FactID_2)
	return err
}

const resetFactEmbeddingForReembed = `-- name: ResetFactEmbeddingForReembed :exec
UPDATE okt_repository.facts
SET embedded_at = NULL,
    embedded_model = NULL
WHERE id = ANY($1::uuid[])
`

// Clear embedded_at + embedded_model on a set of facts so the
// embed_facts worker (which filters embedded_at IS NULL) re-embeds
// them with the local model. Used by the CacheReconciler when an
// imported decomposition's embedding model differs from the local
// embedding config. The Qdrant points for these facts are deleted
// separately by the caller (now possible because Qdrant uses local
// fact UUIDs, not remote registry UUIDs).
func (q *Queries) ResetFactEmbeddingForReembed(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetFactEmbeddingForReembed, dollar_1)
	return err
}

const searchFactsByNumericTokens = `-- name: SearchFactsByNumericTokens :many
SELECT DISTINCT ON (f.id) f.id, f.text, f.status, f.embedded_at, f.embedded_model, f.created_at, f.search_tsv, f.image_url, f.fact_kind, f.promptset_hash
FROM okt_repository.facts f
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
JOIN okt_repository.sources s ON fs.source_id = s.id
WHERE s.repository_id = $1
  AND f.search_tsv @@ to_tsquery('english', $2)
  AND ($3::uuid[] = '{}' OR NOT (f.id = ANY($3::uuid[])))
ORDER BY f.id
LIMIT $4
`

type SearchFactsByNumericTokensParams struct {
	RepositoryID pgtype.UUID   `json:"repository_id"`
	Tsquery      string        `json:"tsquery"`
	ExcludeIds   []pgtype.UUID `json:"exclude_ids"`
	RowLimit     int32         `json:"row_limit"`
}

// Hybrid-retrieval lexical fallback for the annotate_report worker.
// Given a repository_id and a tsquery string (e.g. '508 & 0.9 & kg')
// built by the caller from numeric tokens extracted from a report
// sentence, returns up to `limit` facts in that repository whose
// search_tsv matches the query (plain tsquery AND semantics). Reuses
// the existing search_tsv generated column + idx_facts_search_tsv
// GIN index added by migration 0015 (the 'english' config indexes
// numbers and short unit tokens verbatim — only long prose words are
// stemmed, which is fine because the lexical fallback is for exact
// numeric/unit matches, not prose synonyms). The caller unions these
// lexical hits with the Qdrant semantic hits, dedupes by fact_id,
// and feeds the combined set to the posture classifier.
//
// Scoping: the facts table is per-repo on isolated databases and
// interleaved on shared databases; the JOIN through fact_sources +
// sources filters by repository_id in both layouts (mirrors
// ListFactsForDedup). Excluded fact ids ($3) lets the caller skip
// facts the Qdrant pass already surfaced (avoids double-counting).
func (q *Queries) SearchFactsByNumericTokens(ctx context.Context, arg SearchFactsByNumericTokensParams) ([]OktRepositoryFact, error) {
	rows, err := q.db.Query(ctx, searchFactsByNumericTokens,
		arg.RepositoryID,
		arg.Tsquery,
		arg.ExcludeIds,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktRepositoryFact
	for rows.Next() {
		var i OktRepositoryFact
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Status,
			&i.EmbeddedAt,
			&i.EmbeddedModel,
			&i.CreatedAt,
			&i.SearchTsv,
			&i.ImageUrl,
			&i.FactKind,
			&i.PromptsetHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSentenceOffsets = `-- name: SetSentenceOffsets :exec

UPDATE okt_repository.sources
SET sentence_offsets = $2
WHERE id = $1
`

type SetSentenceOffsetsParams struct {
	ID              pgtype.UUID `json:"id"`
	SentenceOffsets []int32     `json:"sentence_offsets"`
}

// ---------------------------------------------------------------------------
// Sentence-level fact references (migration 0022).
// ---------------------------------------------------------------------------
// Persist the deterministic global sentence array as a flat
// [start0, end0, start1, end1, ...] rune-offset array. Written once
// by retrieve_source after parsing; read by source_decomposition to
// build labeled chunk text and by the API to serve the UI.
func (q *Queries) SetSentenceOffsets(ctx context.Context, arg SetSentenceOffsetsParams) error {
	_, err := q.db.Exec(ctx, setSentenceOffsets, arg.ID, arg.SentenceOffsets)
	return err
}
