// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: graph_export.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAllConceptAliasesForExport = `-- name: ListAllConceptAliasesForExport :many
SELECT ca.concept_id, ca.alias_text
FROM okt_repository.concept_aliases ca
JOIN okt_repository.concepts c ON ca.concept_id = c.id
WHERE c.repository_id = $1
ORDER BY ca.concept_id, ca.alias_text
`

type ListAllConceptAliasesForExportRow struct {
	ConceptID pgtype.UUID `json:"concept_id"`
	AliasText string      `json:"alias_text"`
}

// Every alias for the repo's concepts. Ordered by concept_id, alias_text
// for stable bundle output.
func (q *Queries) ListAllConceptAliasesForExport(ctx context.Context, repositoryID pgtype.UUID) ([]ListAllConceptAliasesForExportRow, error) {
	rows, err := q.db.Query(ctx, listAllConceptAliasesForExport, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllConceptAliasesForExportRow
	for rows.Next() {
		var i ListAllConceptAliasesForExportRow
		if err := rows.Scan(&i.ConceptID, &i.AliasText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllConceptIDsForExport = `-- name: ListAllConceptIDsForExport :many
SELECT id
FROM okt_repository.concepts
WHERE repository_id = $1
ORDER BY id
`

// The concept_ids for the repo (for the Qdrant concept vector fetch).
func (q *Queries) ListAllConceptIDsForExport(ctx context.Context, repositoryID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAllConceptIDsForExport, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllConceptsForExport = `-- name: ListAllConceptsForExport :many
SELECT id, canonical_name, context, description, promptset_hash
FROM okt_repository.concepts
WHERE repository_id = $1
ORDER BY id
`

type ListAllConceptsForExportRow struct {
	ID            pgtype.UUID `json:"id"`
	CanonicalName string      `json:"canonical_name"`
	Context       string      `json:"context"`
	Description   *string     `json:"description"`
	PromptsetHash *string     `json:"promptset_hash"`
}

// Every concept row for a repository. promptset_hash tags the
// concept with the philosophy that produced it. Ordered by id for
// stable idx assignment.
func (q *Queries) ListAllConceptsForExport(ctx context.Context, repositoryID pgtype.UUID) ([]ListAllConceptsForExportRow, error) {
	rows, err := q.db.Query(ctx, listAllConceptsForExport, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllConceptsForExportRow
	for rows.Next() {
		var i ListAllConceptsForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalName,
			&i.Context,
			&i.Description,
			&i.PromptsetHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllFactConceptsForExport = `-- name: ListAllFactConceptsForExport :many
SELECT fc.fact_id, fc.concept_id, fc.promptset_hash
FROM okt_repository.fact_concepts fc
JOIN okt_repository.concepts c ON fc.concept_id = c.id
WHERE c.repository_id = $1
ORDER BY fc.fact_id, fc.concept_id
`

type ListAllFactConceptsForExportRow struct {
	FactID        pgtype.UUID `json:"fact_id"`
	ConceptID     pgtype.UUID `json:"concept_id"`
	PromptsetHash *string     `json:"promptset_hash"`
}

// The fact↔concept junction, scoped to the repo's concepts. promptset_hash
// tags the link with the philosophy that produced the fact+concept pair.
// Ordered by fact_id, concept_id for stable bundle output.
func (q *Queries) ListAllFactConceptsForExport(ctx context.Context, repositoryID pgtype.UUID) ([]ListAllFactConceptsForExportRow, error) {
	rows, err := q.db.Query(ctx, listAllFactConceptsForExport, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllFactConceptsForExportRow
	for rows.Next() {
		var i ListAllFactConceptsForExportRow
		if err := rows.Scan(&i.FactID, &i.ConceptID, &i.PromptsetHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllFactIDsForExport = `-- name: ListAllFactIDsForExport :many
SELECT DISTINCT ON (f.id) f.id
FROM okt_repository.facts f
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
JOIN okt_repository.sources s ON fs.source_id = s.id
WHERE s.repository_id = $1
ORDER BY f.id
`

// The fact_ids for the repo (for the Qdrant vector fetch). Returns
// bare ids so the export task can batch them into GetFactVectorsByIDs.
func (q *Queries) ListAllFactIDsForExport(ctx context.Context, repositoryID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAllFactIDsForExport, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllFactSourcesForExport = `-- name: ListAllFactSourcesForExport :many
SELECT fs.fact_id, fs.source_id, fs.chunk_index
FROM okt_repository.fact_sources fs
JOIN okt_repository.sources s ON fs.source_id = s.id
WHERE s.repository_id = $1
ORDER BY fs.fact_id, fs.source_id
`

type ListAllFactSourcesForExportRow struct {
	FactID     pgtype.UUID `json:"fact_id"`
	SourceID   pgtype.UUID `json:"source_id"`
	ChunkIndex int32       `json:"chunk_index"`
}

// The fact↔source junction, scoped to the repo's facts. Used to
// rebuild fact_sources on import. chunk_index is per-extraction.
// Ordered by fact_id, source_id for stable bundle output.
func (q *Queries) ListAllFactSourcesForExport(ctx context.Context, repositoryID pgtype.UUID) ([]ListAllFactSourcesForExportRow, error) {
	rows, err := q.db.Query(ctx, listAllFactSourcesForExport, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllFactSourcesForExportRow
	for rows.Next() {
		var i ListAllFactSourcesForExportRow
		if err := rows.Scan(&i.FactID, &i.SourceID, &i.ChunkIndex); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllFactsForExport = `-- name: ListAllFactsForExport :many
SELECT DISTINCT ON (f.id) f.id, f.text, f.fact_kind, f.image_url,
       f.status, f.promptset_hash
FROM okt_repository.facts f
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
JOIN okt_repository.sources s ON fs.source_id = s.id
WHERE s.repository_id = $1
ORDER BY f.id
`

type ListAllFactsForExportRow struct {
	ID            pgtype.UUID `json:"id"`
	Text          string      `json:"text"`
	FactKind      string      `json:"fact_kind"`
	ImageUrl      *string     `json:"image_url"`
	Status        string      `json:"status"`
	PromptsetHash *string     `json:"promptset_hash"`
}

// Every fact reachable from the repo's sources, with its source
// links. A fact is repo-scoped via fact_sources → sources (facts has
// no repository_id column — see 0013_facts.up.sql). DISTINCT because
// a fact with multiple source links would otherwise appear once per
// source. content_hash is the dedup key the import path uses to
// merge facts into an existing repo. promptset_hash tags the fact
// with the philosophy that produced it. Ordered by id for stable idx.
func (q *Queries) ListAllFactsForExport(ctx context.Context, repositoryID pgtype.UUID) ([]ListAllFactsForExportRow, error) {
	rows, err := q.db.Query(ctx, listAllFactsForExport, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllFactsForExportRow
	for rows.Next() {
		var i ListAllFactsForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.FactKind,
			&i.ImageUrl,
			&i.Status,
			&i.PromptsetHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllInvestigationSourcesForExport = `-- name: ListAllInvestigationSourcesForExport :many
SELECT is_join.investigation_id, is_join.source_id
FROM okt_repository.investigation_sources is_join
JOIN okt_repository.investigations i ON is_join.investigation_id = i.id
WHERE i.repository_id = $1
ORDER BY is_join.investigation_id, is_join.source_id
`

type ListAllInvestigationSourcesForExportRow struct {
	InvestigationID pgtype.UUID `json:"investigation_id"`
	SourceID        pgtype.UUID `json:"source_id"`
}

// The investigation↔source junction, scoped to the repo's
// investigations. Ordered by investigation_id, source_id for stable
// bundle output.
func (q *Queries) ListAllInvestigationSourcesForExport(ctx context.Context, repositoryID pgtype.UUID) ([]ListAllInvestigationSourcesForExportRow, error) {
	rows, err := q.db.Query(ctx, listAllInvestigationSourcesForExport, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllInvestigationSourcesForExportRow
	for rows.Next() {
		var i ListAllInvestigationSourcesForExportRow
		if err := rows.Scan(&i.InvestigationID, &i.SourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllInvestigationsForExport = `-- name: ListAllInvestigationsForExport :many
SELECT id, title, topic
FROM okt_repository.investigations
WHERE repository_id = $1
ORDER BY id
`

type ListAllInvestigationsForExportRow struct {
	ID    pgtype.UUID `json:"id"`
	Title string      `json:"title"`
	Topic *string     `json:"topic"`
}

// Every investigation for a repository. Ordered by id for stable idx.
func (q *Queries) ListAllInvestigationsForExport(ctx context.Context, repositoryID pgtype.UUID) ([]ListAllInvestigationsForExportRow, error) {
	rows, err := q.db.Query(ctx, listAllInvestigationsForExport, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllInvestigationsForExportRow
	for rows.Next() {
		var i ListAllInvestigationsForExportRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Topic); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllReportAnnotationsForExport = `-- name: ListAllReportAnnotationsForExport :many
SELECT ra.report_id, ra.sentence_index, ra.sentence_text, ra.fact_id,
       ra.score, ra.posture
FROM okt_repository.report_annotations ra
JOIN okt_repository.reports r ON ra.report_id = r.id
WHERE r.repository_id = $1
ORDER BY ra.report_id, ra.sentence_index, ra.fact_id
`

type ListAllReportAnnotationsForExportRow struct {
	ReportID      pgtype.UUID `json:"report_id"`
	SentenceIndex int32       `json:"sentence_index"`
	SentenceText  string      `json:"sentence_text"`
	FactID        pgtype.UUID `json:"fact_id"`
	Score         float64     `json:"score"`
	Posture       *string     `json:"posture"`
}

// Every report_annotation for the repo's reports. posture is the
// autocite classifier label (NULL on legacy/fallback rows). The
// import path remaps fact_id to the fresh local UUID. Ordered by
// report_id, sentence_index, fact_id for stable bundle output.
func (q *Queries) ListAllReportAnnotationsForExport(ctx context.Context, repositoryID pgtype.UUID) ([]ListAllReportAnnotationsForExportRow, error) {
	rows, err := q.db.Query(ctx, listAllReportAnnotationsForExport, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllReportAnnotationsForExportRow
	for rows.Next() {
		var i ListAllReportAnnotationsForExportRow
		if err := rows.Scan(
			&i.ReportID,
			&i.SentenceIndex,
			&i.SentenceText,
			&i.FactID,
			&i.Score,
			&i.Posture,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllReportsForExport = `-- name: ListAllReportsForExport :many
SELECT id, title, topic, body_md, status, parent_id,
       similarity_threshold, embedded_model, sentence_count
FROM okt_repository.reports
WHERE repository_id = $1
ORDER BY id
`

type ListAllReportsForExportRow struct {
	ID                  pgtype.UUID `json:"id"`
	Title               string      `json:"title"`
	Topic               *string     `json:"topic"`
	BodyMd              string      `json:"body_md"`
	Status              string      `json:"status"`
	ParentID            pgtype.UUID `json:"parent_id"`
	SimilarityThreshold *float64    `json:"similarity_threshold"`
	EmbeddedModel       *string     `json:"embedded_model"`
	SentenceCount       *int32      `json:"sentence_count"`
}

// Every report for a repository, including the parent_id nesting
// (migration 0043). Ordered by id for stable idx assignment.
func (q *Queries) ListAllReportsForExport(ctx context.Context, repositoryID pgtype.UUID) ([]ListAllReportsForExportRow, error) {
	rows, err := q.db.Query(ctx, listAllReportsForExport, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllReportsForExportRow
	for rows.Next() {
		var i ListAllReportsForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Topic,
			&i.BodyMd,
			&i.Status,
			&i.ParentID,
			&i.SimilarityThreshold,
			&i.EmbeddedModel,
			&i.SentenceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSourcesForExport = `-- name: ListAllSourcesForExport :many

SELECT id, url, doi, kind, status, parsed_title, parsed_text,
       parsed_markdown, published_at
FROM okt_repository.sources
WHERE repository_id = $1
ORDER BY id
`

type ListAllSourcesForExportRow struct {
	ID             pgtype.UUID `json:"id"`
	Url            string      `json:"url"`
	Doi            *string     `json:"doi"`
	Kind           string      `json:"kind"`
	Status         string      `json:"status"`
	ParsedTitle    *string     `json:"parsed_title"`
	ParsedText     *string     `json:"parsed_text"`
	ParsedMarkdown *string     `json:"parsed_markdown"`
	PublishedAt    pgtype.Date `json:"published_at"`
}

// graph_export.sql — whole-repository graph export queries.
//
// A graph bundle is the serializable form of an entire repository's
// derived layer: sources + facts + concepts + summaries + syntheses +
// investigations + reports + embeddings. These queries read every
// entity for a repository so the export task (tasks/export_graph.go)
// can assemble a GraphBundle JSON document, gzip it, and push it to
// the shared knowledge registry. The import task
// (tasks/import_graph.go) is the inverse: it reads a bundle and
// re-inserts every entity into a fresh (or existing) repository.
//
// All queries are repo-scoped via repository_id. The export task
// resolves the per-repo pool and builds a *store.Queries from it,
// the same way the per-repo chi middleware does. On a shared (tier-1)
// database the rows for every repo are interleaved and filtered by
// repository_id; on an isolated (tier-2/3) database only one repo's
// rows are physically present.
// Every source row for a repository, including the parsed
// text/markdown the import path re-persists so the importing repo
// doesn't need to re-fetch the URL. Ordered by id for a stable idx
// assignment in the export builder. (sha256 is computed in Go from
// the parsed content at bundle-assembly time, not stored on the
// sources row — the column is registry-side only.)
func (q *Queries) ListAllSourcesForExport(ctx context.Context, repositoryID pgtype.UUID) ([]ListAllSourcesForExportRow, error) {
	rows, err := q.db.Query(ctx, listAllSourcesForExport, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllSourcesForExportRow
	for rows.Next() {
		var i ListAllSourcesForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Doi,
			&i.Kind,
			&i.Status,
			&i.ParsedTitle,
			&i.ParsedText,
			&i.ParsedMarkdown,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSummariesForExport = `-- name: ListAllSummariesForExport :many
SELECT cs.id, cs.concept_id, cs.context, cs.sequence_num, cs.is_complete,
       cs.fact_count, cs.content, cs.covered_fact_ids, cs.model
FROM okt_repository.concept_summaries cs
JOIN okt_repository.concepts c ON cs.concept_id = c.id
WHERE c.repository_id = $1
ORDER BY cs.concept_id, cs.sequence_num
`

type ListAllSummariesForExportRow struct {
	ID             pgtype.UUID   `json:"id"`
	ConceptID      pgtype.UUID   `json:"concept_id"`
	Context        string        `json:"context"`
	SequenceNum    int32         `json:"sequence_num"`
	IsComplete     bool          `json:"is_complete"`
	FactCount      int32         `json:"fact_count"`
	Content        string        `json:"content"`
	CoveredFactIds []pgtype.UUID `json:"covered_fact_ids"`
	Model          *string       `json:"model"`
}

// Every concept_summary slice for the repo's concepts. covered_fact_ids
// is the array of fact_ids the slice folds in; the import path remaps
// them to fresh local UUIDs. Ordered by concept_id, sequence_num for
// stable bundle output.
func (q *Queries) ListAllSummariesForExport(ctx context.Context, repositoryID pgtype.UUID) ([]ListAllSummariesForExportRow, error) {
	rows, err := q.db.Query(ctx, listAllSummariesForExport, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllSummariesForExportRow
	for rows.Next() {
		var i ListAllSummariesForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.ConceptID,
			&i.Context,
			&i.SequenceNum,
			&i.IsComplete,
			&i.FactCount,
			&i.Content,
			&i.CoveredFactIds,
			&i.Model,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSynthesesForExport = `-- name: ListAllSynthesesForExport :many
SELECT id, canonical_name, content, covered_summary_ids,
       covered_concept_ids, embedded_image_ids, model
FROM okt_repository.concept_syntheses
WHERE repository_id = $1
ORDER BY canonical_name
`

type ListAllSynthesesForExportRow struct {
	ID                pgtype.UUID   `json:"id"`
	CanonicalName     string        `json:"canonical_name"`
	Content           string        `json:"content"`
	CoveredSummaryIds []pgtype.UUID `json:"covered_summary_ids"`
	CoveredConceptIds []pgtype.UUID `json:"covered_concept_ids"`
	EmbeddedImageIds  []pgtype.UUID `json:"embedded_image_ids"`
	Model             *string       `json:"model"`
}

// Every concept_synthesis for the repo. canonical_name is the group
// key (one synthesis per lower(canonical_name) per repo). The import
// path upserts via UpsertSynthesis (ON CONFLICT on the unique index).
// Ordered by canonical_name for stable bundle output.
func (q *Queries) ListAllSynthesesForExport(ctx context.Context, repositoryID pgtype.UUID) ([]ListAllSynthesesForExportRow, error) {
	rows, err := q.db.Query(ctx, listAllSynthesesForExport, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllSynthesesForExportRow
	for rows.Next() {
		var i ListAllSynthesesForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalName,
			&i.Content,
			&i.CoveredSummaryIds,
			&i.CoveredConceptIds,
			&i.EmbeddedImageIds,
			&i.Model,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
