// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: investigations.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addInvestigationSource = `-- name: AddInvestigationSource :exec
INSERT INTO okt_repository.investigation_sources (investigation_id, source_id)
VALUES ($1, $2)
ON CONFLICT (investigation_id, source_id) DO NOTHING
`

type AddInvestigationSourceParams struct {
	InvestigationID pgtype.UUID `json:"investigation_id"`
	SourceID        pgtype.UUID `json:"source_id"`
}

// Idempotent: re-adding a source to the same investigation is a
// no-op. ON CONFLICT preserves the original added_at.
func (q *Queries) AddInvestigationSource(ctx context.Context, arg AddInvestigationSourceParams) error {
	_, err := q.db.Exec(ctx, addInvestigationSource, arg.InvestigationID, arg.SourceID)
	return err
}

const countInvestigationFacts = `-- name: CountInvestigationFacts :one
SELECT COUNT(DISTINCT f.id)
FROM okt_repository.facts f
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
JOIN okt_repository.investigation_sources is_join ON is_join.source_id = fs.source_id
WHERE is_join.investigation_id = $1
  AND ($2::text = '' OR f.status = $2)
  AND ($3::text = '' OR f.search_tsv @@ websearch_to_tsquery('english', $3))
`

type CountInvestigationFactsParams struct {
	InvestigationID pgtype.UUID `json:"investigation_id"`
	Column2         string      `json:"column_2"`
	Column3         string      `json:"column_3"`
}

// Companion count for ListInvestigationFacts. Counts DISTINCT facts
// contributed by the investigation's sources and matching the
// status/search filters.
func (q *Queries) CountInvestigationFacts(ctx context.Context, arg CountInvestigationFactsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInvestigationFacts, arg.InvestigationID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInvestigationSources = `-- name: CountInvestigationSources :one
SELECT COUNT(*) FROM okt_repository.investigation_sources is_join
JOIN okt_repository.sources s ON s.id = is_join.source_id
WHERE is_join.investigation_id = $1
  AND ($2::text = '' OR s.search_tsv @@ websearch_to_tsquery('english', $2))
`

type CountInvestigationSourcesParams struct {
	InvestigationID pgtype.UUID `json:"investigation_id"`
	Column2         string      `json:"column_2"`
}

func (q *Queries) CountInvestigationSources(ctx context.Context, arg CountInvestigationSourcesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInvestigationSources, arg.InvestigationID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInvestigationsByRepo = `-- name: CountInvestigationsByRepo :one
SELECT COUNT(*) FROM okt_repository.investigations
WHERE repository_id = $1
  AND ($2::text = '' OR title ILIKE '%' || $2 || '%' OR topic ILIKE '%' || $2 || '%')
`

type CountInvestigationsByRepoParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Column2      string      `json:"column_2"`
}

func (q *Queries) CountInvestigationsByRepo(ctx context.Context, arg CountInvestigationsByRepoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInvestigationsByRepo, arg.RepositoryID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvestigation = `-- name: CreateInvestigation :one
INSERT INTO okt_repository.investigations (id, repository_id, title, topic)
VALUES ($1, $2, $3, $4)
RETURNING id, repository_id, title, topic, created_at, updated_at
`

type CreateInvestigationParams struct {
	ID           pgtype.UUID `json:"id"`
	RepositoryID pgtype.UUID `json:"repository_id"`
	Title        string      `json:"title"`
	Topic        *string     `json:"topic"`
}

func (q *Queries) CreateInvestigation(ctx context.Context, arg CreateInvestigationParams) (OktRepositoryInvestigation, error) {
	row := q.db.QueryRow(ctx, createInvestigation,
		arg.ID,
		arg.RepositoryID,
		arg.Title,
		arg.Topic,
	)
	var i OktRepositoryInvestigation
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Title,
		&i.Topic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInvestigation = `-- name: DeleteInvestigation :exec
DELETE FROM okt_repository.investigations WHERE id = $1
`

func (q *Queries) DeleteInvestigation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvestigation, id)
	return err
}

const getInvestigationByID = `-- name: GetInvestigationByID :one
SELECT id, repository_id, title, topic, created_at, updated_at FROM okt_repository.investigations WHERE id = $1
`

func (q *Queries) GetInvestigationByID(ctx context.Context, id pgtype.UUID) (OktRepositoryInvestigation, error) {
	row := q.db.QueryRow(ctx, getInvestigationByID, id)
	var i OktRepositoryInvestigation
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Title,
		&i.Topic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvestigationFacts = `-- name: ListInvestigationFacts :many
SELECT f.id, f.text, f.status, f.embedded_at, f.embedded_model, f.created_at,
       f.fact_kind, f.image_url,
       COALESCE(fs_count.source_count, 0) AS source_count
FROM okt_repository.facts f
JOIN okt_repository.fact_sources fs ON fs.fact_id = f.id
JOIN okt_repository.investigation_sources is_join ON is_join.source_id = fs.source_id
LEFT JOIN (
    SELECT fact_id, COUNT(*) AS source_count
    FROM okt_repository.fact_sources
    GROUP BY fact_id
) fs_count ON fs_count.fact_id = f.id
WHERE is_join.investigation_id = $1
  AND ($2::text = '' OR f.status = $2)
  AND ($3::text = '' OR f.search_tsv @@ websearch_to_tsquery('english', $3))
GROUP BY f.id, fs_count.source_count
ORDER BY
    CASE WHEN $4 = 'source_count' THEN fs_count.source_count END DESC NULLS LAST,
    f.created_at DESC
LIMIT $5 OFFSET $6
`

type ListInvestigationFactsParams struct {
	InvestigationID pgtype.UUID `json:"investigation_id"`
	Column2         string      `json:"column_2"`
	Column3         string      `json:"column_3"`
	Column4         interface{} `json:"column_4"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
}

type ListInvestigationFactsRow struct {
	ID            pgtype.UUID        `json:"id"`
	Text          string             `json:"text"`
	Status        string             `json:"status"`
	EmbeddedAt    pgtype.Timestamptz `json:"embedded_at"`
	EmbeddedModel *string            `json:"embedded_model"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	FactKind      string             `json:"fact_kind"`
	ImageUrl      *string            `json:"image_url"`
	SourceCount   int64              `json:"source_count"`
}

// Facts contributed by the investigation's sources, via
// fact_sources → investigation_sources. Deduped by fact_id (a fact
// confirmed by N of the investigation's sources is returned once)
// with a computed source_count over ALL sources in the repo (not
// just the investigation's) so cross-confirmation still shows.
// Paginated, searchable, and sortable, mirroring the repo-level
// fact list. The status filter accepts ” (all), 'stable', 'new',
// 'to_delete'. The sort accepts 'created_at' (default) or
// 'source_count'.
func (q *Queries) ListInvestigationFacts(ctx context.Context, arg ListInvestigationFactsParams) ([]ListInvestigationFactsRow, error) {
	rows, err := q.db.Query(ctx, listInvestigationFacts,
		arg.InvestigationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvestigationFactsRow
	for rows.Next() {
		var i ListInvestigationFactsRow
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Status,
			&i.EmbeddedAt,
			&i.EmbeddedModel,
			&i.CreatedAt,
			&i.FactKind,
			&i.ImageUrl,
			&i.SourceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestigationSources = `-- name: ListInvestigationSources :many
SELECT s.id, s.repository_id, s.url, s.kind, s.status, s.created_at, s.updated_at, s.content, s.fetched_at, s.error, s.doi, s.parsed_title, s.parsed_text, s.parsed_html, s.parsed_author, s.parsed_sitename, s.parsed_language, s.parsed_at, s.parse_status, s.published_at, s.processed_at, s.search_tsv, s.storage_key, s.content_type, s.local_path, s.stored_at, s.fetch_attempts, s.oa_status, s.parsed_markdown, s.sentence_offsets, s.chunk_failures, s.chunk_errors, s.last_chunk_failure_at, s.concept_skip_count,
       is_join.added_at
FROM okt_repository.investigation_sources is_join
JOIN okt_repository.sources s ON s.id = is_join.source_id
WHERE is_join.investigation_id = $1
  AND ($2::text = '' OR s.search_tsv @@ websearch_to_tsquery('english', $2))
ORDER BY is_join.added_at DESC
LIMIT $3 OFFSET $4
`

type ListInvestigationSourcesParams struct {
	InvestigationID pgtype.UUID `json:"investigation_id"`
	Column2         string      `json:"column_2"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
}

type ListInvestigationSourcesRow struct {
	ID                 pgtype.UUID        `json:"id"`
	RepositoryID       pgtype.UUID        `json:"repository_id"`
	Url                string             `json:"url"`
	Kind               string             `json:"kind"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Content            []byte             `json:"content"`
	FetchedAt          pgtype.Timestamptz `json:"fetched_at"`
	Error              *string            `json:"error"`
	Doi                *string            `json:"doi"`
	ParsedTitle        *string            `json:"parsed_title"`
	ParsedText         *string            `json:"parsed_text"`
	ParsedHtml         *string            `json:"parsed_html"`
	ParsedAuthor       *string            `json:"parsed_author"`
	ParsedSitename     *string            `json:"parsed_sitename"`
	ParsedLanguage     *string            `json:"parsed_language"`
	ParsedAt           pgtype.Timestamptz `json:"parsed_at"`
	ParseStatus        *string            `json:"parse_status"`
	PublishedAt        pgtype.Date        `json:"published_at"`
	ProcessedAt        pgtype.Timestamptz `json:"processed_at"`
	SearchTsv          interface{}        `json:"search_tsv"`
	StorageKey         *string            `json:"storage_key"`
	ContentType        *string            `json:"content_type"`
	LocalPath          *string            `json:"local_path"`
	StoredAt           pgtype.Timestamptz `json:"stored_at"`
	FetchAttempts      []byte             `json:"fetch_attempts"`
	OaStatus           *string            `json:"oa_status"`
	ParsedMarkdown     *string            `json:"parsed_markdown"`
	SentenceOffsets    []int32            `json:"sentence_offsets"`
	ChunkFailures      int32              `json:"chunk_failures"`
	ChunkErrors        []byte             `json:"chunk_errors"`
	LastChunkFailureAt pgtype.Timestamptz `json:"last_chunk_failure_at"`
	ConceptSkipCount   int32              `json:"concept_skip_count"`
	AddedAt            pgtype.Timestamptz `json:"added_at"`
}

// The investigation's source rows, joined from the junction.
// Paginated and searchable against the source's search_tsv (url +
// parsed_title + doi) so the Sources phase mirrors the repo-level
// source list's search behavior. Ordered by added_at DESC so the
// most recently added sources surface first; LIMIT/OFFSET on top.
func (q *Queries) ListInvestigationSources(ctx context.Context, arg ListInvestigationSourcesParams) ([]ListInvestigationSourcesRow, error) {
	rows, err := q.db.Query(ctx, listInvestigationSources,
		arg.InvestigationID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvestigationSourcesRow
	for rows.Next() {
		var i ListInvestigationSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Url,
			&i.Kind,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Content,
			&i.FetchedAt,
			&i.Error,
			&i.Doi,
			&i.ParsedTitle,
			&i.ParsedText,
			&i.ParsedHtml,
			&i.ParsedAuthor,
			&i.ParsedSitename,
			&i.ParsedLanguage,
			&i.ParsedAt,
			&i.ParseStatus,
			&i.PublishedAt,
			&i.ProcessedAt,
			&i.SearchTsv,
			&i.StorageKey,
			&i.ContentType,
			&i.LocalPath,
			&i.StoredAt,
			&i.FetchAttempts,
			&i.OaStatus,
			&i.ParsedMarkdown,
			&i.SentenceOffsets,
			&i.ChunkFailures,
			&i.ChunkErrors,
			&i.LastChunkFailureAt,
			&i.ConceptSkipCount,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvestigationsByRepo = `-- name: ListInvestigationsByRepo :many
SELECT id, repository_id, title, topic, created_at, updated_at FROM okt_repository.investigations
WHERE repository_id = $1
  AND ($2::text = '' OR title ILIKE '%' || $2 || '%' OR topic ILIKE '%' || $2 || '%')
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListInvestigationsByRepoParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Column2      string      `json:"column_2"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

// Paginated, searchable repo-level investigation list. The optional
// `$2` (search) matches the title or topic with ILIKE so the user
// can filter by name without the full-text machinery a source/fact
// search needs (investigations are few per repo). Ordered by
// created_at DESC; LIMIT/OFFSET apply on top.
func (q *Queries) ListInvestigationsByRepo(ctx context.Context, arg ListInvestigationsByRepoParams) ([]OktRepositoryInvestigation, error) {
	rows, err := q.db.Query(ctx, listInvestigationsByRepo,
		arg.RepositoryID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktRepositoryInvestigation
	for rows.Next() {
		var i OktRepositoryInvestigation
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Title,
			&i.Topic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeInvestigationSource = `-- name: RemoveInvestigationSource :exec
DELETE FROM okt_repository.investigation_sources
WHERE investigation_id = $1 AND source_id = $2
`

type RemoveInvestigationSourceParams struct {
	InvestigationID pgtype.UUID `json:"investigation_id"`
	SourceID        pgtype.UUID `json:"source_id"`
}

func (q *Queries) RemoveInvestigationSource(ctx context.Context, arg RemoveInvestigationSourceParams) error {
	_, err := q.db.Exec(ctx, removeInvestigationSource, arg.InvestigationID, arg.SourceID)
	return err
}

const updateInvestigation = `-- name: UpdateInvestigation :one
UPDATE okt_repository.investigations
SET title = $2,
    topic = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, repository_id, title, topic, created_at, updated_at
`

type UpdateInvestigationParams struct {
	ID    pgtype.UUID `json:"id"`
	Title string      `json:"title"`
	Topic *string     `json:"topic"`
}

// Updates title and topic. NULL topic clears the field.
func (q *Queries) UpdateInvestigation(ctx context.Context, arg UpdateInvestigationParams) (OktRepositoryInvestigation, error) {
	row := q.db.QueryRow(ctx, updateInvestigation, arg.ID, arg.Title, arg.Topic)
	var i OktRepositoryInvestigation
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Title,
		&i.Topic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
