// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CasbinRule struct {
	ID    int32  `json:"id"`
	PType string `json:"p_type"`
	V0    string `json:"v0"`
	V1    string `json:"v1"`
	V2    string `json:"v2"`
	V3    string `json:"v3"`
	V4    string `json:"v4"`
	V5    string `json:"v5"`
}

type Group struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GroupMember struct {
	GroupID  pgtype.UUID        `json:"group_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type OktRepositoryConcept struct {
	ID               pgtype.UUID        `json:"id"`
	RepositoryID     pgtype.UUID        `json:"repository_id"`
	CanonicalName    string             `json:"canonical_name"`
	Context          string             `json:"context"`
	Description      *string            `json:"description"`
	EmbeddedAt       pgtype.Timestamptz `json:"embedded_at"`
	EmbeddedModel    *string            `json:"embedded_model"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	SummarizingAt    pgtype.Timestamptz `json:"summarizing_at"`
	AliasesRefinedAt pgtype.Timestamptz `json:"aliases_refined_at"`
	PromptsetHash    *string            `json:"promptset_hash"`
}

type OktRepositoryConceptAlias struct {
	ID        pgtype.UUID        `json:"id"`
	ConceptID pgtype.UUID        `json:"concept_id"`
	AliasText string             `json:"alias_text"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OktRepositoryConceptCandidate struct {
	ID                pgtype.UUID        `json:"id"`
	RepositoryID      pgtype.UUID        `json:"repository_id"`
	ConceptText       string             `json:"concept_text"`
	Context           string             `json:"context"`
	SeedAliases       []string           `json:"seed_aliases"`
	ResolvedConceptID pgtype.UUID        `json:"resolved_concept_id"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type OktRepositoryConceptRelation struct {
	RepositoryID    pgtype.UUID `json:"repository_id"`
	NameA           string      `json:"name_a"`
	NameB           string      `json:"name_b"`
	SharedFactCount int64       `json:"shared_fact_count"`
}

type OktRepositoryConceptSummary struct {
	ID             pgtype.UUID        `json:"id"`
	ConceptID      pgtype.UUID        `json:"concept_id"`
	RepositoryID   pgtype.UUID        `json:"repository_id"`
	Context        string             `json:"context"`
	SequenceNum    int32              `json:"sequence_num"`
	IsComplete     bool               `json:"is_complete"`
	FactCount      int32              `json:"fact_count"`
	Content        string             `json:"content"`
	CoveredFactIds []pgtype.UUID      `json:"covered_fact_ids"`
	Model          *string            `json:"model"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type OktRepositoryConceptSynthesis struct {
	ID                pgtype.UUID        `json:"id"`
	RepositoryID      pgtype.UUID        `json:"repository_id"`
	CanonicalName     string             `json:"canonical_name"`
	Content           string             `json:"content"`
	CoveredSummaryIds []pgtype.UUID      `json:"covered_summary_ids"`
	CoveredConceptIds []pgtype.UUID      `json:"covered_concept_ids"`
	EmbeddedImageIds  []pgtype.UUID      `json:"embedded_image_ids"`
	Model             *string            `json:"model"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type OktRepositoryFact struct {
	ID            pgtype.UUID        `json:"id"`
	Text          string             `json:"text"`
	Status        string             `json:"status"`
	EmbeddedAt    pgtype.Timestamptz `json:"embedded_at"`
	EmbeddedModel *string            `json:"embedded_model"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	SearchTsv     interface{}        `json:"search_tsv"`
	ImageUrl      *string            `json:"image_url"`
	FactKind      string             `json:"fact_kind"`
	PromptsetHash *string            `json:"promptset_hash"`
}

type OktRepositoryFactCandidate struct {
	FactID      pgtype.UUID        `json:"fact_id"`
	CandidateID pgtype.UUID        `json:"candidate_id"`
	FirstSeenAt pgtype.Timestamptz `json:"first_seen_at"`
}

type OktRepositoryFactConcept struct {
	FactID        pgtype.UUID        `json:"fact_id"`
	ConceptID     pgtype.UUID        `json:"concept_id"`
	FirstSeenAt   pgtype.Timestamptz `json:"first_seen_at"`
	PromptsetHash *string            `json:"promptset_hash"`
}

type OktRepositoryFactConceptSkip struct {
	FactID    pgtype.UUID        `json:"fact_id"`
	LastError string             `json:"last_error"`
	SkippedAt pgtype.Timestamptz `json:"skipped_at"`
}

type OktRepositoryFactReference struct {
	FactID        pgtype.UUID        `json:"fact_id"`
	SourceID      pgtype.UUID        `json:"source_id"`
	SentenceIndex int32              `json:"sentence_index"`
	ChunkIndex    int32              `json:"chunk_index"`
	FirstSeenAt   pgtype.Timestamptz `json:"first_seen_at"`
	PromptsetHash *string            `json:"promptset_hash"`
}

type OktRepositoryFactSource struct {
	FactID      pgtype.UUID        `json:"fact_id"`
	SourceID    pgtype.UUID        `json:"source_id"`
	ChunkIndex  int32              `json:"chunk_index"`
	FirstSeenAt pgtype.Timestamptz `json:"first_seen_at"`
}

type OktRepositoryInvestigation struct {
	ID           pgtype.UUID        `json:"id"`
	RepositoryID pgtype.UUID        `json:"repository_id"`
	Title        string             `json:"title"`
	Topic        *string            `json:"topic"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type OktRepositoryInvestigationSource struct {
	InvestigationID pgtype.UUID        `json:"investigation_id"`
	SourceID        pgtype.UUID        `json:"source_id"`
	AddedAt         pgtype.Timestamptz `json:"added_at"`
}

type OktRepositoryReport struct {
	ID                  pgtype.UUID        `json:"id"`
	RepositoryID        pgtype.UUID        `json:"repository_id"`
	Title               string             `json:"title"`
	Topic               *string            `json:"topic"`
	BodyMd              string             `json:"body_md"`
	Status              string             `json:"status"`
	Error               *string            `json:"error"`
	AnnotationJobID     *string            `json:"annotation_job_id"`
	SimilarityThreshold *float64           `json:"similarity_threshold"`
	EmbeddedModel       *string            `json:"embedded_model"`
	SentenceCount       *int32             `json:"sentence_count"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ParentID            pgtype.UUID        `json:"parent_id"`
}

type OktRepositoryReportAnnotation struct {
	ReportID      pgtype.UUID        `json:"report_id"`
	SentenceIndex int32              `json:"sentence_index"`
	SentenceText  string             `json:"sentence_text"`
	FactID        pgtype.UUID        `json:"fact_id"`
	Score         float64            `json:"score"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Posture       *string            `json:"posture"`
}

type OktRepositorySource struct {
	ID              pgtype.UUID        `json:"id"`
	RepositoryID    pgtype.UUID        `json:"repository_id"`
	Url             string             `json:"url"`
	Kind            string             `json:"kind"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Content         []byte             `json:"content"`
	FetchedAt       pgtype.Timestamptz `json:"fetched_at"`
	Error           *string            `json:"error"`
	Doi             *string            `json:"doi"`
	ParsedTitle     *string            `json:"parsed_title"`
	ParsedText      *string            `json:"parsed_text"`
	ParsedHtml      *string            `json:"parsed_html"`
	ParsedAuthor    *string            `json:"parsed_author"`
	ParsedSitename  *string            `json:"parsed_sitename"`
	ParsedLanguage  *string            `json:"parsed_language"`
	ParsedAt        pgtype.Timestamptz `json:"parsed_at"`
	ParseStatus     *string            `json:"parse_status"`
	PublishedAt     pgtype.Date        `json:"published_at"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
	SearchTsv       interface{}        `json:"search_tsv"`
	StorageKey      *string            `json:"storage_key"`
	ContentType     *string            `json:"content_type"`
	LocalPath       *string            `json:"local_path"`
	StoredAt        pgtype.Timestamptz `json:"stored_at"`
	FetchAttempts   []byte             `json:"fetch_attempts"`
	OaStatus        *string            `json:"oa_status"`
	ParsedMarkdown  *string            `json:"parsed_markdown"`
	SentenceOffsets []int32            `json:"sentence_offsets"`
}

type OktRepositorySourceImage struct {
	ID          pgtype.UUID        `json:"id"`
	SourceID    pgtype.UUID        `json:"source_id"`
	Kind        string             `json:"kind"`
	PageNumber  *int32             `json:"page_number"`
	Position    int32              `json:"position"`
	Url         *string            `json:"url"`
	Width       *int32             `json:"width"`
	Height      *int32             `json:"height"`
	Bytes       *int32             `json:"bytes"`
	LocalPath   *string            `json:"local_path"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	AltText     *string            `json:"alt_text"`
	StorageKey  *string            `json:"storage_key"`
	ContentType *string            `json:"content_type"`
	MirroredAt  pgtype.Timestamptz `json:"mirrored_at"`
}

type OktSystemAiUsage struct {
	ID               pgtype.UUID        `json:"id"`
	TaskID           *string            `json:"task_id"`
	Model            string             `json:"model"`
	Provider         string             `json:"provider"`
	PromptTokens     int32              `json:"prompt_tokens"`
	CompletionTokens int32              `json:"completion_tokens"`
	TotalTokens      int32              `json:"total_tokens"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	RepositoryID     pgtype.UUID        `json:"repository_id"`
	SourceID         pgtype.UUID        `json:"source_id"`
	Operation        string             `json:"operation"`
}

type OktSystemOauthAuthorizationCode struct {
	ID                  pgtype.UUID        `json:"id"`
	CodeHash            string             `json:"code_hash"`
	ClientID            string             `json:"client_id"`
	RedirectUri         string             `json:"redirect_uri"`
	Scope               string             `json:"scope"`
	UserID              pgtype.UUID        `json:"user_id"`
	CodeChallenge       string             `json:"code_challenge"`
	CodeChallengeMethod string             `json:"code_challenge_method"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type OktSystemOauthClient struct {
	ID                      pgtype.UUID        `json:"id"`
	ClientID                string             `json:"client_id"`
	ClientSecretHash        *string            `json:"client_secret_hash"`
	RedirectUris            []string           `json:"redirect_uris"`
	GrantTypes              []string           `json:"grant_types"`
	ResponseTypes           []string           `json:"response_types"`
	TokenEndpointAuthMethod string             `json:"token_endpoint_auth_method"`
	ClientName              string             `json:"client_name"`
	Scope                   string             `json:"scope"`
	ClientIDIssuedAt        pgtype.Timestamptz `json:"client_id_issued_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type OktSystemOauthRefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	TokenHash string             `json:"token_hash"`
	ClientID  string             `json:"client_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Scope     string             `json:"scope"`
	Revoked   bool               `json:"revoked"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OktSystemOktWorkerHeartbeat struct {
	WorkerID      string             `json:"worker_id"`
	Hostname      string             `json:"hostname"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	LastHeartbeat pgtype.Timestamptz `json:"last_heartbeat"`
}

type OktSystemPromptset struct {
	Hash                string             `json:"hash"`
	Name                string             `json:"name"`
	OwnerID             pgtype.UUID        `json:"owner_id"`
	FactExtraction      string             `json:"fact_extraction"`
	ImageFactExtraction string             `json:"image_fact_extraction"`
	ConceptExtraction   string             `json:"concept_extraction"`
	Refinement          string             `json:"refinement"`
	Synthesis           string             `json:"synthesis"`
	ImagePicker         string             `json:"image_picker"`
	Summarization       string             `json:"summarization"`
	Posture             string             `json:"posture"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type OktSystemRepositoryContext struct {
	RepositoryID pgtype.UUID        `json:"repository_id"`
	Context      string             `json:"context"`
	IsCustom     bool               `json:"is_custom"`
	Description  string             `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type OktSystemRepositoryContextMapping struct {
	RepositoryID    pgtype.UUID        `json:"repository_id"`
	LocalContext    string             `json:"local_context"`
	RegistryContext string             `json:"registry_context"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type OktSystemRepositoryModelSetting struct {
	RepositoryID pgtype.UUID        `json:"repository_id"`
	TaskKind     string             `json:"task_kind"`
	ModelID      *string            `json:"model_id"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type OktSystemRepositoryProviderSetting struct {
	RepositoryID pgtype.UUID        `json:"repository_id"`
	ProviderKind string             `json:"provider_kind"`
	ProviderID   string             `json:"provider_id"`
	Enabled      bool               `json:"enabled"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type OktSystemRepositoryReportSetting struct {
	RepositoryID             pgtype.UUID        `json:"repository_id"`
	SimilarityThreshold      *float64           `json:"similarity_threshold"`
	PostureClassifierEnabled bool               `json:"posture_classifier_enabled"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	MaxFactsPerSentence      *int32             `json:"max_facts_per_sentence"`
	LexicalSimilarityFloor   *float64           `json:"lexical_similarity_floor"`
}

type Repository struct {
	ID                      pgtype.UUID        `json:"id"`
	Name                    string             `json:"name"`
	Slug                    string             `json:"slug"`
	Description             string             `json:"description"`
	OwnerID                 pgtype.UUID        `json:"owner_id"`
	DatabaseName            string             `json:"database_name"`
	Tier                    string             `json:"tier"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	RegistryID              *string            `json:"registry_id"`
	AutoContribute          bool               `json:"auto_contribute"`
	RegistryEnabled         bool               `json:"registry_enabled"`
	UnmappedContextPolicy   string             `json:"unmapped_context_policy"`
	CatchAllContext         *string            `json:"catch_all_context"`
	AllowedModels           []string           `json:"allowed_models"`
	RegistryPushLevel       string             `json:"registry_push_level"`
	RegistryPullLevel       string             `json:"registry_pull_level"`
	ActivePromptsetHash     *string            `json:"active_promptset_hash"`
	AcceptedPromptsetHashes []string           `json:"accepted_promptset_hashes"`
	AllowedContentTypes     []string           `json:"allowed_content_types"`
	ContributorDisplayName  *string            `json:"contributor_display_name"`
	ContributorAnonymous    bool               `json:"contributor_anonymous"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
