// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: oauth.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthAuthorizationCode = `-- name: CreateOAuthAuthorizationCode :one
INSERT INTO okt_system.oauth_authorization_codes (
    code_hash, client_id, redirect_uri, scope, user_id,
    code_challenge, code_challenge_method, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, code_hash, client_id, redirect_uri, scope, user_id, code_challenge, code_challenge_method, expires_at, created_at
`

type CreateOAuthAuthorizationCodeParams struct {
	CodeHash            string             `json:"code_hash"`
	ClientID            string             `json:"client_id"`
	RedirectUri         string             `json:"redirect_uri"`
	Scope               string             `json:"scope"`
	UserID              pgtype.UUID        `json:"user_id"`
	CodeChallenge       string             `json:"code_challenge"`
	CodeChallengeMethod string             `json:"code_challenge_method"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOAuthAuthorizationCode(ctx context.Context, arg CreateOAuthAuthorizationCodeParams) (OktSystemOauthAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, createOAuthAuthorizationCode,
		arg.CodeHash,
		arg.ClientID,
		arg.RedirectUri,
		arg.Scope,
		arg.UserID,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.ExpiresAt,
	)
	var i OktSystemOauthAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ClientID,
		&i.RedirectUri,
		&i.Scope,
		&i.UserID,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthClient = `-- name: CreateOAuthClient :one
INSERT INTO okt_system.oauth_clients (
    client_id, client_secret_hash, redirect_uris, grant_types,
    response_types, token_endpoint_auth_method, client_name, scope
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, client_id, client_secret_hash, redirect_uris, grant_types, response_types, token_endpoint_auth_method, client_name, scope, client_id_issued_at, created_at
`

type CreateOAuthClientParams struct {
	ClientID                string   `json:"client_id"`
	ClientSecretHash        *string  `json:"client_secret_hash"`
	RedirectUris            []string `json:"redirect_uris"`
	GrantTypes              []string `json:"grant_types"`
	ResponseTypes           []string `json:"response_types"`
	TokenEndpointAuthMethod string   `json:"token_endpoint_auth_method"`
	ClientName              string   `json:"client_name"`
	Scope                   string   `json:"scope"`
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OktSystemOauthClient, error) {
	row := q.db.QueryRow(ctx, createOAuthClient,
		arg.ClientID,
		arg.ClientSecretHash,
		arg.RedirectUris,
		arg.GrantTypes,
		arg.ResponseTypes,
		arg.TokenEndpointAuthMethod,
		arg.ClientName,
		arg.Scope,
	)
	var i OktSystemOauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.TokenEndpointAuthMethod,
		&i.ClientName,
		&i.Scope,
		&i.ClientIDIssuedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthRefreshToken = `-- name: CreateOAuthRefreshToken :one
INSERT INTO okt_system.oauth_refresh_tokens (
    token_hash, client_id, user_id, scope, expires_at
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, token_hash, client_id, user_id, scope, revoked, expires_at, created_at
`

type CreateOAuthRefreshTokenParams struct {
	TokenHash string             `json:"token_hash"`
	ClientID  string             `json:"client_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Scope     string             `json:"scope"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOAuthRefreshToken(ctx context.Context, arg CreateOAuthRefreshTokenParams) (OktSystemOauthRefreshToken, error) {
	row := q.db.QueryRow(ctx, createOAuthRefreshToken,
		arg.TokenHash,
		arg.ClientID,
		arg.UserID,
		arg.Scope,
		arg.ExpiresAt,
	)
	var i OktSystemOauthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ClientID,
		&i.UserID,
		&i.Scope,
		&i.Revoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredOAuthAuthorizationCodes = `-- name: DeleteExpiredOAuthAuthorizationCodes :exec
DELETE FROM okt_system.oauth_authorization_codes WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredOAuthAuthorizationCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOAuthAuthorizationCodes)
	return err
}

const deleteExpiredOAuthRefreshTokens = `-- name: DeleteExpiredOAuthRefreshTokens :exec
DELETE FROM okt_system.oauth_refresh_tokens WHERE expires_at < now() OR revoked = TRUE
`

func (q *Queries) DeleteExpiredOAuthRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOAuthRefreshTokens)
	return err
}

const deleteOAuthAuthorizationCodeByHash = `-- name: DeleteOAuthAuthorizationCodeByHash :exec
DELETE FROM okt_system.oauth_authorization_codes WHERE code_hash = $1
`

func (q *Queries) DeleteOAuthAuthorizationCodeByHash(ctx context.Context, codeHash string) error {
	_, err := q.db.Exec(ctx, deleteOAuthAuthorizationCodeByHash, codeHash)
	return err
}

const deleteOAuthClientByClientID = `-- name: DeleteOAuthClientByClientID :exec
DELETE FROM okt_system.oauth_clients WHERE client_id = $1
`

func (q *Queries) DeleteOAuthClientByClientID(ctx context.Context, clientID string) error {
	_, err := q.db.Exec(ctx, deleteOAuthClientByClientID, clientID)
	return err
}

const deleteOAuthRefreshTokenByHash = `-- name: DeleteOAuthRefreshTokenByHash :exec
DELETE FROM okt_system.oauth_refresh_tokens WHERE token_hash = $1
`

func (q *Queries) DeleteOAuthRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteOAuthRefreshTokenByHash, tokenHash)
	return err
}

const getOAuthAuthorizationCodeByHash = `-- name: GetOAuthAuthorizationCodeByHash :one
SELECT id, code_hash, client_id, redirect_uri, scope, user_id, code_challenge, code_challenge_method, expires_at, created_at FROM okt_system.oauth_authorization_codes WHERE code_hash = $1
`

func (q *Queries) GetOAuthAuthorizationCodeByHash(ctx context.Context, codeHash string) (OktSystemOauthAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, getOAuthAuthorizationCodeByHash, codeHash)
	var i OktSystemOauthAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ClientID,
		&i.RedirectUri,
		&i.Scope,
		&i.UserID,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthClientByClientID = `-- name: GetOAuthClientByClientID :one
SELECT id, client_id, client_secret_hash, redirect_uris, grant_types, response_types, token_endpoint_auth_method, client_name, scope, client_id_issued_at, created_at FROM okt_system.oauth_clients WHERE client_id = $1
`

func (q *Queries) GetOAuthClientByClientID(ctx context.Context, clientID string) (OktSystemOauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClientByClientID, clientID)
	var i OktSystemOauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.TokenEndpointAuthMethod,
		&i.ClientName,
		&i.Scope,
		&i.ClientIDIssuedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthRefreshTokenByHash = `-- name: GetOAuthRefreshTokenByHash :one
SELECT id, token_hash, client_id, user_id, scope, revoked, expires_at, created_at FROM okt_system.oauth_refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetOAuthRefreshTokenByHash(ctx context.Context, tokenHash string) (OktSystemOauthRefreshToken, error) {
	row := q.db.QueryRow(ctx, getOAuthRefreshTokenByHash, tokenHash)
	var i OktSystemOauthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ClientID,
		&i.UserID,
		&i.Scope,
		&i.Revoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listOAuthClients = `-- name: ListOAuthClients :many
SELECT id, client_id, client_secret_hash, redirect_uris, grant_types, response_types, token_endpoint_auth_method, client_name, scope, client_id_issued_at, created_at FROM okt_system.oauth_clients ORDER BY created_at DESC
`

func (q *Queries) ListOAuthClients(ctx context.Context) ([]OktSystemOauthClient, error) {
	rows, err := q.db.Query(ctx, listOAuthClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktSystemOauthClient
	for rows.Next() {
		var i OktSystemOauthClient
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientSecretHash,
			&i.RedirectUris,
			&i.GrantTypes,
			&i.ResponseTypes,
			&i.TokenEndpointAuthMethod,
			&i.ClientName,
			&i.Scope,
			&i.ClientIDIssuedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOAuthRefreshTokenByHash = `-- name: RevokeOAuthRefreshTokenByHash :exec
UPDATE okt_system.oauth_refresh_tokens SET revoked = TRUE
WHERE token_hash = $1
`

func (q *Queries) RevokeOAuthRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeOAuthRefreshTokenByHash, tokenHash)
	return err
}
