// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: promptsets.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePromptset = `-- name: DeletePromptset :exec
DELETE FROM okt_system.promptsets WHERE hash = $1
`

// Remove a promptset by hash. The handler enforces ownership (only
// the owner or a sysadmin may delete) before calling this. Deleting a
// promptset does NOT cascade to repositories that reference it: the
// per-repo active_promptset_hash / accepted_promptset_hashes
// columns are plain TEXT / TEXT[] with no FK (the built-in promptset
// is not a row, so an FK would force a sentinel row). A repo pointing
// at a deleted promptset falls back to the global default at resolve
// time, which is the safe behavior.
func (q *Queries) DeletePromptset(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deletePromptset, hash)
	return err
}

const getPromptsetByHash = `-- name: GetPromptsetByHash :one

SELECT hash, name, owner_id, fact_extraction, image_fact_extraction, concept_extraction, refinement, synthesis, image_picker, summarization, posture, created_at, updated_at FROM okt_system.promptsets WHERE hash = $1
`

// promptsets.sql — user-defined promptset catalog (see migration 0046).
//
// The table lives in okt_system (user-owned metadata). The PK is the
// hash (sha256 of the 8 phase strings), so two promptsets with the
// same prompts collapse to one row — the identity IS the philosophy.
// The create handler computes the hash server-side and ignores any
// client-supplied hash; ON CONFLICT DO UPDATE lets a re-create with
// the same prompts rename + re-own the row.
func (q *Queries) GetPromptsetByHash(ctx context.Context, hash string) (OktSystemPromptset, error) {
	row := q.db.QueryRow(ctx, getPromptsetByHash, hash)
	var i OktSystemPromptset
	err := row.Scan(
		&i.Hash,
		&i.Name,
		&i.OwnerID,
		&i.FactExtraction,
		&i.ImageFactExtraction,
		&i.ConceptExtraction,
		&i.Refinement,
		&i.Synthesis,
		&i.ImagePicker,
		&i.Summarization,
		&i.Posture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPromptsets = `-- name: ListAllPromptsets :many
SELECT hash, name, owner_id, fact_extraction, image_fact_extraction, concept_extraction, refinement, synthesis, image_picker, summarization, posture, created_at, updated_at FROM okt_system.promptsets
ORDER BY created_at DESC
`

// Every promptset in the catalog. Used by the sysadmin view; the
// per-user handler uses ListPromptsetsByOwner instead.
func (q *Queries) ListAllPromptsets(ctx context.Context) ([]OktSystemPromptset, error) {
	rows, err := q.db.Query(ctx, listAllPromptsets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktSystemPromptset
	for rows.Next() {
		var i OktSystemPromptset
		if err := rows.Scan(
			&i.Hash,
			&i.Name,
			&i.OwnerID,
			&i.FactExtraction,
			&i.ImageFactExtraction,
			&i.ConceptExtraction,
			&i.Refinement,
			&i.Synthesis,
			&i.ImagePicker,
			&i.Summarization,
			&i.Posture,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromptsetsByOwner = `-- name: ListPromptsetsByOwner :many
SELECT hash, name, owner_id, fact_extraction, image_fact_extraction, concept_extraction, refinement, synthesis, image_picker, summarization, posture, created_at, updated_at FROM okt_system.promptsets
WHERE owner_id = $1
ORDER BY created_at DESC
`

// Every promptset owned by a user, newest first. The handler
// intersects this with the built-in promptset to build the full
// catalog the UI offers.
func (q *Queries) ListPromptsetsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]OktSystemPromptset, error) {
	rows, err := q.db.Query(ctx, listPromptsetsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktSystemPromptset
	for rows.Next() {
		var i OktSystemPromptset
		if err := rows.Scan(
			&i.Hash,
			&i.Name,
			&i.OwnerID,
			&i.FactExtraction,
			&i.ImageFactExtraction,
			&i.ConceptExtraction,
			&i.Refinement,
			&i.Synthesis,
			&i.ImagePicker,
			&i.Summarization,
			&i.Posture,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPromptset = `-- name: UpsertPromptset :one
INSERT INTO okt_system.promptsets (
    hash, name, owner_id,
    fact_extraction, image_fact_extraction, concept_extraction,
    refinement, synthesis, image_picker, summarization, posture
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (hash) DO UPDATE SET
    name                  = EXCLUDED.name,
    owner_id              = EXCLUDED.owner_id,
    fact_extraction       = EXCLUDED.fact_extraction,
    image_fact_extraction = EXCLUDED.image_fact_extraction,
    concept_extraction    = EXCLUDED.concept_extraction,
    refinement            = EXCLUDED.refinement,
    synthesis             = EXCLUDED.synthesis,
    image_picker          = EXCLUDED.image_picker,
    summarization         = EXCLUDED.summarization,
    posture               = EXCLUDED.posture,
    updated_at            = now()
RETURNING hash, name, owner_id, fact_extraction, image_fact_extraction, concept_extraction, refinement, synthesis, image_picker, summarization, posture, created_at, updated_at
`

type UpsertPromptsetParams struct {
	Hash                string      `json:"hash"`
	Name                string      `json:"name"`
	OwnerID             pgtype.UUID `json:"owner_id"`
	FactExtraction      string      `json:"fact_extraction"`
	ImageFactExtraction string      `json:"image_fact_extraction"`
	ConceptExtraction   string      `json:"concept_extraction"`
	Refinement          string      `json:"refinement"`
	Synthesis           string      `json:"synthesis"`
	ImagePicker         string      `json:"image_picker"`
	Summarization       string      `json:"summarization"`
	Posture             string      `json:"posture"`
}

// Insert a new promptset, or — when the hash already exists (same 8
// phase strings as an existing row) — update the name + owner + the
// phase strings (which are necessarily equal, but bumping updated_at
// is harmless) and return the row. The handler computes the hash
// from the request body and passes it as $1; the ON CONFLICT target
// is the PK (hash).
func (q *Queries) UpsertPromptset(ctx context.Context, arg UpsertPromptsetParams) (OktSystemPromptset, error) {
	row := q.db.QueryRow(ctx, upsertPromptset,
		arg.Hash,
		arg.Name,
		arg.OwnerID,
		arg.FactExtraction,
		arg.ImageFactExtraction,
		arg.ConceptExtraction,
		arg.Refinement,
		arg.Synthesis,
		arg.ImagePicker,
		arg.Summarization,
		arg.Posture,
	)
	var i OktSystemPromptset
	err := row.Scan(
		&i.Hash,
		&i.Name,
		&i.OwnerID,
		&i.FactExtraction,
		&i.ImageFactExtraction,
		&i.ConceptExtraction,
		&i.Refinement,
		&i.Synthesis,
		&i.ImagePicker,
		&i.Summarization,
		&i.Posture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
