// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reports.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addReportAnnotation = `-- name: AddReportAnnotation :exec
INSERT INTO okt_repository.report_annotations (report_id, sentence_index, sentence_text, fact_id, score, posture)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (report_id, sentence_index, fact_id) DO NOTHING
`

type AddReportAnnotationParams struct {
	ReportID      pgtype.UUID `json:"report_id"`
	SentenceIndex int32       `json:"sentence_index"`
	SentenceText  string      `json:"sentence_text"`
	FactID        pgtype.UUID `json:"fact_id"`
	Score         float64     `json:"score"`
	Posture       *string     `json:"posture"`
}

// Idempotent on the PK so re-running annotation (or a retry that
// reaches the same match) doesn't double-insert. posture is the
// autocite classifier label ('related','supports','contradicts');
// NULL on legacy rows or when the classifier was not configured
// (the keep-all fallback).
func (q *Queries) AddReportAnnotation(ctx context.Context, arg AddReportAnnotationParams) error {
	_, err := q.db.Exec(ctx, addReportAnnotation,
		arg.ReportID,
		arg.SentenceIndex,
		arg.SentenceText,
		arg.FactID,
		arg.Score,
		arg.Posture,
	)
	return err
}

const clearReportAnnotations = `-- name: ClearReportAnnotations :exec
DELETE FROM okt_repository.report_annotations WHERE report_id = $1
`

// Removes all annotations for a report before a re-annotation pass
// so stale matches (e.g. a fact that was since deleted) don't linger.
func (q *Queries) ClearReportAnnotations(ctx context.Context, reportID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearReportAnnotations, reportID)
	return err
}

const countReportsByRepo = `-- name: CountReportsByRepo :one
SELECT COUNT(*) FROM okt_repository.reports
WHERE repository_id = $1
  AND ($2::text = '' OR title ILIKE '%' || $2 || '%' OR topic ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR status = $3)
`

type CountReportsByRepoParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Column2      string      `json:"column_2"`
	Column3      string      `json:"column_3"`
}

func (q *Queries) CountReportsByRepo(ctx context.Context, arg CountReportsByRepoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReportsByRepo, arg.RepositoryID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO okt_repository.reports (id, repository_id, title, topic, body_md, status, parent_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, repository_id, title, topic, body_md, status, error, annotation_job_id, similarity_threshold, embedded_model, sentence_count, created_at, updated_at, parent_id
`

type CreateReportParams struct {
	ID           pgtype.UUID `json:"id"`
	RepositoryID pgtype.UUID `json:"repository_id"`
	Title        string      `json:"title"`
	Topic        *string     `json:"topic"`
	BodyMd       string      `json:"body_md"`
	Status       string      `json:"status"`
	ParentID     pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (OktRepositoryReport, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ID,
		arg.RepositoryID,
		arg.Title,
		arg.Topic,
		arg.BodyMd,
		arg.Status,
		arg.ParentID,
	)
	var i OktRepositoryReport
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Title,
		&i.Topic,
		&i.BodyMd,
		&i.Status,
		&i.Error,
		&i.AnnotationJobID,
		&i.SimilarityThreshold,
		&i.EmbeddedModel,
		&i.SentenceCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
	)
	return i, err
}

const deleteReport = `-- name: DeleteReport :exec
DELETE FROM okt_repository.reports WHERE id = $1
`

func (q *Queries) DeleteReport(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReport, id)
	return err
}

const getReportAncestors = `-- name: GetReportAncestors :many
WITH RECURSIVE ancestors AS (
    SELECT r.id, r.parent_id, r.repository_id, 1 AS depth
    FROM okt_repository.reports r
    WHERE r.id = $1
    UNION
    SELECT r.id, r.parent_id, r.repository_id, a.depth + 1
    FROM okt_repository.reports r
    JOIN ancestors a ON r.id = a.parent_id
    WHERE a.depth < 100
)
SELECT id, parent_id, repository_id FROM ancestors ORDER BY depth DESC
`

type GetReportAncestorsRow struct {
	ID           pgtype.UUID `json:"id"`
	ParentID     pgtype.UUID `json:"parent_id"`
	RepositoryID pgtype.UUID `json:"repository_id"`
}

// Returns the chain of ancestors for a single report id (used for
// cycle detection before reparenting). Ordered from immediate parent
// up to the root.
func (q *Queries) GetReportAncestors(ctx context.Context, id pgtype.UUID) ([]GetReportAncestorsRow, error) {
	rows, err := q.db.Query(ctx, getReportAncestors, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportAncestorsRow
	for rows.Next() {
		var i GetReportAncestorsRow
		if err := rows.Scan(&i.ID, &i.ParentID, &i.RepositoryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, repository_id, title, topic, body_md, status, error, annotation_job_id, similarity_threshold, embedded_model, sentence_count, created_at, updated_at, parent_id FROM okt_repository.reports WHERE id = $1
`

func (q *Queries) GetReportByID(ctx context.Context, id pgtype.UUID) (OktRepositoryReport, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i OktRepositoryReport
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Title,
		&i.Topic,
		&i.BodyMd,
		&i.Status,
		&i.Error,
		&i.AnnotationJobID,
		&i.SimilarityThreshold,
		&i.EmbeddedModel,
		&i.SentenceCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
	)
	return i, err
}

const listReportAnnotationsByReport = `-- name: ListReportAnnotationsByReport :many
SELECT ra.report_id, ra.sentence_index, ra.sentence_text, ra.fact_id, ra.score, ra.posture, ra.created_at,
       f.text, f.status, f.fact_kind, f.image_url, f.created_at AS fact_created_at,
       COALESCE(fs_count.source_count, 0) AS source_count
FROM okt_repository.report_annotations ra
JOIN okt_repository.reports rep ON rep.id = ra.report_id
JOIN okt_repository.facts f ON f.id = ra.fact_id
LEFT JOIN LATERAL (
    SELECT fs2.fact_id, COUNT(*) AS source_count
    FROM okt_repository.fact_sources fs2
    JOIN okt_repository.sources s2 ON s2.id = fs2.source_id
    WHERE s2.repository_id = rep.repository_id
    GROUP BY fs2.fact_id
) fs_count ON fs_count.fact_id = f.id
WHERE ra.report_id = $1
ORDER BY ra.sentence_index, ra.score DESC
`

type ListReportAnnotationsByReportRow struct {
	ReportID      pgtype.UUID        `json:"report_id"`
	SentenceIndex int32              `json:"sentence_index"`
	SentenceText  string             `json:"sentence_text"`
	FactID        pgtype.UUID        `json:"fact_id"`
	Score         float64            `json:"score"`
	Posture       *string            `json:"posture"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Text          string             `json:"text"`
	Status        string             `json:"status"`
	FactKind      string             `json:"fact_kind"`
	ImageUrl      *string            `json:"image_url"`
	FactCreatedAt pgtype.Timestamptz `json:"fact_created_at"`
	SourceCount   int64              `json:"source_count"`
}

// UI-facing: every annotation for a report, joined with the fact
// row so the frontend can group facts by sentence_index and render
// the autocitation view. Ordered by sentence_index then score DESC
// so the best match surfaces first within each sentence.
func (q *Queries) ListReportAnnotationsByReport(ctx context.Context, reportID pgtype.UUID) ([]ListReportAnnotationsByReportRow, error) {
	rows, err := q.db.Query(ctx, listReportAnnotationsByReport, reportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReportAnnotationsByReportRow
	for rows.Next() {
		var i ListReportAnnotationsByReportRow
		if err := rows.Scan(
			&i.ReportID,
			&i.SentenceIndex,
			&i.SentenceText,
			&i.FactID,
			&i.Score,
			&i.Posture,
			&i.CreatedAt,
			&i.Text,
			&i.Status,
			&i.FactKind,
			&i.ImageUrl,
			&i.FactCreatedAt,
			&i.SourceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsByRepo = `-- name: ListReportsByRepo :many
SELECT id, repository_id, title, topic, body_md, status, error, annotation_job_id, similarity_threshold, embedded_model, sentence_count, created_at, updated_at, parent_id FROM okt_repository.reports
WHERE repository_id = $1
  AND ($2::text = '' OR title ILIKE '%' || $2 || '%' OR topic ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR status = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListReportsByRepoParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Column2      string      `json:"column_2"`
	Column3      string      `json:"column_3"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

// Paginated, searchable repo-level report list. The optional `$2`
// (search) matches title or topic with ILIKE (reports are few per
// repo). An optional status filter (`$3`) narrows to a single
// lifecycle state (pending/processing/annotated/failed); ” = all.
func (q *Queries) ListReportsByRepo(ctx context.Context, arg ListReportsByRepoParams) ([]OktRepositoryReport, error) {
	rows, err := q.db.Query(ctx, listReportsByRepo,
		arg.RepositoryID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktRepositoryReport
	for rows.Next() {
		var i OktRepositoryReport
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Title,
			&i.Topic,
			&i.BodyMd,
			&i.Status,
			&i.Error,
			&i.AnnotationJobID,
			&i.SimilarityThreshold,
			&i.EmbeddedModel,
			&i.SentenceCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReportStatus = `-- name: MarkReportStatus :exec
UPDATE okt_repository.reports
SET status = $2,
    error = $3,
    annotation_job_id = $4,
    sentence_count = $5,
    embedded_model = $6,
    similarity_threshold = $7,
    updated_at = now()
WHERE id = $1
`

type MarkReportStatusParams struct {
	ID                  pgtype.UUID `json:"id"`
	Status              string      `json:"status"`
	Error               *string     `json:"error"`
	AnnotationJobID     *string     `json:"annotation_job_id"`
	SentenceCount       *int32      `json:"sentence_count"`
	EmbeddedModel       *string     `json:"embedded_model"`
	SimilarityThreshold *float64    `json:"similarity_threshold"`
}

// Updates the report's annotation lifecycle state. error is set
// on failure (and NULL on success); annotation_job_id records the
// River job id that owns the in-flight annotation; sentence_count
// and embedded_model record what the worker produced.
func (q *Queries) MarkReportStatus(ctx context.Context, arg MarkReportStatusParams) error {
	_, err := q.db.Exec(ctx, markReportStatus,
		arg.ID,
		arg.Status,
		arg.Error,
		arg.AnnotationJobID,
		arg.SentenceCount,
		arg.EmbeddedModel,
		arg.SimilarityThreshold,
	)
	return err
}

const setReportsParent = `-- name: SetReportsParent :exec
UPDATE okt_repository.reports
SET parent_id = $1,
    updated_at = now()
WHERE id = ANY($2::uuid[])
  AND repository_id = $3
`

type SetReportsParentParams struct {
	ParentID     pgtype.UUID   `json:"parent_id"`
	Column2      []pgtype.UUID `json:"column_2"`
	RepositoryID pgtype.UUID   `json:"repository_id"`
}

// Bulk reparent: sets parent_id on every id in the list. Caller is
// responsible for validating all ids belong to the same repository
// and that no id equals the new parent (self-parent) or is an
// ancestor of the new parent (cycle prevention). repository_id is
// checked to prevent cross-repo reparenting.
func (q *Queries) SetReportsParent(ctx context.Context, arg SetReportsParentParams) error {
	_, err := q.db.Exec(ctx, setReportsParent, arg.ParentID, arg.Column2, arg.RepositoryID)
	return err
}

const updateReport = `-- name: UpdateReport :one
UPDATE okt_repository.reports
SET title = $2,
    topic = $3,
    body_md = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, repository_id, title, topic, body_md, status, error, annotation_job_id, similarity_threshold, embedded_model, sentence_count, created_at, updated_at, parent_id
`

type UpdateReportParams struct {
	ID     pgtype.UUID `json:"id"`
	Title  string      `json:"title"`
	Topic  *string     `json:"topic"`
	BodyMd string      `json:"body_md"`
}

// Updates title, topic, and body_md. Re-annotation is triggered
// separately by the caller enqueuing an annotate_report job when
// body_md changed.
func (q *Queries) UpdateReport(ctx context.Context, arg UpdateReportParams) (OktRepositoryReport, error) {
	row := q.db.QueryRow(ctx, updateReport,
		arg.ID,
		arg.Title,
		arg.Topic,
		arg.BodyMd,
	)
	var i OktRepositoryReport
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Title,
		&i.Topic,
		&i.BodyMd,
		&i.Status,
		&i.Error,
		&i.AnnotationJobID,
		&i.SimilarityThreshold,
		&i.EmbeddedModel,
		&i.SentenceCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
	)
	return i, err
}
