// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: repository_settings.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRepositoryContext = `-- name: DeleteRepositoryContext :exec
DELETE FROM okt_system.repository_contexts
WHERE repository_id = $1 AND lower(context) = lower($2)
`

type DeleteRepositoryContextParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Context      string      `json:"context"`
}

func (q *Queries) DeleteRepositoryContext(ctx context.Context, arg DeleteRepositoryContextParams) error {
	_, err := q.db.Exec(ctx, deleteRepositoryContext, arg.RepositoryID, arg.Context)
	return err
}

const deleteRepositoryContextMapping = `-- name: DeleteRepositoryContextMapping :exec
DELETE FROM okt_system.repository_context_mappings
WHERE repository_id = $1 AND lower(local_context) = lower($2)
`

type DeleteRepositoryContextMappingParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Lower        string      `json:"lower"`
}

// Remove a mapping by local context (case-insensitive). Used by the
// DeleteContextMapping handler.
func (q *Queries) DeleteRepositoryContextMapping(ctx context.Context, arg DeleteRepositoryContextMappingParams) error {
	_, err := q.db.Exec(ctx, deleteRepositoryContextMapping, arg.RepositoryID, arg.Lower)
	return err
}

const deleteRepositoryModelSetting = `-- name: DeleteRepositoryModelSetting :exec
DELETE FROM okt_system.repository_model_settings
WHERE repository_id = $1 AND task_kind = $2
`

type DeleteRepositoryModelSettingParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	TaskKind     string      `json:"task_kind"`
}

// Clear a per-repo model override (revert to inheriting the global
// default). Called when the UI sets model_id to empty/null.
func (q *Queries) DeleteRepositoryModelSetting(ctx context.Context, arg DeleteRepositoryModelSettingParams) error {
	_, err := q.db.Exec(ctx, deleteRepositoryModelSetting, arg.RepositoryID, arg.TaskKind)
	return err
}

const deleteRepositoryReportSettings = `-- name: DeleteRepositoryReportSettings :exec
DELETE FROM okt_system.repository_report_settings
WHERE repository_id = $1
`

// Drop the per-repo override row so the repo inherits the global
// defaults again.
func (q *Queries) DeleteRepositoryReportSettings(ctx context.Context, repositoryID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRepositoryReportSettings, repositoryID)
	return err
}

const getRepositoryContext = `-- name: GetRepositoryContext :one
SELECT repository_id, context, is_custom, description, created_at, updated_at FROM okt_system.repository_contexts
WHERE repository_id = $1 AND lower(context) = lower($2)
`

type GetRepositoryContextParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Context      string      `json:"context"`
}

func (q *Queries) GetRepositoryContext(ctx context.Context, arg GetRepositoryContextParams) (OktSystemRepositoryContext, error) {
	row := q.db.QueryRow(ctx, getRepositoryContext, arg.RepositoryID, arg.Context)
	var i OktSystemRepositoryContext
	err := row.Scan(
		&i.RepositoryID,
		&i.Context,
		&i.IsCustom,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryContextMappingByLocal = `-- name: GetRepositoryContextMappingByLocal :one
SELECT repository_id, local_context, registry_context, created_at, updated_at FROM okt_system.repository_context_mappings
WHERE repository_id = $1 AND lower(local_context) = lower($2)
`

type GetRepositoryContextMappingByLocalParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Lower        string      `json:"lower"`
}

// Outbound (contribute) lookup: local context → registry context.
// Case-insensitive on the local label. Used by the contribute_source
// worker.
func (q *Queries) GetRepositoryContextMappingByLocal(ctx context.Context, arg GetRepositoryContextMappingByLocalParams) (OktSystemRepositoryContextMapping, error) {
	row := q.db.QueryRow(ctx, getRepositoryContextMappingByLocal, arg.RepositoryID, arg.Lower)
	var i OktSystemRepositoryContextMapping
	err := row.Scan(
		&i.RepositoryID,
		&i.LocalContext,
		&i.RegistryContext,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryContextMappingByRegistry = `-- name: GetRepositoryContextMappingByRegistry :one
SELECT repository_id, local_context, registry_context, created_at, updated_at FROM okt_system.repository_context_mappings
WHERE repository_id = $1 AND lower(registry_context) = lower($2)
`

type GetRepositoryContextMappingByRegistryParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Lower        string      `json:"lower"`
}

// Inbound (pull) lookup: registry context → local context.
// Case-insensitive on the registry label. Used by the
// pull_all_from_registry worker.
func (q *Queries) GetRepositoryContextMappingByRegistry(ctx context.Context, arg GetRepositoryContextMappingByRegistryParams) (OktSystemRepositoryContextMapping, error) {
	row := q.db.QueryRow(ctx, getRepositoryContextMappingByRegistry, arg.RepositoryID, arg.Lower)
	var i OktSystemRepositoryContextMapping
	err := row.Scan(
		&i.RepositoryID,
		&i.LocalContext,
		&i.RegistryContext,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryModelSetting = `-- name: GetRepositoryModelSetting :one

SELECT repository_id, task_kind, model_id, updated_at FROM okt_system.repository_model_settings
WHERE repository_id = $1 AND task_kind = $2
`

type GetRepositoryModelSettingParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	TaskKind     string      `json:"task_kind"`
}

// ──────────────────────────────────────────────────────────────
// Per-repository model selection (see migration 0039).
// ──────────────────────────────────────────────────────────────
// Single (task_kind, model_id) row for a repo. model_id is NULL
// when the repo inherits the global config default for this task.
// Read by the ModelResolver at Work() start to decide which model
// + provider a worker should use for this repo.
func (q *Queries) GetRepositoryModelSetting(ctx context.Context, arg GetRepositoryModelSettingParams) (OktSystemRepositoryModelSetting, error) {
	row := q.db.QueryRow(ctx, getRepositoryModelSetting, arg.RepositoryID, arg.TaskKind)
	var i OktSystemRepositoryModelSetting
	err := row.Scan(
		&i.RepositoryID,
		&i.TaskKind,
		&i.ModelID,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryReportSettings = `-- name: GetRepositoryReportSettings :one
SELECT repository_id, similarity_threshold, posture_classifier_enabled, updated_at, max_facts_per_sentence, lexical_similarity_floor, context_window_before, context_window_after FROM okt_system.repository_report_settings
WHERE repository_id = $1
`

// Per-repository report annotation settings. Returns the single row
// for this repo; absence returns sql.ErrNoRows and the caller falls
// back to the global config defaults (threshold = 0.84, classifier
// enabled = true). The annotate_report worker reads this before
// resolving the per-repo pool.
func (q *Queries) GetRepositoryReportSettings(ctx context.Context, repositoryID pgtype.UUID) (OktSystemRepositoryReportSetting, error) {
	row := q.db.QueryRow(ctx, getRepositoryReportSettings, repositoryID)
	var i OktSystemRepositoryReportSetting
	err := row.Scan(
		&i.RepositoryID,
		&i.SimilarityThreshold,
		&i.PostureClassifierEnabled,
		&i.UpdatedAt,
		&i.MaxFactsPerSentence,
		&i.LexicalSimilarityFloor,
		&i.ContextWindowBefore,
		&i.ContextWindowAfter,
	)
	return i, err
}

const getUnmappedContextPolicy = `-- name: GetUnmappedContextPolicy :one
SELECT unmapped_context_policy, catch_all_context FROM repositories WHERE id = $1
`

type GetUnmappedContextPolicyRow struct {
	UnmappedContextPolicy string  `json:"unmapped_context_policy"`
	CatchAllContext       *string `json:"catch_all_context"`
}

// Combined policy + catch_all_context lookup. Read by the
// pull_all_from_registry worker (once per repo per Work call) and
// by the ListContextMappings handler to surface the current policy
// in the settings UI.
func (q *Queries) GetUnmappedContextPolicy(ctx context.Context, id pgtype.UUID) (GetUnmappedContextPolicyRow, error) {
	row := q.db.QueryRow(ctx, getUnmappedContextPolicy, id)
	var i GetUnmappedContextPolicyRow
	err := row.Scan(&i.UnmappedContextPolicy, &i.CatchAllContext)
	return i, err
}

const listEnabledRepositoryProviderIDs = `-- name: ListEnabledRepositoryProviderIDs :many
SELECT provider_kind, provider_id
FROM okt_system.repository_provider_settings
WHERE repository_id = $1 AND enabled = TRUE
ORDER BY provider_kind, provider_id
`

type ListEnabledRepositoryProviderIDsRow struct {
	ProviderKind string `json:"provider_kind"`
	ProviderID   string `json:"provider_id"`
}

// The gate helper: returns every enabled (kind, id) pair for a repo.
// The caller intersects with the live registry; orphans are filtered
// out here implicitly because they're either disabled or absent.
func (q *Queries) ListEnabledRepositoryProviderIDs(ctx context.Context, repositoryID pgtype.UUID) ([]ListEnabledRepositoryProviderIDsRow, error) {
	rows, err := q.db.Query(ctx, listEnabledRepositoryProviderIDs, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledRepositoryProviderIDsRow
	for rows.Next() {
		var i ListEnabledRepositoryProviderIDsRow
		if err := rows.Scan(&i.ProviderKind, &i.ProviderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoryContextMappings = `-- name: ListRepositoryContextMappings :many
SELECT repository_id, local_context, registry_context, created_at, updated_at FROM okt_system.repository_context_mappings
WHERE repository_id = $1
ORDER BY local_context
`

// Every mapping row for a repo, ordered by local_context. Used by
// the ListContextMappings handler and by the contribute/pull
// workers to build their in-memory translation tables.
func (q *Queries) ListRepositoryContextMappings(ctx context.Context, repositoryID pgtype.UUID) ([]OktSystemRepositoryContextMapping, error) {
	rows, err := q.db.Query(ctx, listRepositoryContextMappings, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktSystemRepositoryContextMapping
	for rows.Next() {
		var i OktSystemRepositoryContextMapping
		if err := rows.Scan(
			&i.RepositoryID,
			&i.LocalContext,
			&i.RegistryContext,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoryContexts = `-- name: ListRepositoryContexts :many
SELECT repository_id, context, is_custom, description, created_at, updated_at FROM okt_system.repository_contexts
WHERE repository_id = $1
ORDER BY is_custom, context
`

func (q *Queries) ListRepositoryContexts(ctx context.Context, repositoryID pgtype.UUID) ([]OktSystemRepositoryContext, error) {
	rows, err := q.db.Query(ctx, listRepositoryContexts, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktSystemRepositoryContext
	for rows.Next() {
		var i OktSystemRepositoryContext
		if err := rows.Scan(
			&i.RepositoryID,
			&i.Context,
			&i.IsCustom,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoryModelSettings = `-- name: ListRepositoryModelSettings :many
SELECT repository_id, task_kind, model_id, updated_at FROM okt_system.repository_model_settings
WHERE repository_id = $1
ORDER BY task_kind
`

// Every (task_kind, model_id) override for a repo. Used by
// GetSettings to surface the per-task model selections in the UI.
func (q *Queries) ListRepositoryModelSettings(ctx context.Context, repositoryID pgtype.UUID) ([]OktSystemRepositoryModelSetting, error) {
	rows, err := q.db.Query(ctx, listRepositoryModelSettings, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktSystemRepositoryModelSetting
	for rows.Next() {
		var i OktSystemRepositoryModelSetting
		if err := rows.Scan(
			&i.RepositoryID,
			&i.TaskKind,
			&i.ModelID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoryProviderSettings = `-- name: ListRepositoryProviderSettings :many
SELECT repository_id, provider_kind, provider_id, enabled, updated_at FROM okt_system.repository_provider_settings
WHERE repository_id = $1
ORDER BY provider_kind, provider_id
`

func (q *Queries) ListRepositoryProviderSettings(ctx context.Context, repositoryID pgtype.UUID) ([]OktSystemRepositoryProviderSetting, error) {
	rows, err := q.db.Query(ctx, listRepositoryProviderSettings, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktSystemRepositoryProviderSetting
	for rows.Next() {
		var i OktSystemRepositoryProviderSetting
		if err := rows.Scan(
			&i.RepositoryID,
			&i.ProviderKind,
			&i.ProviderID,
			&i.Enabled,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedRepositoryContext = `-- name: SeedRepositoryContext :one
INSERT INTO okt_system.repository_contexts (repository_id, context, is_custom, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (repository_id, lower(context)) DO NOTHING
RETURNING repository_id, context, is_custom, description, created_at, updated_at
`

type SeedRepositoryContextParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Context      string      `json:"context"`
	IsCustom     bool        `json:"is_custom"`
	Description  string      `json:"description"`
}

// Single-row seed for contexts. Used by CreateRepository for each
// dbpedia label (is_custom=FALSE) and by the settings POST endpoint
// for custom contexts (is_custom=TRUE). ON CONFLICT DO NOTHING.
func (q *Queries) SeedRepositoryContext(ctx context.Context, arg SeedRepositoryContextParams) (OktSystemRepositoryContext, error) {
	row := q.db.QueryRow(ctx, seedRepositoryContext,
		arg.RepositoryID,
		arg.Context,
		arg.IsCustom,
		arg.Description,
	)
	var i OktSystemRepositoryContext
	err := row.Scan(
		&i.RepositoryID,
		&i.Context,
		&i.IsCustom,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const seedRepositoryProviderSetting = `-- name: SeedRepositoryProviderSetting :one

INSERT INTO okt_system.repository_provider_settings (repository_id, provider_kind, provider_id, enabled)
VALUES ($1, $2, $3, $4)
ON CONFLICT (repository_id, provider_kind, provider_id) DO NOTHING
RETURNING repository_id, provider_kind, provider_id, enabled, updated_at
`

type SeedRepositoryProviderSettingParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	ProviderKind string      `json:"provider_kind"`
	ProviderID   string      `json:"provider_id"`
	Enabled      bool        `json:"enabled"`
}

// repository_settings.sql — per-repository provider + context settings.
//
// These tables live in okt_system (repo metadata). The CreateRepository
// handler seeds both on creation; the RepositorySettings handler reads
// and mutates them; the extract_concepts worker reads the context list
// to build the concept-extraction prompt; the gate helpers in the
// source handler read the provider list to decide whether a search/
// retrieve call is allowed for the active repo.
// Single-row seed used by CreateRepository when iterating the live
// provider registry. ON CONFLICT DO NOTHING so a re-seed (e.g. a
// retry after a partial failure) is idempotent.
func (q *Queries) SeedRepositoryProviderSetting(ctx context.Context, arg SeedRepositoryProviderSettingParams) (OktSystemRepositoryProviderSetting, error) {
	row := q.db.QueryRow(ctx, seedRepositoryProviderSetting,
		arg.RepositoryID,
		arg.ProviderKind,
		arg.ProviderID,
		arg.Enabled,
	)
	var i OktSystemRepositoryProviderSetting
	err := row.Scan(
		&i.RepositoryID,
		&i.ProviderKind,
		&i.ProviderID,
		&i.Enabled,
		&i.UpdatedAt,
	)
	return i, err
}

const setRepositoryProviderEnabled = `-- name: SetRepositoryProviderEnabled :one
INSERT INTO okt_system.repository_provider_settings (repository_id, provider_kind, provider_id, enabled)
VALUES ($1, $2, $3, $4)
ON CONFLICT (repository_id, provider_kind, provider_id)
DO UPDATE SET enabled = EXCLUDED.enabled, updated_at = now()
RETURNING repository_id, provider_kind, provider_id, enabled, updated_at
`

type SetRepositoryProviderEnabledParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	ProviderKind string      `json:"provider_kind"`
	ProviderID   string      `json:"provider_id"`
	Enabled      bool        `json:"enabled"`
}

// Upsert the enabled flag for a (repo, kind, id) triple. Used by the
// settings PUT endpoint. The unique target is the PK, so ON CONFLICT
// DO UPDATE bumps enabled + updated_at.
func (q *Queries) SetRepositoryProviderEnabled(ctx context.Context, arg SetRepositoryProviderEnabledParams) (OktSystemRepositoryProviderSetting, error) {
	row := q.db.QueryRow(ctx, setRepositoryProviderEnabled,
		arg.RepositoryID,
		arg.ProviderKind,
		arg.ProviderID,
		arg.Enabled,
	)
	var i OktSystemRepositoryProviderSetting
	err := row.Scan(
		&i.RepositoryID,
		&i.ProviderKind,
		&i.ProviderID,
		&i.Enabled,
		&i.UpdatedAt,
	)
	return i, err
}

const setUnmappedContextPolicy = `-- name: SetUnmappedContextPolicy :exec
UPDATE repositories
SET unmapped_context_policy = $2,
    catch_all_context = $3,
    updated_at = now()
WHERE id = $1
`

type SetUnmappedContextPolicyParams struct {
	ID                    pgtype.UUID `json:"id"`
	UnmappedContextPolicy string      `json:"unmapped_context_policy"`
	CatchAllContext       *string     `json:"catch_all_context"`
}

// Update the per-repo pull policy for unmapped registry contexts.
// Called by the SetUnmappedPolicy handler. catch_all_context is
// NULL unless policy is 'catch_all'; the handler validates the
// label is a member of repository_contexts before accepting it.
func (q *Queries) SetUnmappedContextPolicy(ctx context.Context, arg SetUnmappedContextPolicyParams) error {
	_, err := q.db.Exec(ctx, setUnmappedContextPolicy, arg.ID, arg.UnmappedContextPolicy, arg.CatchAllContext)
	return err
}

const upsertRepositoryContext = `-- name: UpsertRepositoryContext :one
INSERT INTO okt_system.repository_contexts (repository_id, context, is_custom, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (repository_id, lower(context))
DO UPDATE SET description = EXCLUDED.description, updated_at = now()
RETURNING repository_id, context, is_custom, description, created_at, updated_at
`

type UpsertRepositoryContextParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Context      string      `json:"context"`
	IsCustom     bool        `json:"is_custom"`
	Description  string      `json:"description"`
}

// Add or update a custom context's description. The settings PUT
// endpoint edits description only (renaming a context is add-new +
// migrate + delete-old). ON CONFLICT DO UPDATE sets description +
// updated_at (is_custom is preserved so editing a dbpedia-derived
// label's description doesn't flip its custom flag — an admin
// annotating a dbpedia context keeps is_custom=FALSE).
func (q *Queries) UpsertRepositoryContext(ctx context.Context, arg UpsertRepositoryContextParams) (OktSystemRepositoryContext, error) {
	row := q.db.QueryRow(ctx, upsertRepositoryContext,
		arg.RepositoryID,
		arg.Context,
		arg.IsCustom,
		arg.Description,
	)
	var i OktSystemRepositoryContext
	err := row.Scan(
		&i.RepositoryID,
		&i.Context,
		&i.IsCustom,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepositoryContextMapping = `-- name: UpsertRepositoryContextMapping :one

INSERT INTO okt_system.repository_context_mappings (repository_id, local_context, registry_context)
VALUES ($1, $2, $3)
ON CONFLICT (repository_id, lower(local_context))
DO UPDATE SET registry_context = EXCLUDED.registry_context, updated_at = now()
RETURNING repository_id, local_context, registry_context, created_at, updated_at
`

type UpsertRepositoryContextMappingParams struct {
	RepositoryID    pgtype.UUID `json:"repository_id"`
	LocalContext    string      `json:"local_context"`
	RegistryContext string      `json:"registry_context"`
}

// ──────────────────────────────────────────────────────────────
// Context mappings (local ↔ registry). See migration 0038.
// ──────────────────────────────────────────────────────────────
// Add or update a local→registry mapping. The unique target is
// (repository_id, lower(local_context)) so a local context maps to
// exactly one registry context; ON CONFLICT DO UPDATE swaps the
// registry target + bumps updated_at. Used by the
// SetContextMapping handler (PUT .../settings/context-mappings).
func (q *Queries) UpsertRepositoryContextMapping(ctx context.Context, arg UpsertRepositoryContextMappingParams) (OktSystemRepositoryContextMapping, error) {
	row := q.db.QueryRow(ctx, upsertRepositoryContextMapping, arg.RepositoryID, arg.LocalContext, arg.RegistryContext)
	var i OktSystemRepositoryContextMapping
	err := row.Scan(
		&i.RepositoryID,
		&i.LocalContext,
		&i.RegistryContext,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepositoryModelSetting = `-- name: UpsertRepositoryModelSetting :one
INSERT INTO okt_system.repository_model_settings (repository_id, task_kind, model_id)
VALUES ($1, $2, $3)
ON CONFLICT (repository_id, task_kind)
DO UPDATE SET model_id = EXCLUDED.model_id, updated_at = now()
RETURNING repository_id, task_kind, model_id, updated_at
`

type UpsertRepositoryModelSettingParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	TaskKind     string      `json:"task_kind"`
	ModelID      *string     `json:"model_id"`
}

// Upsert a per-repo model override for a task kind. model_id may
// be NULL (clear → inherit global default). Called by the
// SetModelSetting handler (PUT .../settings/models).
func (q *Queries) UpsertRepositoryModelSetting(ctx context.Context, arg UpsertRepositoryModelSettingParams) (OktSystemRepositoryModelSetting, error) {
	row := q.db.QueryRow(ctx, upsertRepositoryModelSetting, arg.RepositoryID, arg.TaskKind, arg.ModelID)
	var i OktSystemRepositoryModelSetting
	err := row.Scan(
		&i.RepositoryID,
		&i.TaskKind,
		&i.ModelID,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepositoryReportSettings = `-- name: UpsertRepositoryReportSettings :one
INSERT INTO okt_system.repository_report_settings
    (repository_id, similarity_threshold, posture_classifier_enabled, max_facts_per_sentence, lexical_similarity_floor, context_window_before, context_window_after)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (repository_id)
DO UPDATE SET
    similarity_threshold        = EXCLUDED.similarity_threshold,
    posture_classifier_enabled = EXCLUDED.posture_classifier_enabled,
    max_facts_per_sentence      = EXCLUDED.max_facts_per_sentence,
    lexical_similarity_floor    = EXCLUDED.lexical_similarity_floor,
    context_window_before       = EXCLUDED.context_window_before,
    context_window_after        = EXCLUDED.context_window_after,
    updated_at = now()
RETURNING repository_id, similarity_threshold, posture_classifier_enabled, updated_at, max_facts_per_sentence, lexical_similarity_floor, context_window_before, context_window_after
`

type UpsertRepositoryReportSettingsParams struct {
	RepositoryID             pgtype.UUID `json:"repository_id"`
	SimilarityThreshold      *float64    `json:"similarity_threshold"`
	PostureClassifierEnabled bool        `json:"posture_classifier_enabled"`
	MaxFactsPerSentence      *int32      `json:"max_facts_per_sentence"`
	LexicalSimilarityFloor   *float64    `json:"lexical_similarity_floor"`
	ContextWindowBefore      *int32      `json:"context_window_before"`
	ContextWindowAfter       *int32      `json:"context_window_after"`
}

// Insert or update the per-repo report annotation settings. Pass
// similarity_threshold NULL to inherit the global default; pass
// posture_classifier_enabled false to turn the LLM step off for
// this repo without touching the global config; pass
// max_facts_per_sentence NULL to inherit the global
// max_facts_per_sentence (5), or a value in 1..50 to override; pass
// lexical_similarity_floor NULL to inherit the global default (0.6),
// or a value in 0..1 to override (the semantic-distance floor for the
// hybrid lexical fallback); pass context_window_before /
// context_window_after NULL to inherit the global defaults (2/2), or
// a value in 0..10 to override (the number of surrounding sentences
// the posture classifier receives before/after the candidate for
// disambiguation context).
func (q *Queries) UpsertRepositoryReportSettings(ctx context.Context, arg UpsertRepositoryReportSettingsParams) (OktSystemRepositoryReportSetting, error) {
	row := q.db.QueryRow(ctx, upsertRepositoryReportSettings,
		arg.RepositoryID,
		arg.SimilarityThreshold,
		arg.PostureClassifierEnabled,
		arg.MaxFactsPerSentence,
		arg.LexicalSimilarityFloor,
		arg.ContextWindowBefore,
		arg.ContextWindowAfter,
	)
	var i OktSystemRepositoryReportSetting
	err := row.Scan(
		&i.RepositoryID,
		&i.SimilarityThreshold,
		&i.PostureClassifierEnabled,
		&i.UpdatedAt,
		&i.MaxFactsPerSentence,
		&i.LexicalSimilarityFloor,
		&i.ContextWindowBefore,
		&i.ContextWindowAfter,
	)
	return i, err
}
