// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: repositories.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRepository = `-- name: CreateRepository :one
INSERT INTO repositories (name, slug, description, owner_id, database_name, tier)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, slug, description, owner_id, database_name, tier, created_at, updated_at, registry_id, auto_contribute, registry_enabled, unmapped_context_policy, catch_all_context, allowed_models, registry_push_level, registry_pull_level
`

type CreateRepositoryParams struct {
	Name         string      `json:"name"`
	Slug         string      `json:"slug"`
	Description  string      `json:"description"`
	OwnerID      pgtype.UUID `json:"owner_id"`
	DatabaseName string      `json:"database_name"`
	Tier         string      `json:"tier"`
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, createRepository,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.OwnerID,
		arg.DatabaseName,
		arg.Tier,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.OwnerID,
		&i.DatabaseName,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegistryID,
		&i.AutoContribute,
		&i.RegistryEnabled,
		&i.UnmappedContextPolicy,
		&i.CatchAllContext,
		&i.AllowedModels,
		&i.RegistryPushLevel,
		&i.RegistryPullLevel,
	)
	return i, err
}

const deleteRepository = `-- name: DeleteRepository :one
DELETE FROM repositories WHERE id = $1 RETURNING id, name, slug, description, owner_id, database_name, tier, created_at, updated_at, registry_id, auto_contribute, registry_enabled, unmapped_context_policy, catch_all_context, allowed_models, registry_push_level, registry_pull_level
`

func (q *Queries) DeleteRepository(ctx context.Context, id pgtype.UUID) (Repository, error) {
	row := q.db.QueryRow(ctx, deleteRepository, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.OwnerID,
		&i.DatabaseName,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegistryID,
		&i.AutoContribute,
		&i.RegistryEnabled,
		&i.UnmappedContextPolicy,
		&i.CatchAllContext,
		&i.AllowedModels,
		&i.RegistryPushLevel,
		&i.RegistryPullLevel,
	)
	return i, err
}

const getRepositoryAllowedModels = `-- name: GetRepositoryAllowedModels :one
SELECT allowed_models FROM repositories WHERE id = $1
`

// Per-repo model whitelist for the registry cache import. NULL
// means "inherit the global registry.allowed_models config"; a
// non-NULL array replaces the global list for this repo (per-repo
// replaces global). Read by the retrieve_source / pull_all workers
// to decide which decomposition models to import.
func (q *Queries) GetRepositoryAllowedModels(ctx context.Context, id pgtype.UUID) ([]string, error) {
	row := q.db.QueryRow(ctx, getRepositoryAllowedModels, id)
	var allowed_models []string
	err := row.Scan(&allowed_models)
	return allowed_models, err
}

const getRepositoryAutoContribute = `-- name: GetRepositoryAutoContribute :one
SELECT auto_contribute FROM repositories WHERE id = $1
`

// Single-column lookup of the auto_contribute flag. Read by the
// cleanup_facts worker to decide whether to chain contribute_source
// after a source finishes the ingestion pipeline, and by the
// settings handler to surface the flag in GetSettings.
func (q *Queries) GetRepositoryAutoContribute(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getRepositoryAutoContribute, id)
	var auto_contribute bool
	err := row.Scan(&auto_contribute)
	return auto_contribute, err
}

const getRepositoryByID = `-- name: GetRepositoryByID :one
SELECT id, name, slug, description, owner_id, database_name, tier, created_at, updated_at, registry_id, auto_contribute, registry_enabled, unmapped_context_policy, catch_all_context, allowed_models, registry_push_level, registry_pull_level FROM repositories WHERE id = $1
`

func (q *Queries) GetRepositoryByID(ctx context.Context, id pgtype.UUID) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByID, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.OwnerID,
		&i.DatabaseName,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegistryID,
		&i.AutoContribute,
		&i.RegistryEnabled,
		&i.UnmappedContextPolicy,
		&i.CatchAllContext,
		&i.AllowedModels,
		&i.RegistryPushLevel,
		&i.RegistryPullLevel,
	)
	return i, err
}

const getRepositoryBySlug = `-- name: GetRepositoryBySlug :one
SELECT id, name, slug, description, owner_id, database_name, tier, created_at, updated_at, registry_id, auto_contribute, registry_enabled, unmapped_context_policy, catch_all_context, allowed_models, registry_push_level, registry_pull_level FROM repositories WHERE slug = $1
`

func (q *Queries) GetRepositoryBySlug(ctx context.Context, slug string) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryBySlug, slug)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.OwnerID,
		&i.DatabaseName,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegistryID,
		&i.AutoContribute,
		&i.RegistryEnabled,
		&i.UnmappedContextPolicy,
		&i.CatchAllContext,
		&i.AllowedModels,
		&i.RegistryPushLevel,
		&i.RegistryPullLevel,
	)
	return i, err
}

const getRepositoryDatabaseName = `-- name: GetRepositoryDatabaseName :one
SELECT database_name FROM repositories WHERE id = $1
`

func (q *Queries) GetRepositoryDatabaseName(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getRepositoryDatabaseName, id)
	var database_name string
	err := row.Scan(&database_name)
	return database_name, err
}

const getRepositoryRegistryConfig = `-- name: GetRepositoryRegistryConfig :one
SELECT registry_id, registry_enabled FROM repositories WHERE id = $1
`

type GetRepositoryRegistryConfigRow struct {
	RegistryID      *string `json:"registry_id"`
	RegistryEnabled bool    `json:"registry_enabled"`
}

// Combined registry_id + registry_enabled lookup in one round-trip.
// Used by the workers and handlers that need both values to decide
// which client to use and whether the integration is on for this repo.
func (q *Queries) GetRepositoryRegistryConfig(ctx context.Context, id pgtype.UUID) (GetRepositoryRegistryConfigRow, error) {
	row := q.db.QueryRow(ctx, getRepositoryRegistryConfig, id)
	var i GetRepositoryRegistryConfigRow
	err := row.Scan(&i.RegistryID, &i.RegistryEnabled)
	return i, err
}

const getRepositoryRegistryEnabled = `-- name: GetRepositoryRegistryEnabled :one
SELECT registry_enabled FROM repositories WHERE id = $1
`

// Single-column lookup of the registry_enabled flag. Read by the
// retrieve_source worker (to skip the cache lookup) and the remote
// handler (to 503 the /remote endpoints) for a repo that has turned
// the integration off.
func (q *Queries) GetRepositoryRegistryEnabled(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getRepositoryRegistryEnabled, id)
	var registry_enabled bool
	err := row.Scan(&registry_enabled)
	return registry_enabled, err
}

const getRepositoryRegistryID = `-- name: GetRepositoryRegistryID :one
SELECT registry_id FROM repositories WHERE id = $1
`

func (q *Queries) GetRepositoryRegistryID(ctx context.Context, id pgtype.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getRepositoryRegistryID, id)
	var registry_id *string
	err := row.Scan(&registry_id)
	return registry_id, err
}

const getRepositorySlug = `-- name: GetRepositorySlug :one
SELECT slug FROM repositories WHERE id = $1
`

// Single-column lookup for the slug. Used by the
// source_decomposition worker to synthesize a service-routable
// image_url for image facts whose source image has no remote URL
// (PDF page renders stored under storage_key). Cheaper than
// fetching the whole row when only the slug is needed.
func (q *Queries) GetRepositorySlug(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getRepositorySlug, id)
	var slug string
	err := row.Scan(&slug)
	return slug, err
}

const getRepositorySyncLevels = `-- name: GetRepositorySyncLevels :one
SELECT registry_push_level, registry_pull_level FROM repositories WHERE id = $1
`

type GetRepositorySyncLevelsRow struct {
	RegistryPushLevel string `json:"registry_push_level"`
	RegistryPullLevel string `json:"registry_pull_level"`
}

// Combined push_level + pull_level lookup in one round-trip. Read by
// the contribute_source worker (push_level) and the pull workers
// (pull_level) to decide whether to include concepts/links/concept
// embeddings in the contribution or import. Defaults to 'concepts'
// (migration 0044) so existing repos keep full sync behavior.
func (q *Queries) GetRepositorySyncLevels(ctx context.Context, id pgtype.UUID) (GetRepositorySyncLevelsRow, error) {
	row := q.db.QueryRow(ctx, getRepositorySyncLevels, id)
	var i GetRepositorySyncLevelsRow
	err := row.Scan(&i.RegistryPushLevel, &i.RegistryPullLevel)
	return i, err
}

const listAllRepositories = `-- name: ListAllRepositories :many
SELECT id, name, slug, description, owner_id, database_name, tier, created_at, updated_at, registry_id, auto_contribute, registry_enabled, unmapped_context_policy, catch_all_context, allowed_models, registry_push_level, registry_pull_level FROM repositories ORDER BY created_at DESC
`

func (q *Queries) ListAllRepositories(ctx context.Context) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listAllRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.OwnerID,
			&i.DatabaseName,
			&i.Tier,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RegistryID,
			&i.AutoContribute,
			&i.RegistryEnabled,
			&i.UnmappedContextPolicy,
			&i.CatchAllContext,
			&i.AllowedModels,
			&i.RegistryPushLevel,
			&i.RegistryPullLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoriesByOwner = `-- name: ListRepositoriesByOwner :many
SELECT id, name, slug, description, owner_id, database_name, tier, created_at, updated_at, registry_id, auto_contribute, registry_enabled, unmapped_context_policy, catch_all_context, allowed_models, registry_push_level, registry_pull_level FROM repositories WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListRepositoriesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositoriesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.OwnerID,
			&i.DatabaseName,
			&i.Tier,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RegistryID,
			&i.AutoContribute,
			&i.RegistryEnabled,
			&i.UnmappedContextPolicy,
			&i.CatchAllContext,
			&i.AllowedModels,
			&i.RegistryPushLevel,
			&i.RegistryPullLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRepositoryAllowedModels = `-- name: SetRepositoryAllowedModels :exec
UPDATE repositories
SET allowed_models = $2, updated_at = now()
WHERE id = $1
`

type SetRepositoryAllowedModelsParams struct {
	ID            pgtype.UUID `json:"id"`
	AllowedModels []string    `json:"allowed_models"`
}

// Upsert the per-repo allowed_models list. Called by the
// SetRegistrySettings handler (PUT .../settings/registry) when the
// body carries an allowed_models field. Pass NULL to clear the
// per-repo override (revert to inheriting the global config); pass
// an array (incl. ["*"] or []) to set the per-repo whitelist.
func (q *Queries) SetRepositoryAllowedModels(ctx context.Context, arg SetRepositoryAllowedModelsParams) error {
	_, err := q.db.Exec(ctx, setRepositoryAllowedModels, arg.ID, arg.AllowedModels)
	return err
}

const setRepositoryAutoContribute = `-- name: SetRepositoryAutoContribute :exec
UPDATE repositories
SET auto_contribute = $2, updated_at = now()
WHERE id = $1
`

type SetRepositoryAutoContributeParams struct {
	ID             pgtype.UUID `json:"id"`
	AutoContribute bool        `json:"auto_contribute"`
}

// Upsert the auto_contribute flag for a repo. Called by the
// SetAutoContribute handler (PUT .../settings/auto-contribute).
func (q *Queries) SetRepositoryAutoContribute(ctx context.Context, arg SetRepositoryAutoContributeParams) error {
	_, err := q.db.Exec(ctx, setRepositoryAutoContribute, arg.ID, arg.AutoContribute)
	return err
}

const setRepositoryRegistryEnabled = `-- name: SetRepositoryRegistryEnabled :exec
UPDATE repositories
SET registry_enabled = $2, updated_at = now()
WHERE id = $1
`

type SetRepositoryRegistryEnabledParams struct {
	ID              pgtype.UUID `json:"id"`
	RegistryEnabled bool        `json:"registry_enabled"`
}

// Toggle the per-repo registry integration. Called by the
// SetRegistry handler. When FALSE, the retrieve_source worker
// skips the cache lookup and the /remote endpoints return 503.
func (q *Queries) SetRepositoryRegistryEnabled(ctx context.Context, arg SetRepositoryRegistryEnabledParams) error {
	_, err := q.db.Exec(ctx, setRepositoryRegistryEnabled, arg.ID, arg.RegistryEnabled)
	return err
}

const setRepositoryRegistryID = `-- name: SetRepositoryRegistryID :exec
UPDATE repositories
SET registry_id = $2, updated_at = now()
WHERE id = $1
`

type SetRepositoryRegistryIDParams struct {
	ID         pgtype.UUID `json:"id"`
	RegistryID *string     `json:"registry_id"`
}

// Update the per-repo registry selector. Called by the
// SetRegistry handler (PUT .../settings/registry). The id is
// validated against the configured registries list in the handler,
// not via a foreign key (registries are config, not a DB table).
func (q *Queries) SetRepositoryRegistryID(ctx context.Context, arg SetRepositoryRegistryIDParams) error {
	_, err := q.db.Exec(ctx, setRepositoryRegistryID, arg.ID, arg.RegistryID)
	return err
}

const setRepositorySyncLevels = `-- name: SetRepositorySyncLevels :exec
UPDATE repositories
SET registry_push_level = $2, registry_pull_level = $3, updated_at = now()
WHERE id = $1
`

type SetRepositorySyncLevelsParams struct {
	ID                pgtype.UUID `json:"id"`
	RegistryPushLevel string      `json:"registry_push_level"`
	RegistryPullLevel string      `json:"registry_pull_level"`
}

// Update the per-repo push/pull sync levels. Called by the
// SetSyncLevels handler (PUT .../settings/sync-levels). Each level is
// validated against the CHECK constraint ('facts' | 'concepts') in
// the handler before this call; passing an invalid value here would
// fail the constraint and surface as a 500.
func (q *Queries) SetRepositorySyncLevels(ctx context.Context, arg SetRepositorySyncLevelsParams) error {
	_, err := q.db.Exec(ctx, setRepositorySyncLevels, arg.ID, arg.RegistryPushLevel, arg.RegistryPullLevel)
	return err
}

const updateRepository = `-- name: UpdateRepository :one
UPDATE repositories
SET name = $2, description = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, description, owner_id, database_name, tier, created_at, updated_at, registry_id, auto_contribute, registry_enabled, unmapped_context_policy, catch_all_context, allowed_models, registry_push_level, registry_pull_level
`

type UpdateRepositoryParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

func (q *Queries) UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, updateRepository, arg.ID, arg.Name, arg.Description)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.OwnerID,
		&i.DatabaseName,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegistryID,
		&i.AutoContribute,
		&i.RegistryEnabled,
		&i.UnmappedContextPolicy,
		&i.CatchAllContext,
		&i.AllowedModels,
		&i.RegistryPushLevel,
		&i.RegistryPullLevel,
	)
	return i, err
}
