// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: summaries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimConceptForSummary = `-- name: ClaimConceptForSummary :one
UPDATE okt_repository.concepts
SET summarizing_at = now()
WHERE id = $1
  AND (summarizing_at IS NULL OR summarizing_at < now() - $2::interval)
RETURNING id
`

type ClaimConceptForSummaryParams struct {
	ID        pgtype.UUID     `json:"id"`
	Staleness pgtype.Interval `json:"staleness"`
}

// Atomically acquire the per-concept summarization lock. Returns
// the concept id on success; returns no rows when another worker
// already holds a fresh lock (summarizing_at IS NOT NULL AND
// summarizing_at >= now() - @staleness::interval). A stale lock
// (summarizing_at older than the staleness window) is reclaimable
// so a crashed worker doesn't wedge the concept forever. The
// staleness is passed as a Postgres interval string (e.g. "2h").
func (q *Queries) ClaimConceptForSummary(ctx context.Context, arg ClaimConceptForSummaryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, claimConceptForSummary, arg.ID, arg.Staleness)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const countFactsForConceptSummary = `-- name: CountFactsForConceptSummary :one
SELECT COUNT(*) FROM okt_repository.fact_concepts fc
WHERE fc.concept_id = $1
`

// Total fact count for a concept (over fact_concepts), used by the
// summarize_concepts worker to select a fact-summary curriculum
// tier (SummarizationConfig.TierFor). The fact_concepts PRIMARY KEY
// index on concept_id makes this a fast index-only scan. Distinct
// from CountFactsByConcept (concepts.sql) which joins facts and
// accepts a search predicate; this one is the bare count the worker
// needs to pick a batch_size/max_tokens tier.
func (q *Queries) CountFactsForConceptSummary(ctx context.Context, conceptID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFactsForConceptSummary, conceptID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSummariesByConcept = `-- name: CountSummariesByConcept :one
SELECT COUNT(*) FROM okt_repository.concept_summaries WHERE concept_id = $1
`

func (q *Queries) CountSummariesByConcept(ctx context.Context, conceptID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSummariesByConcept, conceptID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSummary = `-- name: CreateSummary :one
INSERT INTO okt_repository.concept_summaries (
    concept_id, repository_id, context, sequence_num,
    is_complete, fact_count, content, covered_fact_ids, model
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, concept_id, repository_id, context, sequence_num, is_complete, fact_count, content, covered_fact_ids, model, created_at, updated_at
`

type CreateSummaryParams struct {
	ConceptID      pgtype.UUID   `json:"concept_id"`
	RepositoryID   pgtype.UUID   `json:"repository_id"`
	Context        string        `json:"context"`
	SequenceNum    int32         `json:"sequence_num"`
	IsComplete     bool          `json:"is_complete"`
	FactCount      int32         `json:"fact_count"`
	Content        string        `json:"content"`
	CoveredFactIds []pgtype.UUID `json:"covered_fact_ids"`
	Model          *string       `json:"model"`
}

// Insert a new summary row. The caller passes the explicit
// sequence_num, is_complete, covered_fact_ids, content, fact_count,
// and the denormalized context/repository_id. Used for both the
// "freeze a slice" path (is_complete = TRUE) and the "seed a new
// open slice" path (is_complete = FALSE).
func (q *Queries) CreateSummary(ctx context.Context, arg CreateSummaryParams) (OktRepositoryConceptSummary, error) {
	row := q.db.QueryRow(ctx, createSummary,
		arg.ConceptID,
		arg.RepositoryID,
		arg.Context,
		arg.SequenceNum,
		arg.IsComplete,
		arg.FactCount,
		arg.Content,
		arg.CoveredFactIds,
		arg.Model,
	)
	var i OktRepositoryConceptSummary
	err := row.Scan(
		&i.ID,
		&i.ConceptID,
		&i.RepositoryID,
		&i.Context,
		&i.SequenceNum,
		&i.IsComplete,
		&i.FactCount,
		&i.Content,
		&i.CoveredFactIds,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsCompleteSummary = `-- name: ExistsCompleteSummary :one
SELECT EXISTS (
    SELECT 1
    FROM okt_repository.concept_summaries
    WHERE concept_id = $1 AND is_complete = TRUE
) AS exists
`

// Whether the concept has at least one frozen (is_complete = TRUE)
// summary slice. The worker uses this to decide whether to run the
// incremental open-accumulator path (only while no complete slice
// exists) or the batch-only path (once the first slice is frozen).
func (q *Queries) ExistsCompleteSummary(ctx context.Context, conceptID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existsCompleteSummary, conceptID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getFactsForSummary = `-- name: GetFactsForSummary :many
SELECT id, text FROM okt_repository.facts
WHERE id = ANY($1::uuid[])
`

type GetFactsForSummaryRow struct {
	ID   pgtype.UUID `json:"id"`
	Text string      `json:"text"`
}

// Bulk fetch of fact bodies by id list. Used by the worker to
// build FactInput rows for the LLM prompt without an N+1 query.
// ANY() on an empty array matches nothing, which is correct.
func (q *Queries) GetFactsForSummary(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetFactsForSummaryRow, error) {
	rows, err := q.db.Query(ctx, getFactsForSummary, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFactsForSummaryRow
	for rows.Next() {
		var i GetFactsForSummaryRow
		if err := rows.Scan(&i.ID, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxSummarySequenceNum = `-- name: GetMaxSummarySequenceNum :one
SELECT COALESCE(MAX(sequence_num), 0)::int AS sequence_num
FROM okt_repository.concept_summaries
WHERE concept_id = $1
`

// The highest sequence_num among a concept's summaries, or 0 when
// the concept has no summaries yet. Used by the worker to pick the
// next sequence_num when creating a new slice. The cast to int
// pins the sqlc return type to int32 (without it COALESCE on
// MAX(int) returns an interface{} in sqlc's Go emitter).
func (q *Queries) GetMaxSummarySequenceNum(ctx context.Context, conceptID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxSummarySequenceNum, conceptID)
	var sequence_num int32
	err := row.Scan(&sequence_num)
	return sequence_num, err
}

const getOpenSummary = `-- name: GetOpenSummary :one
SELECT id, concept_id, repository_id, context, sequence_num, is_complete, fact_count, content, covered_fact_ids, model, created_at, updated_at FROM okt_repository.concept_summaries
WHERE concept_id = $1 AND is_complete = FALSE
`

// The single open (is_complete = FALSE) summary for a concept, or
// no rows when none exists. The unique partial index
// uq_concept_summaries_concept_open guarantees at most one open
// summary per concept_id, so this is a scalar lookup.
func (q *Queries) GetOpenSummary(ctx context.Context, conceptID pgtype.UUID) (OktRepositoryConceptSummary, error) {
	row := q.db.QueryRow(ctx, getOpenSummary, conceptID)
	var i OktRepositoryConceptSummary
	err := row.Scan(
		&i.ID,
		&i.ConceptID,
		&i.RepositoryID,
		&i.Context,
		&i.SequenceNum,
		&i.IsComplete,
		&i.FactCount,
		&i.Content,
		&i.CoveredFactIds,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllFactIDsForConcept = `-- name: ListAllFactIDsForConcept :many
SELECT fc.fact_id
FROM okt_repository.fact_concepts fc
WHERE fc.concept_id = $1
ORDER BY fc.first_seen_at
`

// Every fact_id linked to a concept, ordered by first_seen_at.
// Used to reconstruct the open slice's covered set together with
// the newly arrived facts when regenerating an open summary.
func (q *Queries) ListAllFactIDsForConcept(ctx context.Context, conceptID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAllFactIDsForConcept, conceptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var fact_id pgtype.UUID
		if err := rows.Scan(&fact_id); err != nil {
			return nil, err
		}
		items = append(items, fact_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactSourcesByFactIDs = `-- name: ListFactSourcesByFactIDs :many
SELECT fs.fact_id,
       fs.source_id,
       fs.first_seen_at,
       s.url,
       s.parsed_title
FROM okt_repository.fact_sources fs
JOIN okt_repository.sources s ON s.id = fs.source_id
WHERE fs.fact_id = ANY($1::uuid[])
ORDER BY fs.fact_id, fs.first_seen_at
`

type ListFactSourcesByFactIDsRow struct {
	FactID      pgtype.UUID        `json:"fact_id"`
	SourceID    pgtype.UUID        `json:"source_id"`
	FirstSeenAt pgtype.Timestamptz `json:"first_seen_at"`
	Url         string             `json:"url"`
	ParsedTitle *string            `json:"parsed_title"`
}

// Batched source attribution: one row per (fact, source) for the
// given fact_id set. Joined with sources.url + parsed_title so the
// worker can build the "(BBC; J. Smith)" parenthetical for the
// prompt. Ordered by fact_id, first_seen_at so the Go grouping is
// deterministic. ANY() on an empty array matches nothing.
func (q *Queries) ListFactSourcesByFactIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListFactSourcesByFactIDsRow, error) {
	rows, err := q.db.Query(ctx, listFactSourcesByFactIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFactSourcesByFactIDsRow
	for rows.Next() {
		var i ListFactSourcesByFactIDsRow
		if err := rows.Scan(
			&i.FactID,
			&i.SourceID,
			&i.FirstSeenAt,
			&i.Url,
			&i.ParsedTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSummariesByConcept = `-- name: ListSummariesByConcept :many
SELECT id, concept_id, repository_id, context, sequence_num, is_complete, fact_count, content, covered_fact_ids, model, created_at, updated_at FROM okt_repository.concept_summaries
WHERE concept_id = $1
ORDER BY sequence_num
`

// Every summary for a concept, ordered by sequence_num so the
// oldest slice is first. Used by the HTTP read endpoint and by the
// worker to reconstruct the open slice's covered set.
func (q *Queries) ListSummariesByConcept(ctx context.Context, conceptID pgtype.UUID) ([]OktRepositoryConceptSummary, error) {
	rows, err := q.db.Query(ctx, listSummariesByConcept, conceptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktRepositoryConceptSummary
	for rows.Next() {
		var i OktRepositoryConceptSummary
		if err := rows.Scan(
			&i.ID,
			&i.ConceptID,
			&i.RepositoryID,
			&i.Context,
			&i.SequenceNum,
			&i.IsComplete,
			&i.FactCount,
			&i.Content,
			&i.CoveredFactIds,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTouchedConceptsForSummary = `-- name: ListTouchedConceptsForSummary :many

SELECT DISTINCT c.id, c.canonical_name, c.context, c.repository_id
FROM okt_repository.concepts c
JOIN okt_repository.fact_concepts fc ON fc.concept_id = c.id
JOIN okt_repository.fact_sources fs ON fs.fact_id = fc.fact_id
WHERE c.repository_id = $1
  AND fs.source_id = $2
ORDER BY c.canonical_name
`

type ListTouchedConceptsForSummaryParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	SourceID     pgtype.UUID `json:"source_id"`
}

type ListTouchedConceptsForSummaryRow struct {
	ID            pgtype.UUID `json:"id"`
	CanonicalName string      `json:"canonical_name"`
	Context       string      `json:"context"`
	RepositoryID  pgtype.UUID `json:"repository_id"`
}

// summaries.sql — concept summarization queries.
//
// A concept_summary is an incremental LLM-produced synthesis of the
// facts linked to a (concept, context) pair. The summarization task
// (tasks.SummarizeConcepts) fans out from extract_concepts in
// parallel with embed_concepts. See migration 0026 for the schema
// and the slicing/locking model.
//
// Slicing model: the first slice (sequence_num 1) is an "open
// accumulator" — regenerated as new facts trickle in, until it
// reaches BatchSize covered facts and freezes (is_complete = TRUE).
// Once a complete slice exists, the worker switches to batch-only
// mode: it only emits complete BatchSize slices, never an open
// remainder, and skips the pass entirely when fewer than BatchSize
// new facts have arrived. This caps LLM cost by spending one call
// per fact while a concept is still small, then one call per full
// batch once it has crystallized.
// Source-scoped: distinct concept_ids linked (via fact_concepts →
// fact_sources) to at least one fact from THIS source. Used by the
// summarize_concepts worker to know which concepts the current
// source's extract_concepts pass touched. DISTINCT because the
// join expands (a concept links to many facts, a fact to many
// sources). The worker passes the resulting list as the explicit
// ConceptIDs chunk of one SummarizeConceptsArgs job per chunk.
func (q *Queries) ListTouchedConceptsForSummary(ctx context.Context, arg ListTouchedConceptsForSummaryParams) ([]ListTouchedConceptsForSummaryRow, error) {
	rows, err := q.db.Query(ctx, listTouchedConceptsForSummary, arg.RepositoryID, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTouchedConceptsForSummaryRow
	for rows.Next() {
		var i ListTouchedConceptsForSummaryRow
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalName,
			&i.Context,
			&i.RepositoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTouchedConceptsForSummaryByRepo = `-- name: ListTouchedConceptsForSummaryByRepo :many
SELECT DISTINCT c.id, c.canonical_name, c.context, c.repository_id
FROM okt_repository.concepts c
JOIN okt_repository.fact_concepts fc ON fc.concept_id = c.id
JOIN okt_repository.fact_sources fs ON fs.fact_id = fc.fact_id
JOIN okt_repository.sources s ON fs.source_id = s.id
WHERE c.repository_id = $1
ORDER BY c.canonical_name
`

type ListTouchedConceptsForSummaryByRepoRow struct {
	ID            pgtype.UUID `json:"id"`
	CanonicalName string      `json:"canonical_name"`
	Context       string      `json:"context"`
	RepositoryID  pgtype.UUID `json:"repository_id"`
}

// Repo-wide variant: distinct concept_ids for a repository. Used
// when SummarizeConceptsArgs.SourceID is empty (manual re-enqueue
// / periodic catch-up). Same JOIN shape as the source-scoped
// variant.
func (q *Queries) ListTouchedConceptsForSummaryByRepo(ctx context.Context, repositoryID pgtype.UUID) ([]ListTouchedConceptsForSummaryByRepoRow, error) {
	rows, err := q.db.Query(ctx, listTouchedConceptsForSummaryByRepo, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTouchedConceptsForSummaryByRepoRow
	for rows.Next() {
		var i ListTouchedConceptsForSummaryByRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalName,
			&i.Context,
			&i.RepositoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUncoveredFactIDsForSummary = `-- name: ListUncoveredFactIDsForSummary :many
SELECT fc.fact_id
FROM okt_repository.fact_concepts fc
WHERE fc.concept_id = $1
  AND NOT EXISTS (
      SELECT 1
      FROM okt_repository.concept_summaries cs
      WHERE cs.concept_id = fc.concept_id
        AND fc.fact_id = ANY(cs.covered_fact_ids)
  )
ORDER BY fc.first_seen_at
`

// Fact_ids linked to a concept that are NOT in any of its existing
// summaries' covered_fact_ids. These are the new facts the worker
// needs to fold into the open slice (or seed a new one). Ordered
// by fact_concepts.first_seen_at so the slicing is deterministic
// (the oldest facts land in the oldest slice).
func (q *Queries) ListUncoveredFactIDsForSummary(ctx context.Context, conceptID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listUncoveredFactIDsForSummary, conceptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var fact_id pgtype.UUID
		if err := rows.Scan(&fact_id); err != nil {
			return nil, err
		}
		items = append(items, fact_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseConceptSummaryLock = `-- name: ReleaseConceptSummaryLock :exec
UPDATE okt_repository.concepts
SET summarizing_at = NULL
WHERE id = $1
`

// Release the per-concept summarization lock. Called by the worker
// in a defer so a panic mid-loop still releases. The lock is
// best-effort: a query error is logged and swallowed so a failing
// release doesn't poison the result.
func (q *Queries) ReleaseConceptSummaryLock(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, releaseConceptSummaryLock, id)
	return err
}

const updateSummary = `-- name: UpdateSummary :one
UPDATE okt_repository.concept_summaries
SET content = $2,
    covered_fact_ids = $3,
    fact_count = $4,
    is_complete = $5,
    model = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, concept_id, repository_id, context, sequence_num, is_complete, fact_count, content, covered_fact_ids, model, created_at, updated_at
`

type UpdateSummaryParams struct {
	ID             pgtype.UUID   `json:"id"`
	Content        string        `json:"content"`
	CoveredFactIds []pgtype.UUID `json:"covered_fact_ids"`
	FactCount      int32         `json:"fact_count"`
	IsComplete     bool          `json:"is_complete"`
	Model          *string       `json:"model"`
}

// Regenerate an existing summary row. Used by the worker to update
// the open slice as new facts arrive (covered_fact_ids grows,
// fact_count grows, content is regenerated) and to freeze it
// (is_complete flips to TRUE) when the covered set reaches
// BatchSize. updated_at is bumped automatically by the trigger-free
// DEFAULT now() on the column? No — we set it explicitly so the
// row carries a meaningful "last regenerated" timestamp even though
// the column has a DEFAULT; the explicit SET wins.
func (q *Queries) UpdateSummary(ctx context.Context, arg UpdateSummaryParams) (OktRepositoryConceptSummary, error) {
	row := q.db.QueryRow(ctx, updateSummary,
		arg.ID,
		arg.Content,
		arg.CoveredFactIds,
		arg.FactCount,
		arg.IsComplete,
		arg.Model,
	)
	var i OktRepositoryConceptSummary
	err := row.Scan(
		&i.ID,
		&i.ConceptID,
		&i.RepositoryID,
		&i.Context,
		&i.SequenceNum,
		&i.IsComplete,
		&i.FactCount,
		&i.Content,
		&i.CoveredFactIds,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
