// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: syntheses.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSynthesesByRepo = `-- name: CountSynthesesByRepo :one
SELECT COUNT(*) FROM okt_repository.concept_syntheses
WHERE repository_id = $1
`

func (q *Queries) CountSynthesesByRepo(ctx context.Context, repositoryID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSynthesesByRepo, repositoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSynthesisByCanonicalName = `-- name: DeleteSynthesisByCanonicalName :exec
DELETE FROM okt_repository.concept_syntheses
WHERE repository_id = $1
  AND lower(canonical_name) = lower($2)
`

type DeleteSynthesisByCanonicalNameParams struct {
	RepositoryID  pgtype.UUID `json:"repository_id"`
	CanonicalName string      `json:"canonical_name"`
}

// Delete a synthesis row by (repository_id, lower(canonical_name)).
// Used by refine_concepts when a merge deletes the loser concept:
// concept_syntheses has no FK to concepts.id (it's keyed by
// lower(canonical_name)), so deleting the concept leaves the
// synthesis row orphaned. This query cleans it up so the next
// synthesis regen for the surviving concept doesn't leave a stale
// row under the old name.
func (q *Queries) DeleteSynthesisByCanonicalName(ctx context.Context, arg DeleteSynthesisByCanonicalNameParams) error {
	_, err := q.db.Exec(ctx, deleteSynthesisByCanonicalName, arg.RepositoryID, arg.CanonicalName)
	return err
}

const getSynthesisByGroup = `-- name: GetSynthesisByGroup :one
SELECT id, repository_id, canonical_name, content, covered_summary_ids, covered_concept_ids, embedded_image_ids, model, created_at, updated_at FROM okt_repository.concept_syntheses
WHERE repository_id = $1
  AND lower(canonical_name) = lower($2)
`

type GetSynthesisByGroupParams struct {
	RepositoryID  pgtype.UUID `json:"repository_id"`
	CanonicalName string      `json:"canonical_name"`
}

// The single synthesis row for (repository_id, lower(canonical_name)),
// or no rows when none exists. The unique index
// uq_concept_syntheses_repo_name guarantees at most one row per
// group, so this is a scalar lookup.
func (q *Queries) GetSynthesisByGroup(ctx context.Context, arg GetSynthesisByGroupParams) (OktRepositoryConceptSynthesis, error) {
	row := q.db.QueryRow(ctx, getSynthesisByGroup, arg.RepositoryID, arg.CanonicalName)
	var i OktRepositoryConceptSynthesis
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.CanonicalName,
		&i.Content,
		&i.CoveredSummaryIds,
		&i.CoveredConceptIds,
		&i.EmbeddedImageIds,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroupConceptIDs = `-- name: ListGroupConceptIDs :many
SELECT c.id
FROM okt_repository.concepts c
WHERE c.repository_id = $1
  AND lower(c.canonical_name) = lower($2)
`

type ListGroupConceptIDsParams struct {
	RepositoryID  pgtype.UUID `json:"repository_id"`
	CanonicalName string      `json:"canonical_name"`
}

// The concept_ids sharing (repository_id, lower(canonical_name)).
// Used by the worker to populate covered_concept_ids on upsert so the
// read path knows which per-context concept_ids were folded.
func (q *Queries) ListGroupConceptIDs(ctx context.Context, arg ListGroupConceptIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listGroupConceptIDs, arg.RepositoryID, arg.CanonicalName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupImageFacts = `-- name: ListGroupImageFacts :many
SELECT f.id, f.text, f.image_url
FROM okt_repository.facts f
JOIN okt_repository.fact_concepts fc ON fc.fact_id = f.id
JOIN okt_repository.concepts c ON c.id = fc.concept_id
WHERE c.repository_id = $1
  AND lower(c.canonical_name) = lower($2)
  AND f.fact_kind = 'image'
  AND f.image_url IS NOT NULL
ORDER BY fc.first_seen_at DESC
LIMIT $3
`

type ListGroupImageFactsParams struct {
	RepositoryID  pgtype.UUID `json:"repository_id"`
	CanonicalName string      `json:"canonical_name"`
	Cap           int32       `json:"cap"`
}

type ListGroupImageFactsRow struct {
	ID       pgtype.UUID `json:"id"`
	Text     string      `json:"text"`
	ImageUrl *string     `json:"image_url"`
}

// Image facts (fact_kind = 'image' with a non-null image_url) linked
// via fact_concepts to any concept_id in the
// (repository_id, lower(canonical_name)) group. The worker passes
// these as candidates to the image-picker LLM call (or directly to
// the synthesis when the candidate count is <= MaxImages). Ordered
// by fact_concepts.first_seen_at DESC so the most recently linked
// images come first, then capped at @cap by the caller (default 50).
// Returns the fact id, text (the image description the extractor
// produced), and image_url (service-routable; the frontend resolves
// it to a blob URL via the storage endpoint).
func (q *Queries) ListGroupImageFacts(ctx context.Context, arg ListGroupImageFactsParams) ([]ListGroupImageFactsRow, error) {
	rows, err := q.db.Query(ctx, listGroupImageFacts, arg.RepositoryID, arg.CanonicalName, arg.Cap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupImageFactsRow
	for rows.Next() {
		var i ListGroupImageFactsRow
		if err := rows.Scan(&i.ID, &i.Text, &i.ImageUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImageFactsByIDs = `-- name: ListImageFactsByIDs :many
SELECT id, text, image_url, fact_kind
FROM okt_repository.facts
WHERE id = ANY($1::uuid[])
  AND fact_kind = 'image'
`

type ListImageFactsByIDsRow struct {
	ID       pgtype.UUID `json:"id"`
	Text     string      `json:"text"`
	ImageUrl *string     `json:"image_url"`
	FactKind string      `json:"fact_kind"`
}

// Bulk fetch of image facts by id list for the synthesis read path.
// The GET /definition endpoint uses this to eager-load the
// image_url + text of every fact the synthesis embeds via
// ![alt](<fact_id>), so the frontend can resolve storage URLs to
// blob URLs without N extra calls. ANY() on an empty array matches
// nothing, which is correct (a synthesis with no embedded images
// returns no rows). Filters to fact_kind = 'image' so a stale
// embedded_image_id that no longer points at an image fact is
// silently dropped.
func (q *Queries) ListImageFactsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListImageFactsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listImageFactsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImageFactsByIDsRow
	for rows.Next() {
		var i ListImageFactsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.ImageUrl,
			&i.FactKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSummariesByCanonicalNameGroup = `-- name: ListSummariesByCanonicalNameGroup :many

SELECT cs.id, cs.concept_id, cs.repository_id, cs.context, cs.sequence_num, cs.is_complete, cs.fact_count, cs.content, cs.covered_fact_ids, cs.model, cs.created_at, cs.updated_at
FROM okt_repository.concept_summaries cs
JOIN okt_repository.concepts c ON c.id = cs.concept_id
WHERE c.repository_id = $1
  AND lower(c.canonical_name) = lower($2)
ORDER BY cs.concept_id, cs.sequence_num
`

type ListSummariesByCanonicalNameGroupParams struct {
	RepositoryID  pgtype.UUID `json:"repository_id"`
	CanonicalName string      `json:"canonical_name"`
}

// syntheses.sql — concept synthesis queries.
//
// A concept_synthesis is the single authoritative "definition" the
// system produces for a canonical-name group, folding together ALL
// summary slices across every concept_id sharing lower(canonical_name)
// in a repository. See migration 0028 for the schema and the
// per-group upsert model. The synthesize_concept worker (chained from
// summarize_concepts) is the only writer; the HTTP layer is read-only.
// Every concept_summaries row for every concept_id in the
// (repository_id, lower(canonical_name)) group, ordered by
// concept_id then sequence_num so the worker can render the slices
// in a stable order into the synthesis prompt. Joins concepts to
// filter by lower(canonical_name).
func (q *Queries) ListSummariesByCanonicalNameGroup(ctx context.Context, arg ListSummariesByCanonicalNameGroupParams) ([]OktRepositoryConceptSummary, error) {
	rows, err := q.db.Query(ctx, listSummariesByCanonicalNameGroup, arg.RepositoryID, arg.CanonicalName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktRepositoryConceptSummary
	for rows.Next() {
		var i OktRepositoryConceptSummary
		if err := rows.Scan(
			&i.ID,
			&i.ConceptID,
			&i.RepositoryID,
			&i.Context,
			&i.SequenceNum,
			&i.IsComplete,
			&i.FactCount,
			&i.Content,
			&i.CoveredFactIds,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSynthesesByRepo = `-- name: ListSynthesesByRepo :many
SELECT id, repository_id, canonical_name, content, covered_summary_ids, covered_concept_ids, embedded_image_ids, model, created_at, updated_at FROM okt_repository.concept_syntheses
WHERE repository_id = $1
ORDER BY canonical_name
LIMIT $2 OFFSET $3
`

type ListSynthesesByRepoParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

// Every synthesis in a repository, ordered by canonical_name. Used
// by the repo-level list endpoint. Paginated by the caller via
// LIMIT/OFFSET.
func (q *Queries) ListSynthesesByRepo(ctx context.Context, arg ListSynthesesByRepoParams) ([]OktRepositoryConceptSynthesis, error) {
	rows, err := q.db.Query(ctx, listSynthesesByRepo, arg.RepositoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OktRepositoryConceptSynthesis
	for rows.Next() {
		var i OktRepositoryConceptSynthesis
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.CanonicalName,
			&i.Content,
			&i.CoveredSummaryIds,
			&i.CoveredConceptIds,
			&i.EmbeddedImageIds,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseAdvisoryLockForSynthesis = `-- name: ReleaseAdvisoryLockForSynthesis :exec
SELECT pg_advisory_unlock(hashtext($1))
`

// Release the advisory lock acquired by TryAdvisoryLockForSynthesis.
// Best-effort: a query error is logged and swallowed by the caller so
// a failing release doesn't poison the synthesis result.
func (q *Queries) ReleaseAdvisoryLockForSynthesis(ctx context.Context, hashtext string) error {
	_, err := q.db.Exec(ctx, releaseAdvisoryLockForSynthesis, hashtext)
	return err
}

const tryAdvisoryLockForSynthesis = `-- name: TryAdvisoryLockForSynthesis :one
SELECT pg_try_advisory_lock(hashtext($1)) AS ok
`

// Attempt to acquire a session-level Postgres advisory lock keyed by
// a hash of the group key string. Returns true on success, false when
// another worker already holds the lock. The lock is per-connection;
// the caller MUST release it via ReleaseAdvisoryLockForSynthesis in a
// defer. A crashed worker's connection returns to the pool and pgx
// releases the lock automatically, so no staleness window is needed.
func (q *Queries) TryAdvisoryLockForSynthesis(ctx context.Context, hashtext string) (bool, error) {
	row := q.db.QueryRow(ctx, tryAdvisoryLockForSynthesis, hashtext)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const upsertSynthesis = `-- name: UpsertSynthesis :one
INSERT INTO okt_repository.concept_syntheses (
    repository_id, canonical_name, content,
    covered_summary_ids, covered_concept_ids, embedded_image_ids, model
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (repository_id, lower(canonical_name)) DO UPDATE SET
    content             = EXCLUDED.content,
    covered_summary_ids = EXCLUDED.covered_summary_ids,
    covered_concept_ids = EXCLUDED.covered_concept_ids,
    embedded_image_ids  = EXCLUDED.embedded_image_ids,
    model               = EXCLUDED.model,
    updated_at          = now()
RETURNING id, repository_id, canonical_name, content, covered_summary_ids, covered_concept_ids, embedded_image_ids, model, created_at, updated_at
`

type UpsertSynthesisParams struct {
	RepositoryID      pgtype.UUID   `json:"repository_id"`
	CanonicalName     string        `json:"canonical_name"`
	Content           string        `json:"content"`
	CoveredSummaryIds []pgtype.UUID `json:"covered_summary_ids"`
	CoveredConceptIds []pgtype.UUID `json:"covered_concept_ids"`
	EmbeddedImageIds  []pgtype.UUID `json:"embedded_image_ids"`
	Model             *string       `json:"model"`
}

// Insert a new synthesis row, or update the existing row for the
// (repository_id, lower(canonical_name)) group. The ON CONFLICT
// targets the unique index uq_concept_syntheses_repo_name (the
// expression index on lower(canonical_name)). On conflict, content,
// covered_summary_ids, covered_concept_ids, embedded_image_ids, and
// model are replaced; updated_at is bumped explicitly (the column's
// DEFAULT now() only applies on insert). canonical_name is NOT
// overwritten — the original casing is preserved.
func (q *Queries) UpsertSynthesis(ctx context.Context, arg UpsertSynthesisParams) (OktRepositoryConceptSynthesis, error) {
	row := q.db.QueryRow(ctx, upsertSynthesis,
		arg.RepositoryID,
		arg.CanonicalName,
		arg.Content,
		arg.CoveredSummaryIds,
		arg.CoveredConceptIds,
		arg.EmbeddedImageIds,
		arg.Model,
	)
	var i OktRepositoryConceptSynthesis
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.CanonicalName,
		&i.Content,
		&i.CoveredSummaryIds,
		&i.CoveredConceptIds,
		&i.EmbeddedImageIds,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
