-- 0023_concepts.up.sql
--
-- Concept extraction Phase 1: the canonical concept entity, its
-- alternate surface forms (aliases), and the fact↔concept junction.
--
-- A concept is a repo-scoped, canonical-named entity assigned a
-- context (an L3 ontology class label, e.g. "Politician"). Concepts
-- are produced by the extract_concepts worker, which runs over a
-- repository's stable facts after dedup. The end goal is the
-- fact_concepts junction: querying a concept returns every fact
-- linked to it (e.g. "DNA" → 200 facts).
--
-- Matching is text-search-based: a new (concept, context) pair is
-- matched against existing concepts by lower(canonical_name) OR
-- lower(alias_text), scoped by (repository_id, lower(context)).
-- Seed aliases are generated inline by the concept-extraction
-- provider to boost match chance; expanded aliases + the canonical
-- name are generated by the alias provider for newly created
-- concepts only (matched concepts merge seed aliases for free).
--
-- Phase 2 (disambiguation attractor + parent_concept_id +
-- concept_disambiguations table) is deferred to a later migration.

CREATE TABLE IF NOT EXISTS okt_repository.concepts (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    repository_id   UUID NOT NULL REFERENCES okt_system.repositories(id) ON DELETE CASCADE,
    canonical_name  TEXT NOT NULL,
    context         TEXT NOT NULL,                -- DBpedia L3 class label
    description     TEXT,
    embedded_at     TIMESTAMPTZ,
    embedded_model  TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_concepts_repo
    ON okt_repository.concepts (repository_id);
-- Unique on (repository_id, lower(canonical_name), lower(context)).
-- Expressed as a UNIQUE INDEX on lower() expressions because sqlc's
-- migration parser does not accept a function expression inside a
-- table-level UNIQUE constraint, and because a case-insensitive
-- uniqueness on name+context is exactly what we want (the same
-- concept with different casing is the same concept).
CREATE UNIQUE INDEX IF NOT EXISTS uq_concepts_repo_name_context
    ON okt_repository.concepts (repository_id, lower(canonical_name), lower(context));

CREATE TABLE IF NOT EXISTS okt_repository.concept_aliases (
    id         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    concept_id UUID NOT NULL REFERENCES okt_repository.concepts(id) ON DELETE CASCADE,
    alias_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_concept_aliases_lookup
    ON okt_repository.concept_aliases (lower(alias_text));
CREATE INDEX IF NOT EXISTS idx_concept_aliases_concept
    ON okt_repository.concept_aliases (concept_id);
-- Unique on (concept_id, lower(alias_text)) so the same alias with
-- different casing is deduplicated at insert time.
CREATE UNIQUE INDEX IF NOT EXISTS uq_concept_aliases_concept_text
    ON okt_repository.concept_aliases (concept_id, lower(alias_text));

CREATE TABLE IF NOT EXISTS okt_repository.fact_concepts (
    fact_id       UUID NOT NULL REFERENCES okt_repository.facts(id) ON DELETE CASCADE,
    concept_id    UUID NOT NULL REFERENCES okt_repository.concepts(id) ON DELETE CASCADE,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (fact_id, concept_id)
);
CREATE INDEX IF NOT EXISTS idx_fact_concepts_concept
    ON okt_repository.fact_concepts (concept_id);